### ISSUE TITLE
Mention `git submodule update --init --recursive` in the contributing guide

### ISSUE THREAD

**Issue by slaskawi** [mongodb/mongodb-kubernetes-operator#1003]
This repo uses submodules and it would be nice to mention that it needs to be cloned using `git clone --recurse-submodules --remote-submodules` or the submodules need to be updated manually (e.g. by using `git submodule update --init --recursive`)

**Comment by irajdeep** [comment]
addressed in this PR: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1076
