### ISSUE TITLE
mongod complains about numa

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#1006]
mongodb complains about numa:

CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]

is there some switch i didn't see to add that?
or is it save to ignore that?

**Operator Information**
 - Operator Version 0.7.3
 - MongoDB Image used 4.4.11

**Comment by joe-eklund** [comment]
@fireba11 
> Operator overrides the default entrypoint (/usr/local/bin/docker-entrypoint.sh) which contains the /usr/bin/numactl --interleave=all start mode but doesn't provide it's own way to run it like that.

Hey I just ran into this problem, did you ever find a solution to this?

**Comment by fireba11** [comment]
nope
