### ISSUE TITLE
MongoDB operator and databases in different namespaces

### ISSUE THREAD

**Issue by mrszop** [mongodb/mongodb-kubernetes-operator#1015]
Hello community,

it seems like there is something missing (or I am missing something) with the helm chart installation of the MongoDB operator. My idea is to separate MongoDB databases and the operator. My approach is following:

- create namespace "mongodb-operator" for operator and "mongodb-databases" for MongoDB databases

```sh
k create ns mongodb-operator
k create ns mongodb-databases
```

- take helm chart and modify `values.yaml` to let MongoDB operator watch all namespaces

```yaml
## Operator
operator:
  watchNamespace: "*"

## Operator's database
database:
  name: mongodb-database
  namespace: mongodb-operator
```

- apply helm chart

```sh
helm install -f values.yaml
```

- apply a demo MongoDB database example

```sh
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mongodb-databases
```

I get following error when checking MongoDB database:

```sh
k -n mongodb-databases describe statefulset.apps/example-mongodb

Events:
  Type     Reason        Age                     From                    Message
  ----     ------        ----                    ----                    -------
  Warning  FailedCreate  2m20s (x17 over 7m48s)  statefulset-controller  create Pod example-mongodb-0 in StatefulSet example-mongodb failed error: pods "example-mongodb-0" is forbidden: error looking up service account mongodb-databases/mongodb-database: serviceaccount "mongodb-database" not found
```

As far as I can see, there is a problem with the service account. The service account the MongoDB database statefulset is refering to is not available in the mongodb-databases namespace (mongodb-databases/mongodb-database). But I don't know why it is referring to this account or why it is not creating on its own nor what RBAC it actually needs :/

```sh
k -n mongodb-operator get sa mongodb-kubernetes-operator
NAME                          SECRETS   AGE
mongodb-kubernetes-operator   1         31m
```

Cheers,
Szop

**Comment by mrszop** [comment]
Hey,

I've got it finally running. I suggest a small update of your documentation. You provide two different ways of installing MongoDB Operator: via helm chart and via native kubectl. Unfortunately you need to do a manual step which is described [in the native kubectl part on the helm chart installation too](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#install-in-a-different-namespace-using-kubectl):

>For each namespace that you want the Operator to watch, run the following commands to deploy a Role, RoleBinding and ServiceAccount in that namespace:

```sh
kubectl apply -k config/rbac --namespace <my-namespace>
```

This needs to be applied after the helm chart installation of operator too, if you want to use databases in a different namespace then the operator itself.

Cheers,
Szop

**Comment by madalinignisca** [comment]
I have another case for which I'm evaluating the official operator vs the percona one.
I have each client isolated in it's namespace with all their resources. I would like them to be able to have their mongo cluster in their namespace.

Currently for other services like Elastic Search or MySQL with their official operators, I can do that, start a cluster in the selected namespace, while the operator runs in it's namespace.

I don't have to `deploy Role, RoleBinding and ServiceAccount in that namespace` separate for each cluster/namespace with the other operators.

Would such a change to minimize deployments manifests be complex to support?

**Comment by madalinignisca** [comment]
NVM, just spoted in the docs WATCH_NAMESPACE="*" and it's all set for my case :)

**Comment by edwardzjl** [comment]
Same issue here, but I did not apply the whole `config/rbac` dir, instead just the service account file `config/rbac/service_account.yaml`, and it seems to be working now.

I think this section of the document is a bit misleading and need a bit modification:

> For each namespace that you want the Operator to watch, run the following commands to deploy a Role, RoleBinding and ServiceAccount in that namespace:
>
> ```bash
> kubectl apply -k config/rbac --namespace <my-namespace>
> ```

It is not only **the namespaces that you want the Operator to watch**, but also **the namespace that the operator will be installed into**, at least for the ServiceAccount.

**Comment by tamer-hassan** [comment]
Documentation is now very detailed and covers all three different scopes (single namespace, multi-namespace, and cluster-wide), covering both the use of kubectl and helm
https://www.mongodb.com/docs/kubernetes-operator/master/tutorial/set-scope-k8s-operator/#ns-scope-different-ns
