### ISSUE TITLE
Version 0.7.6 not support ARM64?

### ISSUE THREAD

**Issue by noahge** [mongodb/mongodb-kubernetes-operator#1117]
**What did you do to encounter the bug?**

**What did you expect?**

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by mohsinonxrm** [comment]
@noahge , may want to review https://github.com/mongodb/mongodb-kubernetes-operator/issues/299

Specifically:
https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1304623123
