### ISSUE TITLE
deployment/auth-mongo-depl: container auth-mongo is waiting to start: mongo can't be pulled

### ISSUE THREAD

**Issue by Zohalmohal** [mongodb/mongodb-kubernetes-operator#1144]
This is my `auth-depl.yaml` file:

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: auth-depl
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: auth
      template:
        metadata:
          labels:
            app: auth
        spec:
          containers:
            - name: auth
              image: tester/auth
              env:
                - name: MONGO_URI
                  value: 'mongodb://auth-mongo-srv:27017/auth'
                - name: JWT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: jwt-secret
                      key: JWT_KEY
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: auth-srv
    spec:
      selector:
        app: auth
      ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000

And the following is `auth-mongo-depl.yaml`:

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: auth-mongo-depl
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: auth-mongo
      template:
        metadata:
          labels:
            app: auth-mongo
        spec:
          containers:
            - name: auth-mongo
              image: mongo
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: auth-mongo-srv
    spec:
      selector:
        app: auth-mongo
      ports:
        - name: db
          protocol: TCP
          port: 27017
          targetPort: 27017

When I run `skaffold dev` it gives me the following error:

     - deployment/auth-mongo-depl: container auth-mongo is waiting to start: mongo can't be pulled
        - pod/auth-mongo-depl-64f5f58669-dw4hg: container auth-mongo is waiting to start: mongo can't be pulled
     - deployment/auth-mongo-depl failed. Error: container auth-mongo is waiting to start: mongo can't be pulled.

The `mongo` service is up and running and I can run `mongo` command on the terminal. It also starts and runs on it's default `mongodb://127.0.0.1:27017` address. I use Windows 10 and Docker-Desktop.

Let me know if more information needs to be added.

**Comment by Seunope** [comment]
Facing the same issue...

**Comment by mircea-cosbuc** [comment]
Hi @Zohalmohal , 
Based on your example it doesn't seem like you are using the kubernetes operator for deploying mongodb. If you'd like to try it, please follow the documentation: https://github.com/mongodb/mongodb-kubernetes-operator/tree/master/docs.
I will close this issue.  You're welcome to open any new issue you might encounter while using the MongoDB community operator.
