### ISSUE TITLE
Tolerance for MongoDb Pods

### ISSUE THREAD

**Issue by hemantkathuria** [mongodb/mongodb-kubernetes-operator#121]
Hello, 

1 - Currently we have Taints for a node pool in our AKS cluster and we want to have the MongoDB community database deployed to that specific node pool. How do we specify the [tolerance](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)?

2 - Also do you plan to support Standalone deployment of MongoDB?

**Comment by theburi** [comment]
We started with ReplicaSet first. and Sharded Clusters and Standalone will follow.

We also found that running single Node Replicaset is pretty much an alternative to a Standalone, however without potential problems in future migration to ReplicaSet like connection string or upgrade.

**Comment by theburi** [comment]
Regarding Tolerations: We don't expose STS Pod Templates yet where Tolerations get configured. This is something that we will be adding going forward.

**Comment by hemantkathuria** [comment]
> Regarding Tolerations: We don't expose STS Pod Templates yet where Tolerations get configured. This is something that we will be adding going forward.

In that case what do you suggest on how to deploy the pods on the Nodes / Node Pools having Taints defined? Any workaround possible? Also, are you expecting this feature in recent future like few weeks similar to SCRAM support?

**Comment by chatton** [comment]
Hi @hemantkathuria 

Arbitrary configuration support should also be coming shortly like SCRAM. 

As a temporary work around, you could apply a change to the underlying StatefulSet created by the operator. The operator will not overwrite any changes made, only apply them on top of the existing StatefulSet.

You could try the following

* Create the MongoDB resource
* Wait for StatefulSet to be created (it won't get into running state without tolerations as you know).
* Save the configuration of the StatefulSet resource.
* Update the configuration with the tolerations you need.
* Apply the configuration.

But support for this through the MongoDB resource is coming shortly!

**Comment by hemantkathuria** [comment]
Hello Friends!

Are we close to the release of this feature? We are really looking forward for the same?

Thank you

**Comment by chatton** [comment]
Hi @hemantkathuria 

Arbitrary StatefulSet configuration was implemented in the latest release v0.1.1, you can look at [this example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml) as a starting point. We will be adding more shortly.
