### ISSUE TITLE
Autogenerated connection string secret does not work for backups

### ISSUE THREAD

**Issue by stocksr** [mongodb/mongodb-kubernetes-operator#1225]
**What did you do to encounter the bug?**
I am attempting to use the connection string provided to run mongodump commands and running into issues.

**What did you expect?**
That it would be possible to create a user that can run backups

**What happened instead?**
The generated connection string includes \admin so is unusable as a URI parameter for a backup
I am getting the error 
Invalid Options: Cannot specify different database in connection URI and command-line option ("admin" was specified in the URI and "app-database" was specified in the --db option
This is a snip from my attempt at a backup cron job
```            - name: backup-runner
              image: docker.io/mongo:5.0.9
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - "-c"
                - "exec mongodump -vvvvv --uri=${MONGO_SERVER_URL} --gzip --archive=/db_backups/$(date +%Y%m%d).backup.gz --db=$DB"
              volumeMounts:
                - mountPath: /db_backups/
                  name: backups
              env:
                - name: DB
                  value: app-database
                - name: MONGO_SERVER_URL
                  valueFrom:
                    secretKeyRef:
                      key: connectionString.standardSrv
                      name: mongodb-admin-backup-agent
                      optional: false
```

**Operator Information**
 - Operator Version:0.7.8
 - mongo:5.0.9

** Suggestion **
Please could you add all the parts of the connection string as individual fields to the secret so that I can construct a connection string and use each bit as needed at a minimum I would like the authDb, the replicaSetName, the ssl flag and the hostname for the +srv version of the connection string, it would probably also make sense to include the host list.

At the moment I am looking to write shell scripts to parse the connection string into its components

**Comment by olekristensen** [comment]
this issue is related to #1134

**Comment by olekristensen** [comment]
Still relevant!
