### ISSUE TITLE
automation-agent-verbose.log: No space left on device

### ISSUE THREAD

**Issue by tomislater** [mongodb/mongodb-kubernetes-operator#1226]
**What did you do to encounter the bug?**
Just install mongo (3 replicas) with 4Gi disks for logs.

**What did you expect?**
I did not except to see such message.

**What happened instead?**
A lot of such messages in `mongodb-agent` container:
```
Logging error occurred: rolling_file_appender: Failed to write to /var/log/mongodb-mms-automation/automation-agent-verbose.log: write /var/log/mongodb-mms-automation/automation-agent-verbose.log: no space left on device
```

**Screenshots**
<img width="724" alt="Screenshot 2023-02-10 at 15 22 56" src="https://user-images.githubusercontent.com/1127164/218115124-fdbd2e72-494c-46b4-b416-0e2ed8217e19.png">

**Operator Information**
 - Operator Version (`0.7.8`)
 - MongoDB Image used
   - `docker.io/mongo:5.0.13`
   - `quay.io/mongodb/mongodb-agent:12.0.15.7646-1`

**Kubernetes Cluster Information**
 - Distribution (`AWS EKS`)
 - Version (`1.24`)
 - Image Registry location (`quay`)

**Additional context**
I observed that the `agent` write logs to `/var/log/mongodb-mms-automation` folder which is strange in cloud native applications? Should not we put everything as a container output? Do we really need to create disks for logs?

I did not found any way to configure agent for disabling `DEBUG`. I can overwrite the command, but... I don't think it is a good idea? Any thoughts? Thanks!

**Comment by tomislater** [comment]
I changed a command to (copied from a code):

```
- name: mongodb-agent
  command:
    - /bin/bash
    - '-c'
    - >-
      current_uid=$(id -u)

      AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"

      declare -r current_uid

      if ! grep -q "${current_uid}" /etc/passwd ; then

      sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd

      echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd

      export NSS_WRAPPER_PASSWD=/tmp/passwd

      export LD_PRELOAD=libnss_wrapper.so

      export NSS_WRAPPER_GROUP=/etc/group

      fi

      agent/mongodb-agent
      -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      -serveStatusPort=5000
      -cluster=/var/lib/automation/config/cluster-config.json
      -skipMongoStart -noDaemonize -useLocalMongoDbTools -logFile
      /var/log/mongodb-mms-automation/automation-agent.log
      -maxLogFileDurationHrs 1 -logLevel INFO -maxLogFiles 8
```
And change the last line.

It started working; as an ad-hoc solution is fine, but I would not like to do this thing on production cluster.

**Comment by kjelljoakim** [comment]
We are seeing the same issue. It appeared after upgrading to operator 0.7.8 with [this](https://github.com/mongodb/mongodb-kubernetes-operator/pull/1200/files) change. I deleted all debug logs in `/var/log/mongodb-mms-automation` but the volume gets filled up again within 24 hours (with a 2Gi volume) and now we are seeing about 5k lines per minute of

```
Logging error occurred: rolling_file_appender: Failed to write to /var/log/mongodb-mms-automation/automation-agent-verbose.log: write /var/log/mongodb-mms-automation/automation-agent-verbose.log: no space left on device
```
![image](https://user-images.githubusercontent.com/5394208/218427477-38080718-3876-4c79-a000-87050d62a7ff.png)

Is there a reason for `DEBUG` being the default log level here? Would it not be better to have debug logs as optional?

**Operator Information**

- Operator Version (0.7.8)
- MongoDB Image used
  - quay.io/mongodb/mongodb-agent:12.0.15.7646-1

**Kubernetes Cluster Information**

Distribution (Google GKE)
Version (1.22)
Image Registry location (quay)

**Comment by fujin** [comment]
Seeing the same thing here, used the fix from the comment above https://github.com/mongodb/mongodb-kubernetes-operator/issues/1226#issuecomment-1427668570 👍🏽

**Comment by Batuzz** [comment]
I've got exactly the same issue in my environment, thanks @tomislater for bringing up this issue with more details.

**Comment by rdxmb** [comment]
I am having the same issue when upgrading the operator from 0.7.6 to 0.7.8 

I have not expected to have such an issue/error with full log devices in the mongodb-instances - just from upgrading the operator. I did not upgrade the mongodb-objects, only the operator. Confused.

**Comment by siegenthalerroger** [comment]
The log level and more importantly the logFile duration definitely needs to be configurable. This is an insane amount of data being produced just for a log...

**Comment by rdxmb** [comment]
Yes and it would be best to write the logs to stdout instead of having a pvc for it

**Comment by KiqoCode** [comment]
Can someone explain how and where I can apply this temporary fix from @tomislater ?

Having the same issue.. 

> I changed a command to (copied from a code):
> 
> ```
> - name: mongodb-agent
>   command:
>     - /bin/bash
>     - '-c'
>     - >-
>       current_uid=$(id -u)
> 
>       AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"
> 
>       declare -r current_uid
> 
>       if ! grep -q "${current_uid}" /etc/passwd ; then
> 
>       sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
> 
>       echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
> 
>       export NSS_WRAPPER_PASSWD=/tmp/passwd
> 
>       export LD_PRELOAD=libnss_wrapper.so
> 
>       export NSS_WRAPPER_GROUP=/etc/group
> 
>       fi
> 
>       agent/mongodb-agent
>       -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
>       -serveStatusPort=5000
>       -cluster=/var/lib/automation/config/cluster-config.json
>       -skipMongoStart -noDaemonize -useLocalMongoDbTools -logFile
>       /var/log/mongodb-mms-automation/automation-agent.log
>       -maxLogFileDurationHrs 1 -logLevel INFO -maxLogFiles 8
> ```
> 
> And change the last line.
> 
> It started working; as an ad-hoc solution is fine, but I would not like to do this thing on production cluster.

**Comment by tomislater** [comment]
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_readiness_probe_values.yaml here you have an example. You just need to change a command for this container.

**Comment by rdxmb** [comment]
Just wondering what this line means

"Automatic rotation of your MongoDB Agent logs only occurs when an update to the log file is made."

https://www.mongodb.com/docs/ops-manager/current/reference/mongodb-agent-settings/#logging-settings

Is the logrotate working in your case, @KiqoCode ?

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan

**Comment by aleksanderlech** [comment]
Hello,

Why is this issue closed? I am facing exactly the same problem. I don't understand why by default mongodb-agent using DEBUG is its default logging level. Can we at least make it configurable so we don't have to override the whole commandline for this?

**Comment by laiminhtrung1997** [comment]
#1489 

This issue has been fixed. Please check the [comment](https://github.com/mongodb/mongodb-kubernetes-operator/issues/1439#issuecomment-1937357000).

**Comment by chadlangston** [comment]
is this still an issue? I have been running the mongodb operator without issue until just recently the mongodb-agent started logging trace and debug logs and going off the rails. i modified the command to hard code the log level, but that didn't work either. the only solution i have found is to redirect stdout and stderr to /dev/null

`              command:
                - /bin/bash
                - -c
                - |-
                  current_uid=$(id -u)
                  AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"
                  declare -r current_uid
                  if ! grep -q "${current_uid}" /etc/passwd ; then
                  sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
                  echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
                  export NSS_WRAPPER_PASSWD=/tmp/passwd
                  export LD_PRELOAD=libnss_wrapper.so
                  export NSS_WRAPPER_GROUP=/etc/group
                  fi
                  agent/mongodb-agent -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -cluster=/var/lib/automation/config/cluster-config.json -skipMongoStart -noDaemonize -useLocalMongoDbTools -logFile ${AGENT_LOG_FILE} -maxLogFileDurationHrs ${AGENT_MAX_LOG_FILE_DURATION_HOURS} -logLevel ${AGENT_LOG_LEVEL} &> /dev/null`

**Comment by chadlangston** [comment]
is this still an issue? I have been running the mongodb operator without issue until just recently the mongodb-agent started logging trace and debug logs and going off the rails. i modified the command to hard code the log level, but that didn't work either. the only solution i have found is to redirect stdout and stderr to /dev/null

```
command:
  - /bin/bash
  - -c
  - |-
    current_uid=$(id -u)
    AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"
    declare -r current_uid
    if ! grep -q "${current_uid}" /etc/passwd ; then
    sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
    echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
    export NSS_WRAPPER_PASSWD=/tmp/passwd
    export LD_PRELOAD=libnss_wrapper.so
    export NSS_WRAPPER_GROUP=/etc/group
    fi
    agent/mongodb-agent -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -cluster=/var/lib/automation/config/cluster-config.json -skipMongoStart -noDaemonize -useLocalMongoDbTools -logFile ${AGENT_LOG_FILE} -maxLogFileDurationHrs ${AGENT_MAX_LOG_FILE_DURATION_HOURS} -logLevel ${AGENT_LOG_LEVEL} &> /dev/null
```

i tried setting the `AGENT_LOG_LEVEL` to FATAL via env variable and directly in the command, but no luck..
