### ISSUE TITLE
Use a different storage class

### ISSUE THREAD

**Issue by kaykhancheckpoint** [mongodb/mongodb-kubernetes-operator#126]
Hi,

How do i alter the storage class so that it does not use the default one but uses another one. Im basically trying to get persistent volumes so they are created with aws ebs

**Comment by kylos101** [comment]
Hi @kaykhancheckpoint you may want to look at #61. Work is underway in #118.

**Comment by hemantkathuria** [comment]
Hello Friends!

Are we close to the release of this feature? We are really looking forward for the same?

Thank you

**Comment by chatton** [comment]
Hi @hemantkathuria  This feature is almost complete and should be out the next release (this week or next!)

**Comment by borenstein** [comment]
I see that PR #118 has been merged into master, and that this allows "arbitrary StatefulSet configuration." I don't see any examples of how this is done. Is it a set of parameters to be supplied in the `spec` section of my `MongoDB` resource manifest? If so, could you please supply an example?

**Comment by chatton** [comment]
Hi Guys, sorry for the delay, arbitrary StatefulSet configuration is now possible with the latest release of the operator v0.1.1.

You can use the [this CR](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml) as a starting point.

We will add more detailed examples shortly.
