### ISSUE TITLE
mongodb-agent container logs to filesystem

### ISSUE THREAD

**Issue by ccodreanu** [mongodb/mongodb-kubernetes-operator#1261]
**What did you do to encounter the bug?**
deploy a mongodbcommunity resource with the latest version of the operator and set LOG_FILE_PATH env to /dev/stdout

**What did you expect?**
mongodb-agent container to log to stdout

**What happened instead?**
mongodb-agent container does not log to stdout anymore since this was merged: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1200/files

**Operator Information**
 - Operator Version: 0.7.9
 - MongoDB Image used: docker.io/mongo:6.0.4, quay.io/mongodb/mongodb-agent:12.0.10.7591-1

**Kubernetes Cluster Information**
 - Distribution EKS
 - Version 1.23

**Comment by irajdeep** [comment]
With the `0.7.9` operator release. You can configure [agent log rotation](https://www.mongodb.com/docs/ops-manager/current/reference/mongodb-agent-settings/) by specifying `maxLogFileDurationHrs` under the MongoDB CR. The changes were added in this PR: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1238. 

Additionally, we can configure it(via the CR) if the agent should log to a file on disk or stdout.

**Comment by ChrisJBurns** [comment]
@irajdeep Will give it a try.

I always have a bit of a nightmare trying to find the specs of a CRD, would you have them as a link? I'm having to dig into the code to figure out what the configuration options are in the CR.

**Comment by irajdeep** [comment]
Yeah, logging to stdout is not present in [AgentConfiguration](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/api/v1/mongodbcommunity_types.go#L285). To avoid the problem of logs filling up you can set `maxLogFileDurationHrs` so that logs get rotated. A better option would be to prepare a patch to make the log destination configurable : -)

**Comment by ChrisJBurns** [comment]
Ahh I thought "Additionally, we can configure it(via the CR) if the agent should log to a file on disk or stdout." meant that it was currently possible. No problems, will set the `maxLogFileDurationHrs` to 24 hours :)

**Comment by ChrisJBurns** [comment]
@irajdeep  Do you know if the agent config is available? I'm getting an error saying it is not present in the schema?

**Comment by ChrisJBurns** [comment]
I believe so, let me check and get back to you

**Comment by deepak7340** [comment]
Hi Can some one please help me the syntax for using the agent loglevel. 
Here I'm using graylog  with Mongodb https://github.com/KongZ/charts and I'.trying to add the values in templetes/mongodb.yaml file 

```
  agent:
    logLevel: INFO
    maxLogFileDurationHrs: 6
```
But this seems to be not working 
Thanks for the support

**Comment by laurivosandi** [comment]
I find logging into files an antipattern in the Kubernetes world, the container runtime will anyway log the stdout to files and you have other tools to aggregate logs from Kubernetes nodes.

I don't understand why logging to stdout is _not_ default?

**Comment by rdxmb** [comment]
Sorry, seems like this project is not production ready. Moving to percona mongodb operator instead.

**Comment by nammn** [comment]
While late - this has been fixed: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1489
