### ISSUE TITLE
Mongodb Replicaset connection string unable to connect every time primary

### ISSUE THREAD

**Issue by thennetivamsi** [mongodb/mongodb-kubernetes-operator#1280]
**What did you do to encounter the bug?**
how to connect outside the cluster every time primary node. i deployed replicaset cluster and i get cluster IP by using this IP then i connect every time primary node in side node but outside its shows error so how to fix it.
![ALT](https://github.com/thennetivamsi/Rabbitmq_k8s_Operator/blob/main/errorconnection.png?raw=true)
**replicaset connection string issue**
we deployed mongodb replicaset 3 node cluster and we create gateway and connected replicaset service using IP:Port connected but its not connect every time primary node so inside the node 1,2,3 we are mansion replicaSet=name then its able to connect every time primary but outside the node not able to connect primary and also we mansion replicaSet=name but it's show error so please guide me how to achieve outside the cluster i need to connect every time primary.
inside node connect every time primary as expected.
 ![ALT](https://raw.githubusercontent.com/thennetivamsi/Rabbitmq_k8s_Operator/main/podconnection.png)  
**What did you expect?**
how to connect outside the cluster every time primary node.

**What happened instead?**
inside the node we able to connect every time primary but outside cluster not connect every time primary.

**Operator Information**
 - Operator Version 1.18
 - MongoDB Image used 5.0.15

**Kubernetes Cluster Information**
 - Distribution
 - Version 5.0.15
 - Image Registry location (quay, or an internal registry)

**Comment by thennetivamsi** [comment]
Yes I'm still facing the same issue.

**Comment by domenicbove** [comment]
Ya this seems to be a large issue for me as well. I've just been arbitrarily choosing a pod and hoping its not secondary when connecting to the cluster. Any hints?

**Comment by thennetivamsi** [comment]
Yes I'm still facing the same issue.
