### ISSUE TITLE
Storage class for kuberenetes community 

### ISSUE THREAD

**Issue by victory4software** [mongodb/mongodb-kubernetes-operator#1315]
**What did you do to encounter the bug?**
I want to attach a specific storage class name to the MongoDB community cluster so if for any reason the environment is corrupted I can start again the same cluster for SC not creating a new PV
**What did you expect?**
If I deleted the cluster and creating again the MongoDB cluster with the same storage class it should run with all the data that was existing before

**What happened instead?**
There is no place to set the Storage class name so every time you delete the MongoDB cluster and create a new cluster a new database is created.

**Comment by 93imagine** [comment]
This is how I set a storageClassName. 

```   statefulSet:
    spec:
      serviceName: svc
      volumeClaimTemplates:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10G
          storageClassName: storageClass ```

**Comment by irajdeep** [comment]
@victory4software feel free to re-open if the mechanism suggested by @93imagine doesn't work.
