### ISSUE TITLE
FluxCD show warning logs in kustomize controller 

### ISSUE THREAD

**Issue by zxp86021** [mongodb/mongodb-kubernetes-operator#1355]
**What did you do to encounter the bug?**
1. Install fluxcd gitops toolkit (kustomize controller >= v1.0.1)
2. Deploy operator using config/default/kustomization.yaml via fluxcd
3. kustomize controller show warning log

**What did you expect?**
No warning log

**What happened instead?**
Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

**Operator Information**
 - Operator Version: v0.8.0

**Kubernetes Cluster Information**
 - Distribution: AWS EKS
 - Version: 1.25
 - Image Registry location: quay.io

**Comment by maxgio92** [comment]
Hey @zxp86021, I've just proposed a PR, which is linked to this issue. Thank your for reporting this!
