### ISSUE TITLE
Pods crashed and can't start back with replicas number from 3 to 1

### ISSUE THREAD

**Issue by scorsi** [mongodb/mongodb-kubernetes-operator#136]
Hello, 

I got a weird issue where my mongo db can't start. The pods were running before (and crashed?) and while trying to restart, the `mongodb-agent` container is marked as failing starting.

If I delete everything (claimed volumes and the mongodb resource) everything will start and run correctly, but after some time, the pods did stop and can't restart.

_Note: I had a 3 replicas and scale down to 1 for budget reason, can it be the cause?_

The resource:
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: order-db
  namespace: mongodb
spec:
  members: 1 # was 3
  type: ReplicaSet
  version: 4.2.8
```

The `mongodb-agent` logs are (_cut_):
```
[2020-08-11T08:49:01.281-00] [.info] [main/components/agent.go:LoadClusterConfig:219] [08:49:01.281] clusterConfig unchanged

[2020-08-11T08:49:02.235-00] [.info] [cm/mongoctl/processctl.go:Update:3298] <order-db-0> [08:49:02.235] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 3}]}] and upsert=true on local.clustermanager

[2020-08-11T08:49:02.271-00] [.info] [cm/director/director.go:computePlan:279] <order-db-0> [08:49:02.271] ... process has a plan : WaitPrimary,RsReconfig

<order-db-0> [08:49:02.270] ... process has a plan : WaitPrimary,RsReconfig

<order-db-0> [08:49:02.272] Running step 'WaitPrimary' as part of move 'WaitPrimary'

[2020-08-11T08:49:02.272-00] [.info] [cm/director/director.go:executePlan:867] <order-db-0> [08:49:02.272] Running step 'WaitPrimary' as part of move 'WaitPrimary'

[2020-08-11T08:49:02.272-00] [.info] [cm/director/director.go:tracef:772] <order-db-0> [08:49:02.272] Precondition of 'WaitPrimary' applies because
[All the following are true:
    ['currentState.NeedToStepDownCurrentPrimary' = false]
    ['currentState.Up' = true]
]

[2020-08-11T08:49:02.274-00] [.info] [cm/director/director.go:planAndExecute:563] <order-db-0> [08:49:02.274] Step=WaitPrimary as part of Move=WaitPrimary in plan failed : <order-db-0> [08:49:02.274] Postcondition not yet met for step WaitPrimary because ['currentState.IsPrimary' = false].
```

The `mongod` container logs are (_cut_):
```
2020-08-11T08:55:11.164+0000 I  CONNPOOL [Replication] Connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017

2020-08-11T08:55:12.225+0000 I  CONNPOOL [Replication] Connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017

2020-08-11T08:55:12.239+0000 I  REPL_HB  [replexec-0] Heartbeat to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017 failed after 2 retries, response status: HostUnreachable: Error connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017 :: caused by :: Could not find address for order-db-1.order-db-svc.mongodb.svc.cluster.local:27017: SocketException: Host not found (authoritative)
```

Do you have any idea ? 

Thanks,

**Comment by chatton** [comment]
Hi @scorsi  thanks for the report,

Do you mean you created a regular 3 member replica set, then scaled down to 1 and it broken this way?

What sort of kubernetes environment are you using?

I will try to reproduce this and get back to you.

**Comment by scorsi** [comment]
I had a 3 members replicaset and scaled down to 1, yes. It's after some days that the pods were deleted or crashed (I don't very know what happen) and can't start back. It looks like the `order-db-0` tried to communicate with `order-db-1` (I imagine to recover data ?) and can't since it don't exists. It's like the pods registered themself but don't unregistered in case of scale-down.

I'm running on AWS EKS with version 1.17.

**Comment by chatton** [comment]
@scorsi it looks like there is an issue with scaling down in some situations, I was able to repro this, thanks for creating this issue! We will start working on a fix straight away 👍

**Comment by rtudo** [comment]
@chatton  Facing similar issue on 0.7.2 . Had scaled down from 3 to 1 and now not able to recover as there is no primary node available. The first pod is a secondary node and can't even reconfig in this case. Any idea on how can I atleast recover the cluster? (maybe I will update readiness probe and allow other pods to come up ) 
The mongodb-agent is in unready state

> `[2022-02-17T13:29:29.556+0000] [.info] [src/director/director.go:planAndExecute:564] <graylog-mongodb-0> [13:29:29.556] Step=WaitPrimary as part of Move=WaitPrimary in plan failed : <graylog-mongodb-0> [13:29:29.556] Postcondition not yet met for step WaitPrimary because
> ['currentState.IsPrimary' = false].
>  Recomputing a plan...
> [2022-02-17T13:29:29.696+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:29:29.696] clusterConfig unchanged
> [2022-02-17T13:29:30.650+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1573] [13:29:30.650] Testing auth with username __system db=local to graylog-mongodb-0.graylog-mongodb-svc.mongodb.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false
> [2022-02-17T13:29:30.738+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:1985] <graylog-mongodb-0> [13:29:30.738] Able to successfully auth to graylog-mongodb-0.graylog-mongodb-svc.mongodb.svc.cluster.local:27017 (local=false) using desired auth key
> [2022-02-17T13:29:30.748+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:29:30.748] clusterConfig unchanged
> [2022-02-17T13:29:30.830+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <graylog-mongodb-0> [13:29:30.830] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 22}]}] and upsert=true on local.clustermanager
> [2022-02-17T13:29:31.057+0000] [.info] [src/director/director.go:computePlan:280] <graylog-mongodb-0> [13:29:31.057] ... process has a plan : WaitPrimary,RsReconfig
> [2022-02-17T13:29:31.058+0000] [.info] [src/director/director.go:tracef:794] <graylog-mongodb-0> [13:29:31.058] Running step: 'WaitPrimary' of move 'WaitPrimary'
> [2022-02-17T13:29:31.058+0000] [.info] [src/director/director.go:tracef:794] <graylog-mongodb-0> [13:29:31.058] because
> [All the following are true:
>     ['currentState.NeedToStepDownCurrentPrimary' = false]
>     ['currentState.Up' = true]
> ]
> [2022-02-17T13:29:31.059+0000] [.info] [src/director/director.go:planAndExecute:564] <graylog-mongodb-0> [13:29:31.059] Step=WaitPrimary as part of Move=WaitPrimary in plan failed : <graylog-mongodb-0> [13:29:31.059] Postcondition not yet met for step WaitPrimary because
> ['currentState.IsPrimary' = false].
>  Recomputing a plan...`

**Comment by ammurdoch** [comment]
@rtudo Were you able to find a solution?  I'm not in the same situation.

**Comment by rtudo** [comment]
Hi @ammurdoch , it's been more than an year so I don't remember exactly how but we did recover the cluster. Try updating readiness probe as mentioned in my earlier comment maybe and then see if you can bring up other pods and allow Mongo cluster to be healthy

**Comment by slaskawi** [comment]
At first, using a single-member ReplicaSet can cause service interruptions. If from whatever reason that single replica crashes, the application that depends on it will be in troubles.

As for the solution, if you ran into this situation, you can turn the Operator off (by scaling it to 0), edit the StatefulSet and manually remove the Readiness Probe. This should force it to scale down bypassing all the security measures we have in place. Then edit the CR and set the number of members to 1. Finally, turn the Operator on.
