### ISSUE TITLE
TLS is using the wrong file name

### ISSUE THREAD

**Issue by phmcder** [mongodb/mongodb-kubernetes-operator#1374]
I am deploying a database instance using the MongoDBCommunity operator with TLS enabled. I see that the secret "hyperion-mongodb-server-certificate-key" is created and the secret contains the following key:
`66945b13310adfbf0d44ca7aa26fe5d4cdea61a1070b1d65a9c905229cb56596.pem`

After a short time the pod crashes. When I look at the logs I see the error
`"Cannot read certificate file","attr":{"keyFile":"/var/lib/tls/server/053cb3fa611689df16de1e718af119e3fed872047edf7649c0229a5b0d7ece15.pem","error":"error:FFFFFFFF80000002:system library::No such file or directory"}}
Error during global initialization","attr":{"error":{"code":140,"codeName":"InvalidSSLConfiguration","errmsg":"Can not set up PEM key file."`

**Operator Information**
 - Operator Version : 0.8.2
 - MongoDB Image used: 6.0.5

**Kubernetes Cluster Information**
 - Distribution: EKS platform eks.4
 - Version: 1.27
 - Image Registry location: quay

Any ideas why this happens?

**Comment by irajdeep** [comment]
Could you share the MongoDB resource yaml you're using?

**Comment by phmcder** [comment]
Seems to have fixed itself. Might have been stale resources

**Comment by iamhritik** [comment]
facing the same issue and resolved it by scaling down the sts and deleting the old pvc
