### ISSUE TITLE
Nonsecure prometheus

### ISSUE THREAD

**Issue by domenicbove** [mongodb/mongodb-kubernetes-operator#1405]
This might be more of a feature request. But I am looking for a way to configure prometheus thru the MongoDBCommunity CR without having to input a user/password.

**What did you do to encounter the bug?**
1. Edit MongoDBCommunity CR, and set prometheus section to
```
  prometheus:
    port: 9216
```

2. Receives error
```
# mongodbcommunity.mongodbcommunity.mongodb.com "mongodb" was not valid:
# * spec.prometheus.passwordSecretRef: Required value
# * spec.prometheus.username: Required value
```

**What did you expect?**
I am hoping for a way to get prometheus enabled without providing a user/password. As far as I can tell, when I remove the prometheus section entirely, there is no enablement in the `mongodb-config` secret.
The only way to get it configured in there is with a user/pass

**Operator Information**
 - Operator Version - mongodb-kubernetes-operator:0.8.2
 - MongoDB Image used - 7.0.2

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by irajdeep** [comment]
I am closing this as "won't fix" since we don't plan to implement a feature disabling basic auth in the near future.
