### ISSUE TITLE
In the quay.io repository, there is no image of the arm architecture.

### ISSUE THREAD

**Issue by maskshell** [mongodb/mongodb-kubernetes-operator#1408]
In the quay.io repository, there is no image of the arm architecture.

**Comment by Julien-Ben** [comment]
Hello,

We actually released our first ARM images a few days ago
The one for 0.8.3 is the following :
quay.io/mongodb/mongodb-kubernetes-operator:0.8.3-arm64

**Comment by vinnytwice** [comment]
@Julien-Ben Hi, I did try to use the 0.8.3 on my M1 running a K3D cluster but I guess that the Helm chart is not updated yet ( see https://github.com/mongodb/mongodb-kubernetes-operator/issues/1420).
Is the 0.8.3 helm chart already updated to use quay.io/mongodb/mongodb-kubernetes-operator:0.8.3-arm64 or how should be set to use it?
Thank you very much.
Cheers.

**Comment by vinnytwice** [comment]
Hi every one, today I was finally able to install mongo v. 6.0.11 in a k3d Kubernetes cluster on my MacBook with M1 chip ( https://github.com/mongodb/mongodb-kubernetes-operator/issues/1420). 
Mongo is installed via the operator , which on arm machines still does have a problem as the mongo-agent it installs doesn't have an arm64 image yet. I used these  images https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1666717878 to override chart's values and installed the 6.0.11 version without problems. So let's hope that the agent arm64 image gets uploaded to quay.io soon so to use the official operator.
Cheers

**Comment by nello1992** [comment]
Hi @maskshell , if you still need a clean solution you can refer to this issue #1426 
The image for arm64 is available on quay and you just need to specify --set image.tag=0.8.3-arm64 when installing the operator with helm:
`helm install --set image.tag=0.8.3-arm64 community-operator mongodb-helm-charts/community-operator`

I just tried on an arm64 machine and it works correctly in k8s. 
Hope this helps

**Comment by Julien-Ben** [comment]
Hi @maskshell 
You can now find ARM images for the operator on our [quay registry](https://quay.io/repository/mongodb/mongodb-kubernetes-operator?tab=tags)
They are built for both architectures starting with version 0.8.3

You can simply pull the non-prefixed tag and docker will automatically download the image for the right architecture for your machine.
E.g  `docker pull quay.io/mongodb/mongodb-kubernetes-operator:0.8.3`

**Comment by maskshell** [comment]
Very sad, imagebase `mongodb/mongodb-agent-ubi` has an image for arm architecture, but `mongodb/mongodb-agent` does not.

**Comment by maskshell** [comment]
got it.

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              image: "quay.io/mongodb/mongodb-agent-ubi:12.0.25.7724-1"
```
