### ISSUE TITLE
No Docker image for quay.io/mongodb/mongodb-kubernetes-operator:0.1.1

### ISSUE THREAD

**Issue by uberkelium** [mongodb/mongodb-kubernetes-operator#144]
It looks like version 0.1.1 for mongodb-kubernetes-operator was deleted from quay.io, so the latest release from this repo fails when trying to pull the image. I'm not sure if this is intentional.

https://quay.io/repository/mongodb/mongodb-kubernetes-operator?tab=history

![image](https://user-images.githubusercontent.com/22272118/90628126-edaa5900-e1d1-11ea-89b2-dde975e84250.png)

```
root@secondary-1:~# docker pull quay.io/mongodb/mongodb-kubernetes-operator:0.1.1
Error response from daemon: unknown: Tag 0.1.1 was deleted or has expired. To pull, revive via time machine
```

**Comment by chatton** [comment]
Hi @uberkelium  thanks for bringing this up, will take care of this ASAP

**Comment by chatton** [comment]
@uberkelium everything should be there now, closing this issue, feel free to re-open if it isn't resolved
