### ISSUE TITLE
Allow service spec to be updated from MongoDBCommunity CR

### ISSUE THREAD

**Issue by alita1991** [mongodb/mongodb-kubernetes-operator#1521]
**What did you do to encounter the bug?**
1. Install MongoDB operator
2. Create a MongoDB Community CR with the service spec changed.

**What did you expect?**
Service spec should be updated with additional ports + annotations

**What happened instead?**
Service spec is not exposed, similar to the Statefulset spec.

**Operator Information**
 - Operator Version: 0.9.0
 - MongoDB Image used: 5.0.25

**Kubernetes Cluster Information**
 - Distribution: K3S
 - Version: 1.26
 - Image Registry location (quay, or an internal registry): quay

**Additional context**
I aim to include extra sidecar containers, such as a metrics sidecar, allowing me to deploy an external metrics exporter alongside that would be scraped via service. I intend to configure annotations on the service for Prometheus automatic discovery, enabling the scraping of metrics and exposing the exporter container at the service level, similar to the one exposed when prometheus integration is enabled.

Updating the service spec is not currently possible, and as result, a lot of manual steps are required, like creating a custom service for each cluster, which points to the sidecar container with the required annotations in place.

**Comment by nammn** [comment]
@alita1991 is there a reason you cannot use servicemonitors?

**Comment by nammn** [comment]
Related: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1518

**Comment by kferrone** [comment]
I need this too. It's standard practice to escape hatch the resources created by an operator. Currently I need to add NLB annotations for AWS LB controller but I can't.
