### ISSUE TITLE
[Release v0.2.0] Mongodb pods are not created by following the installation steps.

### ISSUE THREAD

**Issue by naddame** [mongodb/mongodb-kubernetes-operator#153]
I just tried the release v0.2.0 which include `users:` in the file `deploy/crds/mongodb.com_v1_mongodb_cr.yaml` and it does not works. Got warn: WARN mongodb/replica_set_controller.go:174 error creating automation config config map: Secret "digital-factory-mongodb-mdfdb-admin-scram-credentials" not found

No pod created because, I suppose, of this warning.  And when I remove the `users:` block from the file `deploy/crds/mongodb.com_v1_mongodb_cr.yaml` it works and pods got created.

**Environment**
GKE

**Scenario**
- I have followed the install steps: https://github.com/mongodb/mongodb-kubernetes-operator#install-the-operator
- I have changed the name of deploy in the file `deploy/crds/mongodb.com_v1_mongodb_cr.yaml` from example-mongodb to digital-factory-mongodb and user name from my-user to mdfdb-admin
- I haven't created any kubernetes secret, which is normally the responsibility of the mongodb-kubernetes-operator

**Comment by bznein** [comment]
Hello @naddame and thanks for your report.

We will soon prepare detailed docs for this feature. When enabling SCRAM authentication and creating a user, the operator looks for a secret (the one referred under `users.passwordSecretRef`) which contains the password that needs to be used to generate the user.

You can either create it manually like this:

`kubectl create secret generic my-user-password --from-literal=password="my-password` 

Or provide it in a YAML file, here's an example that still has to be merged into the master:
https://github.com/mongodb/mongodb-kubernetes-operator/pull/152/files

Feel free to comment on this issue for further clarification if needed
