### ISSUE TITLE
Too many "Connection accepted" and "Connection ended" in the logs

### ISSUE THREAD

**Issue by neo2k** [mongodb/mongodb-kubernetes-operator#1544]
We use many MongoDB Instances with 3 Replica. Regular MongoDB Agent checks produces many "Connection accepted" and "Connection ended". In my case about  5 million lines of log messages every day.

This [Forum Thread](https://www.mongodb.com/community/forums/t/a-lot-of-noise-in-the-logs-connection-ended-connection-accepted/156635/7) is about that problem. One suggested solution is to use an connection pool in the client.

Would id be possible / a good idea to use a collection pool in the mongodb-agent?

**Comment by MartinHerrmanPerfana** [comment]
I have noticed the same behavior, didn't count the numbers yet. We are planning to upgrade from version 6 to version 7, so I'll have another check after the upgrade.
