### ISSUE TITLE
Publish the MongoDB community operator under OperatorHub

### ISSUE THREAD

**Issue by lsoica** [mongodb/mongodb-kubernetes-operator#1560]
By publishing the operator in this repository (https://github.com/redhat-openshift-ecosystem/community-operators-prod), it becomes accessible not just through OperatorHub, but also integrated into the operator catalog of any OKD/OCP cluster. This streamlines the process, allowing us to utilize the platform's provided version instead of deploying our own.

**Comment by nammn** [comment]
cc. @mircea-cosbuc @dan-mckean
