### ISSUE TITLE
agent image referenced by 0.10.0 release not available on quay.io

### ISSUE THREAD

**Issue by ascheja** [mongodb/mongodb-kubernetes-operator#1575]
**What did you do to encounter the bug?**
1. Install manager by applying https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/v0.10.0/config/manager/manager.yaml + https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/v0.10.0/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
2. Create a mongodb CRD
3. Mongodb pods fails to initialize because [quay.io/mongodb/mongodb-agent:107.0.1.8507-1](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/manager/manager.yaml#L48) cannot be found
![image](https://github.com/mongodb/mongodb-kubernetes-operator/assets/3932118/7aa492e6-add3-4cd2-bf51-4d9e307f76ca)

**Comment by nammn** [comment]
Hey @ascheja thanks for flagging this.
We did some refactoring in the past that basically moved all agents to the new repo, but it seems that we forgot to move some places.
https://github.com/mongodb/mongodb-kubernetes-operator/pull/1577 fixes that + I manually uploaded the missing agent to quay.io/mongodb/mongodb-agent:107.0.1.8507-1 as well
