### ISSUE TITLE
Broken link in `latest` release notes

### ISSUE THREAD

**Issue by vedantthapa** [mongodb/mongodb-kubernetes-operator#1586]
**What did you do to encounter the bug?**
1. Go to [latest release](https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.10.0).
2. Click on the `here` hyperlink under Logging section.

**What did you expect?**
Redirect to the relevant logging documentation, which, I guess is [this](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/logging.md)?

**What happened instead?**
Redirects to a non-existent page resulting in `404`.

**Screenshots**
<img width="1883" alt="Screenshot 2024-07-15 at 10 02 53 AM" src="https://github.com/user-attachments/assets/bb10b7d8-bea7-49eb-a5b8-f9d1971ceab8">

**Comment by Julien-Ben** [comment]
Hello @vedantthapa 
Thank you for spotting and reporting this, we will fix the links

**Comment by nammn** [comment]
@vedantthapa thanks for checking, it has been fixed: https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.10.0
