### ISSUE TITLE
Headless service not using cluster dns 

### ISSUE THREAD

**Issue by deveshk0** [mongodb/mongodb-kubernetes-operator#180]
After creating the cluster resource ,  a headless service will be created and that service is added to the `/var/lib/automation/config/automation-config`.

But it is using cluster.local as suffix not my cluster dns suffix like `kubet-cluster.internal`

eg - `test-mongodb-0.test-mongodb-svc.test-mongo.svc.cluster.local` is created instead of `test-mongodb-0.test-mongodb-svc.test-mongo.svc.kubet-cluster.internal``

Any where we can change that?

**Comment by rodrigovalin** [comment]
Unfortunatelly, there's no way we can set this. The relevant line is this:

https://github.com/mongodb/mongodb-kubernetes-operator/blob/37c8442101bfe371fe7f7a5bb2b5525b5b9e69f0/pkg/controller/mongodb/replica_set_controller.go#L372

This is actually a good "first issue" if you would like to contribute to the project :)

**Comment by deveshk0** [comment]
There are two approaches, I can think of - 
-  Quick and easy one, use an environment variable to take info from the user.
-  Somehow figure out cluster-dns in the operator using go-client(will have to check if there is any apis available for that) or using `/etc/resolv.conf` since that contains that info.

**Comment by rodrigovalin** [comment]
@deveshk0 

I'm not sure you can fetch the cluster domain from the `client-go` unfortunatelly. But what can be done is to add a `spec.clusterDomain` string attribute to the `MongoDB` resource that you can use to pass your custom cluster domain, that the operator can use as the default value of the `getDomain` function I shared in my previous comment.

**Comment by deveshk0** [comment]
@rodrigovalin can you have look into the #181  I did with env variable as it required minimal changes.
