### ISSUE TITLE
add kustomize file to be deployable as module

### ISSUE THREAD

**Issue by blaggacao** [mongodb/mongodb-kubernetes-operator#183]
Adding a kustomization file would enable the deployment to be consumed as "kustomization module".
 A very light weight one is by no means any stance for or against any specific deployment mode, it just enables this kind of consumption.

This consumption in a _kustomization.yaml_ is what I'm aiming for:
```
resorces:
  - gitub.com/mongodb/mongodb-kuberentes-operator/deploy?ref=master
```

**Comment by bznein** [comment]
This has been closed by #240
