### ISSUE TITLE
Packaging the operator as a helm chart?

### ISSUE THREAD

**Issue by kylos101** [mongodb/mongodb-kubernetes-operator#193]
Hi mongodb team,

I'm just curious, are there plans to package this operator as a helm chart?

If no, why? I assume now might be too early to package it (because it is in a state of flux). Or perhaps there's some other set of reasons?

In the meantime, I'll follow the instructions to clone and then kubectl create & get. Thank you so very much for putting this together, it is very much appreciated.

Take care,

Kyle

**Comment by LouisPlisso** [comment]
Hi @kylos101,
yes we are planning to prepare a helm chart for this operator, but you're right that it's a bit too early as of now

Stay tuned for new features and a helm chart 😉 
Louis

**Comment by kylos101** [comment]
Very cool, thanks Louis! Have a nice day. 😀

**Comment by kylos101** [comment]
Closing because my question was answered. Thanks again!

**Comment by caiconkhicon** [comment]
Sorry, even though this issue was closed, may I ask when will it be implemented? Next month, or next year, etc.

**Comment by rtrive** [comment]
Any updates on that?

**Comment by theburi** [comment]
We have not done much progress here. But we have reopened this ticket and will try to find some time.

**Comment by bznein** [comment]
Hi @caiconkhicon and @rtrive,

This is a nice feature that we would like to have but are not actively working on now, you are more than welcome to contribute!
Feel free to open a PR with a proposed chart and we can go from that.

Nikolas

**Comment by manuel-koch** [comment]
Any estimate when enhance the helm-chart to support https://github.com/mongodb/mongodb-kubernetes-operator/issues/380 is available ?

I don't like to manually create ServiceAccount with same privileges as the operator and those privileges seem far too permissive for a simple MongoDb ReplicaSet/Pod that is not acting as an operator.

**Comment by rodrigovalin** [comment]
All of our Kubernetes Operators are available in the [MongoDB Helm Repo](https://github.com/mongodb/helm-charts).
