### ISSUE TITLE
[Documentation] How to bind /data/db to host path

### ISSUE THREAD

**Issue by Brice187** [mongodb/mongodb-kubernetes-operator#202]
It would be nice if you could add some examples how to use host mounts with this operator.
I want to build a script for mongodump, which my backup solution triggers and I want to backup the whole mongodb data dir

**Comment by bznein** [comment]
Examples have now been added [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/arbitrary_statefulset_configuration/mongodb.com_v1_hostpath.yaml)
