### ISSUE TITLE
/opt/scripts/agent-launcher.sh: line 114: splittedAgentFlags[*]: unbound variable

### ISSUE THREAD

**Issue by brechtvalcke** [mongodb/mongodb-kubernetes-operator#211]
Hi, sadly my installation broke again..

Mongodb kubernetes operator 1.7 worked fine for about a month and than out of nowhere it broke and if I check the logs of the ops manager that is broken I get this error in there:
`/opt/scripts/agent-launcher.sh: line 114: splittedAgentFlags[*]: unbound variable`

I really don't understand! I removed the entire namespace and enterprise operator. Reinstalled everything again and I get the same error. It's really wierd! Why has this happened? And how do I resolve this?

**Comment by chatton** [comment]
Hi @brechtvalcke thanks for the report, I think you've accidentally created this issue in the wrong repository (this is for the Community Operator)

I think you were looking for [The Enterprise Operator](https://github.com/mongodb/mongodb-enterprise-kubernetes)

Closing this issue, but please re-open it there

Could you also help me clarify a few things?

Did this issue occur during an upgrade from 1.7.1 -> 1.8.0?

You mention that the Ops Manager deployment  is broken, but the error you included looks like it came from one of the database pods.
