### ISSUE TITLE
cr annotations don't seem to update

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#215]
I tried to update my mongodb to the latest 4.2.10 but nothing happened.
I noticed the CR does have an annotation "mongodb.com/v1.lastVersion: 4.2.9". After updating that to 4.2.10 the operatore ran the upgrade.
When and how is that annotation supposed to get updated?

**Comment by chatton** [comment]
Hi @fireba11 

That annotation is used internally by the operator to track progress of in-progress upgrades across multiple reconciliations, but it sounds like it's not working as intended.

Just to clarify, you updated the spec.version from 4.2.9 -> 4.2.10, the operator didn't apply any changes to the StatefulSet until you manually updated the lastVersion annotation?

**Comment by fireba11** [comment]
Correct.
