### ISSUE TITLE
Unable to connect to cluster

### ISSUE THREAD

**Issue by Thoro** [mongodb/mongodb-kubernetes-operator#221]
Hi

have just tried to create my first cluster with 2 nodes in total, when connecting to their individual IPs I can see who is master and who is not. 

When trying to connect via 

```
mongo "mongodb://10.21.240.152:27017,10.21.240.153:27017/?replicaSet=trackingdb"
```
I receive an output like:

```
MongoDB shell version v4.4.1
connecting to: mongodb://10.21.240.152:27017,10.21.240.153:27017/?compressors=disabled&gssapiServiceName=mongodb&replicaSet=trackingdb


{"t":{"$date":"2020-10-16T10:52:12.101Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"trackingdb","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set trackingdb"}}
Error: connect failed to replica set trackingdb/10.21.240.152:27017,10.21.240.153:27017 :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```

The same happens with Robo 3T, I see that connections go to both nodes, what might be the issue here?

**Comment by antonlisovenko** [comment]
hi @Thoro thanks for the report
Do you have the same problem if you have a replica set with 3 members?

**Comment by Thoro** [comment]
I have also tried it with 3 members, but scaled it down again, I just discovered the --verbose option on the mongoshell, and I believe I figured it out.

My names for mongodb are not globally resolve able, so it tries to connect to the cluster internal names.

I have updated my local hosts file with the names and the "public" (private but routed) ips and now it seems to connect fully.
