### ISSUE TITLE
 MongoDB Community Operator NA for ppc64le arch

### ISSUE THREAD

**Issue by krishvoor** [mongodb/mongodb-kubernetes-operator#226]
Hello Team,

Taking a quick glimpse/code read through  [mongodb-kubernetes-operator] I realized inorder to deploy MongoDB Community Operator on IBM POWER systems additional efforts would be needed.

Per my observation(s) I saw the following requires enablement on IBM POWER architecture -

**Docker Images Needed for POWER Architecture -**
mongodb-kubernetes-operator- https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/operator.yaml#L18
mongodb-agent - https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/operator.yaml#L34
mongodb-kubernetes-operator-version-upgrade-post-start-hook - https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/operator.yaml#L36

**Binaries needed for POWER Architecture -**
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/agent/Dockerfile#L14
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/agent/Dockerfile#L23
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/agent/Dockerfile#L32

I would like to contribute/work towards enabling community mongodb operator for POWER Architecture.

Please comment/advice on how to get started.

**Comment by theburi** [comment]
MongoDB Agent and db tools have Power binaries. just a matter of getting the right URL in a download center.
Let us look at the readiness probe if we could provide that in this repo as well.

**Comment by krishvoor** [comment]
@theburi - Thanks for your comments, we would also need ppc64le [server] arch. specific docker images in CI for continous releases, can you perhaps guide me on how I can propose IBM Power Systems in CI Environment ?

**Comment by theburi** [comment]
After looking at a code we realized that our probes need to be included in this repository. We will publish them in the next release. That will allow us to rebuild them targeting ppc64le architecture.

Here is a link to mongodb Agent for Power https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-manager-10.19.0.6566-1.ppc64e1.ubuntu1604.deb
and mongodb binaries are available from download center https://www.mongodb.com/download-center/community/releases

We don't build Docker images as part of this project, but rather use any available in the community like this one https://github.com/docker-library/mongo
