### ISSUE TITLE
Shouldn't the plural in crd file be finishing with an `s`  ?

### ISSUE THREAD

**Issue by radtriste** [mongodb/mongodb-kubernetes-operator#237]
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_mongodb_crd.yaml#L19

```
plural: mongodb
```

We would expect 

```
plural: mongodbs
```

**Comment by radtriste** [comment]
I can PR quickly if needed

**Comment by radtriste** [comment]
Hello,

Could we have an update here ?
IMO, we should have a correct plural value in the crd.

This is creating problem when we want to read the status of instances created with the MongoDB operator to get information about it (like the URI)

**Comment by jamesbroadhead** [comment]
Hi there - 

From a purely organizational/branding perspective, we don't pluralize 'MongoDB' on its own - it tends to be 'MongoDB Instances' or 'MongoDB Servers'. As such, we didn't intend to change this. 

However, if it's causing compatibility problems, that's a different matter -- does the Kogito Operator require that plural forms match the singular with an extra 's'? Is that documented somewhere? 

Thanks, 

James

**Comment by radtriste** [comment]
Hi @jamesbroadhead 

I see your point.

Default behavior of our mapper was to just add the `es` or `s` as a plural name for the kind => https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/restmapper.go#L126
So indeed, there was some problems.

Using a DynamicRestMapper from https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/apiutil/dynamicrestmapper.go seems to solve the problem.
It will read the information direct from crd.

Thanks for taking time for that...
Will now close the issue.
