### ISSUE TITLE
[Feature Request] Multicluster Capability

### ISSUE THREAD

**Issue by LaumiH** [mongodb/mongodb-kubernetes-operator#253]
I have set up a MongoDB ReplicaSet spanning two clusters with the help of [Submariner](https://submariner.io/) and StatefulSets.

Submariner exposes local Services (also Headless Services) onto the remote cluster, meaning a cloned Service is created in the remote cluster using the cluster's CIDR. Like this, a pod in another (remote) cluster can resolve the local pods by querying Submariner's stub domain. It works similar to Istios implementation, however Istio does not deal well with Headless Services yet.
The pods can be addressed using `<pod-id>.<cluster-id>.<namespace>.<svc-name>.svc.clusterset.local`.

My idea now is to add multicluster support to the MongoDB Community Operator. As of now, all the mongo pods need to be configured manually and lose config over restarting.

Would you be willing to guide me through the existing code base and show me what might need to change in order to provide this capability? Or is this not possible for some reason? 

I am very interested in adding this!

**Comment by kwill4026** [comment]
Hello @LaumiH I am interested in how your setup of MongoDB using submariner looks like. Are you utilizing https://github.com/bitnami/charts/tree/master/bitnami/mongodb?

**Comment by LaumiH** [comment]
Hi @kwill4026, I did not use any ready-to-go chart. I set it up manually with the most basic configuration in a StatefulSet with 3 replicas. Then I connected the pods by hand.
