### ISSUE TITLE
Failed global initialization: BadValue: Authorization with 3.x

### ISSUE THREAD

**Issue by aeisma** [mongodb/mongodb-kubernetes-operator#256]
Using authentication mode ["SCRAM"] with version: "3.6.20" (also tried 3.6.19), as well as when using version: "4.2.7" in combination with featureCompatibilityVersion: "3.6" result in a mongodb crash with:

``
[main] Failed global initialization: BadValue: Authorization is enabled but no authentication mechanisms are present.
``

When using version: "4.2.7" without featureCompatibilityVersion, mongod runs, but I need 3.6 compatibility.

**Comment by theburi** [comment]
With this operator, we started with MDB 4.0 support as 3.6 is going into EOL very soon. At the moment we only support SCRAM-SHA-256. However, MongoDB 3.6 could only support SCRAM-SHA-1 and that is what causes this error. We never considered that 3.6 would need to be supporting with new deployments. 
We will add it to our backlog.

**Comment by jmcollin78** [comment]
Same for me 👎 (

**Comment by shardulsrivastava** [comment]
looking for support for Mongo DB 3.6 , any updates ??

**Comment by jmcollin78** [comment]
You are right. I migrate to MongoDB 4.5.4.
