### ISSUE TITLE
Q: is there a more elegant way to fix a broken node

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#268]
** Not a bug but a question **
If your cluster breaks (in our case out of space error, we didn't have an alert on testing so we didn't resize the pv in time) and mongo can't get the node back up because oplog isn't long enough the mongo documentation advices you to shut down the node, delete it's data, start it and wait for it to get synced.
Obvously you can't do it like that on kubernetes ...
We figured out one way and were wondering if operator provides a more elegant option (of not that could be a freature request ;-))

* delete pv (shell gets stuck since it's in use)
* use another shell to delete pvc (shell gets stuck since it's in use)
* use a third shell to delete the pod (pv and pvc will get deleted now)
* the pod gets stuck with "pending"
* delete the pod again (now pv and pvc get recreated)

The node wil come back up and start syncing ... but that is far from elegant or failsave ;-)

**Comment by chatton** [comment]
Hi @fireba11 ,

The Community operator does not currently have a solution for this problem.
