### ISSUE TITLE
Persistent Volume Claim (PVC) storage automated expansion

### ISSUE THREAD

**Issue by rajavignesh** [mongodb/mongodb-kubernetes-operator#270]
**What did you do to encounter the bug?**
Updated the below in CR yaml file for expanding the storage. Changing "storage" parameter from 4Gi to 6Gi (example values) is not reflected in Stateful Set and PVC not getting resized after applying the CR file (changes are reflected in Object file)
  **_persistent: true
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "xxx"
            resources:
              requests:
                storage: 4Gi_**

**What did you expect?**
PVC to be expanded when changes are made in CR yaml file and applied

**What happened instead?**
PVC files are not getting resized

**Screenshots**

**Operator Information**
All on latest version

**Kubernetes Cluster Information**
kubectl version --client
**Output**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by antonlisovenko** [comment]
Hi @rajavignesh 

Can you try the resizing procedure that is described for the Enterprise Operator MongoDB? https://docs.mongodb.com/kubernetes-operator/stable/tutorial/resize-pv-storage/

Statefulset doesn't allow to change the PVC templates directly - so you need some manual actions to workaround that

**Comment by rajavignesh** [comment]
Hi @antonlisovenko 

Following the steps in the document works well. Looking if there is an automated way to increase the storage size like been done for CPU & Memory.

**Comment by antonlisovenko** [comment]
@rajavignesh 

great that helped!
From what I know the automated way could be to let the Operator perform the same steps as described in the instruction and we don't have this planned yet.

**Comment by ossinkine** [comment]
Hi guys, I guess the automated storage expansion should be implemented, so I suggest to open this issue

**Comment by ossinkine** [comment]
@chatton @bznein @irajdeep @rodrigovalin How do you look at it?

**Comment by bznein** [comment]
Hi @ossinkine,

This is not on our roadmap at the moment, but we are happy to accept external contributions to it.

**Comment by ossinkine** [comment]
My point is if we have open issue external contributors can see it and maybe contribute. Or at least we can follow the issue and see when it appears in your roadmap.

**Comment by bznein** [comment]
@ossinkine you can definitely open a new issue, or this one can be reopened, and we can add a `feature-request` label. Nothing against it!
