### ISSUE TITLE
How to resolve the problem 'CrashLoopBackOff' installing operator

### ISSUE THREAD

**Issue by peter6968** [mongodb/mongodb-kubernetes-operator#306]
Hi,excuse me😭.
I met some problems installing the 'operator'😭😭 :

![image](https://user-images.githubusercontent.com/24848930/106345053-46852e00-62e8-11eb-928e-f303dc3de199.png)

![image](https://user-images.githubusercontent.com/24848930/106345085-9106aa80-62e8-11eb-9a4d-3daf5ec838ac.png)

I used the following commands to create this 'operator'.
> kubectl create ns mongodb

> kubectl create -f deploy/crds/mongodb.com_mongodbcommunity_crd.yaml -n mongodb

>kubectl create -f deploy/operator/ -n mongodb

>
But I can't understand the problem ,I can't find the reason in logs.

**Comment by peter6968** [comment]
I didn't modified the YML files.😭

**Comment by JohnnyS318** [comment]
I encountered the same issue with a fresh minikube cluster.

**Comment by avi-nehama** [comment]
Same here, I just followed the instructions exactly as specified [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md) and got the same errors as described by peter6968

**Comment by sneben** [comment]
The commit [db40116](https://github.com/mongodb/mongodb-kubernetes-operator/commit/db401165847cf4ee8c3572f70094ae5973b0db2b) 2 days ago (were the CRD was renamed) seem to be incompatible with the 0.4.0 version, which is still referenced in **operator.yaml**. Use everything from the release, then it works.

**Comment by avi-nehama** [comment]
This indeed solved the problem, thanks!

**Comment by alyacb** [comment]
Hi! Release [v0.5.0](https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.5.0) is out now, and the version referenced in operator.yaml is fixed in that tag.

**Comment by avi-nehama** [comment]
Looks like you can close this issue, though the documentation page '[deploy-configure](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md)' still uses the old name, i.e. 
`kubectl get mongodb --namespace <my-namespace>` 
Should be:
`kubectl get **mongodbcommunity** --namespace <my-namespace>`

**Comment by alyacb** [comment]
Thank you for pointing that out @avi-nehama! I updated the documentation to fix it.

**Comment by peter6968** [comment]
Thanks !
