### ISSUE TITLE
Operator serviceaccount is missing pods permission on Openshift

### ISSUE THREAD

**Issue by mrethers** [mongodb/mongodb-kubernetes-operator#311]
**What did you do to encounter the bug?**
1. Install operator from OperatorHub on Openshift
2. Create a ops manager secret
3. Create a MongoDBOpsManagers instance
4. Go to the operator log

**What did you expect?**
The Ops Manager cluster should be deployed.

**What happened instead?**
The operator is showing a missing permission with the service account:

`E0201 20:43:55.653468       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:handshake:mongodb-enterprise-operator" cannot list resource "pods" in API group "" in the namespace "handshake"`

**Operator Information**
 - 1.9.0
 - 
**Kubernetes Cluster Information**
 Openshift 4.5

**Additional context**
I checked the MANAGED_SECURITY_CONTEXT environment variable is set to true on the operator pod.

```apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: handshake
spec:
  adminCredentials: mongodb-ops-manager-credentials
  applicationDatabase:
    members: 3
  configuration:
    mms.fromEmailAddr: admin@thecompany.com
  externalConnectivity:
    type: LoadBalancer
  replicas: 1
  version: 4.4.7
status:
  applicationDatabase:
    lastTransition: '2021-02-01T21:00:30Z'
    members: 3
    observedGeneration: 1
    phase: Running
    version: 4.2.2-ent
  opsManager:
    lastTransition: '2021-02-01T21:00:30Z'
    message: StatefulSet not ready
    observedGeneration: 1
    phase: Pending
    resourcesNotReady:
      - kind: StatefulSet
        message: 'Not all the Pods are ready (total: 1, updated: 1, ready: 0)'
        name: ops-manager
    url: 'http://ops-manager-svc.handshake.svc.cluster.local:8080'
```

**Comment by bznein** [comment]
Hi @mrethers, there was indeed an error in our permissions with 1.9.0, you can upgrade to 1.9.1 which should fix the issue

**Comment by jamesbroadhead** [comment]
This ticket relates to the Enterprise Operator, and this repo is for the Community Operator. 
For support on the Enterprise Operator, you can use the [Enterprise Repo](https://github.com/mongodb/mongodb-enterprise-kubernetes), refer to the [Enterprise Operator Docs](https://docs.mongodb.com/kubernetes-operator/master/) visit the [Support Center](https://support.mongodb.com/welcome). 
Hope that these links help you resolve your issue
