### ISSUE TITLE
MongoDb Authentication Failed error

### ISSUE THREAD

**Issue by green999** [mongodb/mongodb-kubernetes-operator#314]
I  have deployed the following replicaset and it is working fine. When I try connect to the instance I get 'authenticaton failed ' error. 

**************
>>kubectl get mdbc
The instance is **running** mode.

************
 >>**mongo localhost:27017 -u my-user -p admin@1234**
      MongoDB shell version v3.6.8
      connecting to: mongodb://localhost:27017/test
      Implicit session: session { "id" : UUID("516c5483-f498-43fd-b79f-adc50a9c52d7") }
      MongoDB server version: 4.2.6
      WARNING: shell and server versions do not match
      2021-02-02T18:49:58.734+0000 E QUERY    [thread1] Error: Authentication failed. :
      DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
      @(auth):6:1
      @(auth):1:2
      exception: login failed
**************
---
apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: testdb
spec:
  additionalMongodConfig: {}
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: test-mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

---
apiVersion: v1
kind: Secret
metadata:
  name: test-mongodb-password
type: Opaque
stringData:
  password: admin@1234
**********************

What is that I am doing wrong? I tried with mongo-express, and it also gives the same error.

Any help is appreciated.  

Thanks!

**Comment by ArrowRaider** [comment]
I can't login no matter what either.  Is this github project actually working for anyone here?

**Comment by jamesbroadhead** [comment]
@green999 could you try again please with a new mongodb shell - the one you are using is 3.6.8 - could you try with the shell that comes with 4.2.6 or above please?

**Comment by pinkerltm** [comment]
I experience the same error with Shell(and Server) v4.2.6
