### ISSUE TITLE
Cannot add node selector or node affinity to stateful set with custom volume and storage class

### ISSUE THREAD

**Issue by akshay654** [mongodb/mongodb-kubernetes-operator#320]
I am trying to create the Mongo DB stateful set with custom storage class and volume attached to it,I am using the below Yaml file for the deployment, but i am not able to select a specific node for my pods to run on the specified node.

Node Affinity yaml -

apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "premium"
            resources:
              requests:
                storage: 1Gi
      template:
             containers:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mongodbtest
                operator: In
                values:
                - testnewnamespace

Node Selector yaml- 

apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    spec:
      template:
        spec:
          containers:
		  nodeSelector:
		     mongodbtest=testnewnamespace
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "managed-premium"
            resources:
              requests:
                storage: 15Gi

**Comment by chatton** [comment]
Hi @akshay654,

Can you provide a little more information? Is the underlying stateful set not being created as expected? What is the expected result?

Would you also be able to attach the operator logs and formatted MongoDBCommunity resource definitions (just so it's easier to test/repro)

**Comment by akshay654** [comment]
Hi @chatton 

Thanks for reaching out.

I successfully figured it out, It was syntax issue and now the statefulset and pods are created with the requested node selector.

Following is the configuration that works for me, Hope someone finds it useful if needed to achieve the same configuration.

apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "managed-premium"
            resources:
              requests:
                storage: 15Gi
      template:
         spec:
             containers:
             nodeSelector:
			     workload : pipeline
