### ISSUE TITLE
Authenticate Client using X509 Certificate

### ISSUE THREAD

**Issue by rajavignesh** [mongodb/mongodb-kubernetes-operator#324]
**What did you do to encounter the bug?**
Updated "mongodb.com_v1_mongodb_cr.yaml" --> "spec.security.authentication.modes" to "X509"
Applied the manifest using kubectl command

**What did you expect?**
Enable x509 certificate for client authentication

**What happened instead?**
Received below error message
"The MongoDB "ea-mongodb-mvp" is invalid: spec.security.authentication.modes: Unsupported value: "X509": supported values: "SCRAM"

**Operator Information**
 - Operator Version: mongodb-kubernetes-operator:0.3.0
 - MongoDB Image used: 4.2.10

If possible, please include:
 - yaml definitions for your objects
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.10"
  security:
    authentication:
      enabled: true
      **modes: ["X509"]**

**Comment by chatton** [comment]
Hi @rajavignesh, the Community Operator does not support X509 authentication, did you intend to use the [enterprise operator](https://github.com/mongodb/mongodb-enterprise-kubernetes) which does?

**Comment by rajavignesh** [comment]
Hi @chatton, tried in community operator. Would like to know if there is a workaround to implement this feature.
