### ISSUE TITLE
TLS allowing connection without certificate

### ISSUE THREAD

**Issue by rajavignesh** [mongodb/mongodb-kubernetes-operator#328]
**What did you do to encounter the bug?**

After enabling TLS in-transit, the client able to establish a connection without a TLS certificate by mentioning "--tlsAllowInvalidCertificates" as mentioned below and making changes to yaml file is not reflected in the pod mongodb config file.
Connection String:
mongo --host ea-mongodb-tls/tls-00,tls-01,tls-02 -u mongodba -p pass --tls --tlsAllowInvalidCertificates

1. Added TLS parameter in "mongodb.com_v1_mongodbcommunity_cr.yaml" file
2. Set "allowConnectionsWithoutCertificates" parameter to "false" in "spec.additionalMongodConfig"
3. In "/data/automation-mongod.conf", "mode" is set to "requireTLS"

**What did you expect?**
The client should not able to connect to MongoDB without a certificate when the configuration is set to "mode: requireTLS"

**What happened instead?**
The client able to establish a connection without a TLS certificate by mentioning "--tlsAllowInvalidCertificates" when the configuration is set to "mode: requireTLS"

**Operator Information**
 - Operator Version: 0.5.0

**Additional context**
Even mentioning "spec.additionalMongodConfig.net.tls.allowConnectionsWithoutCertificates: false" in "mongodb.com_v1_mongodbcommunity_cr.yaml", changes are not reflected in the pod config file.

**mongodb.com_v1_mongodbcommunity_cr.yaml**
    tls:
      enabled: true      
      certificateKeySecretRef:
        name: sec-ea-mongodb-tls
      caConfigMapRef:
        name: cm-ea-mongodb-tls
  additionalMongodConfig:
    net:
      tls:
        allowConnectionsWithoutCertificates: false

**/data/automation-mongod.conf**
net:
  bindIp: 0.0.0.0
  port: 27017
  tls:
    CAFile: /var/lib/tls/ca/ca.crt
    allowConnectionsWithoutCertificates: true
    certificateKeyFile: /var/lib/tls/server/dcc70585bb6fe4f9acff054b33df7d79fd723aa7015f51da8e6d411cbcd36ba3.pem
    mode: requireTLS

**Comment by rajavignesh** [comment]
Can someone please share your inputs on this.

**Comment by bznein** [comment]
Hi @rajavignesh, 

thanks for reporting this issue. 
It looks like the `additionalMongodConfig` object is not being correctly passed through.

I will try to reproduce it and come back to you as soon as possible :)

**Comment by bznein** [comment]
Hi @rajavignesh,

I wasn't able to reproduce the `additionalMongodConfig` issue on `master`.
However, we had some discrepancies between operator version and CRDs due to the re-scaffolding work we have been doing, which might have caused your issue.

Would you be abele to re-test your scenario using the newly released `0.5.1` version and newest CRDs?

Thanks
Nikolas

**Comment by rajavignesh** [comment]
> Hi @rajavignesh,
> 
> I wasn't able to reproduce the `additionalMongodConfig` issue on `master`.
> However, we had some discrepancies between operator version and CRDs due to the re-scaffolding work we have been doing, which might have caused your issue.
> 
> Would you be abele to re-test your scenario using the newly released `0.5.1` version and newest CRDs?
> 
> Thanks
> Nikolas

**Comment by rajavignesh** [comment]
Hi @bznein 
I tried with the latest release but the parameter "allowConnectionsWithoutCertificates" is set to true in the MongoDB config file even if it's mentioned as false in the CR.

  **_additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    net.tls.allowConnectionsWithoutCertificates: false_**

When you enable TLS, are you able to establish a database connection without a TLS certificate mentioning "tlsAllowInvalidCertificates" in the connection string?

**Comment by rajavignesh** [comment]
Hi @bznein 
![mongodb operator tls](https://user-images.githubusercontent.com/75835084/108988388-6a0a8100-76ba-11eb-9fdf-52ea3daf10d3.jpg)

In file "controllers/mongodb_tls.go" the function "tlsConfigModification" has the parameter value "allowConnectionsWithoutCertificates" hardcoded as **true**.

**args.Set("net.tls.allowConnectionsWithoutCertificates", true)**

**Comment by rajavignesh** [comment]
Team, please share your input.

**Comment by rajavignesh** [comment]
Tried with Operator version 0.7.2, still, I am able to connect without a certificate by setting "allowInvalidCertificates" parameter to true.

**Comment by carlos-cuellar-maravilla** [comment]
In mongodb 6.0 community edition.  Is  able to connect when using requireTLS, certificateKeyFile and CAfile defined in mongodb.conf while using tlsAllowInvalidCertificates=true at the connection string.
