### ISSUE TITLE
Unable to connect to mongodb instance

### ISSUE THREAD

**Issue by semin-park** [mongodb/mongodb-kubernetes-operator#331]
**What did you do to encounter the bug?**
1. `git clone https://github.com/mongodb/mongodb-kubernetes-operator.git`
    * master branch - commit c4b20bb
2. `cd mongodb-kubernetes-operator`
3. `kubectl create -f deploy/crds/mongodb.com_mongodbcommunity_crd.yaml`
4. Do what's written [in this issue](https://github.com/mongodb/mongodb-kubernetes-operator/issues/312#issuecomment-771629962)
5. `kubectl create -f deploy/operator/`
6. `kubectl create -f deploy/crds/mongodb.com_v1_mongodbcommunity_cr.yaml`
7. Wait until all pods are running
8. `kubectl exec -it example-mongodb-0 -- mongo`

Trying to run the mongo shell on that pod results in a "Connection refused" error, which happened because mongod didn't start yet, because it couldn't find `/data/automation-mongod.conf`

**What did you expect?**

Expected mongo shell to be able to connect just fine.

**Operator Information**
 - Operator Version (tried master, v0.5.0, v0.4.0)
 - MongoDB Image used 4.2.6

**Additional context**

It seems like the mongod container sleeps repeatedly until `/data/automation-mongod.conf` file is created. But that configuration file does not exist in the given path and even after hours of the pod's creation, mongod is still sleeping.

```
root@example-mongodb-0:/# ls /data
configdb  db  lost+found
```

**Comment by semin-park** [comment]
The problem is that for some reason `/data/automation-mongod.conf` is not there. If I create a configuration manually, mongod does pick it up and starts running.

I've tried `master`, `v0.5.0` and `v0.4.0` and in all three cases, I'm experiencing the exact same problem. Does anyone have an idea?

@chatton Sorry to bug, but would highly appreciate if you could have a look :)

**Comment by bznein** [comment]
Hi @semin-park,

apologies for the delay in the answer, can you show us the logs of the agent pod?

```kubectl logs example-mongodb-0 -c mongodb-agent```

**Comment by semin-park** [comment]
Unfortunately I'm not working on this anymore, so I'll close this issue for now
