### ISSUE TITLE
kubectl create -f deploy/crds/mongodb.com_mongodbcommunity_crd.yaml command fails

### ISSUE THREAD

**Issue by dotrc** [mongodb/mongodb-kubernetes-operator#334]
**What did you do to encounter the bug?**
1. Go to 'https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#procedure'
2. Run the command `kubectl create -f deploy/crds/mongodb.com_mongodbcommunity_crd.yaml`

**What did you expect?**
`kubectl create -f deploy/crds/mongodb.com_mongodbcommunity_crd.yaml` command should succeed.

**What happened instead?**
`deploy/crds/mongodb.com_mongodbcommunity_crd.yaml` is not present in the repository, hence the command fails.

**Comment by bznein** [comment]
Hi @dotrc,

you are right!
https://github.com/mongodb/mongodb-kubernetes-operator/pull/327/ restructured the content of the repo and we will soon update our documentation to reflect this.
In the meantime you can find the file you are looking for in `config/crd/bases`

Nikolas

**Comment by dotrc** [comment]
Thanks @bznein!
Will try out the guidelines specified in #327.

You may close this issue once the documentation gets updated.

./.rc
