### ISSUE TITLE
failed to create symbolic link '/data/journal': Permission denied in opsmanager pod

### ISSUE THREAD

**Issue by tonythomasm** [mongodb/mongodb-kubernetes-operator#338]
Getting below error while creating MongoDBOpsManager. Error from the pod is as given below:

`tonythomas@Tonys-MacBook-Pro mongo_operator % kubectl logs ops-manager-db-0 -n mongodb
{"logType":"agent-launcher-script","contents":"Using Kubernetes CA file"}
ln: failed to create symbolic link '/data/journal': Permission denied`

I followed the below given documentation to install entererpise-operator and opsmanager in kubernetes. https://www.mongodb.com/blog/post/running-mongodb-ops-manager-in-kubernetes

operator got installed successfully. But opsManager deployment is failing with statefulset deployment of backing database for Ops Manager.

attached files:
[mongodb-enterprise-operator_yaml.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6002749/mongodb-enterprise-operator_yaml.txt)
[ops-manager_yaml.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6002750/ops-manager_yaml.txt)
[opsmanager_sts_yaml.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6002752/opsmanager_sts_yaml.txt)

( from above opsmanager_sts_yaml.txt is the generated statefulset from cluster )

**What did you expect?**
successful deployment of statefulset pods for opsmanager

**Comment by jamesbroadhead** [comment]
Hi @tonythomasm - 
The MongoDBOpsManager CRD belongs to the [Enterprise Operator](mongodb/mongodb-enterprise-kubernetes). Please follow the instructions on that repo for opening a Support Case.
All the best, 

James
