### ISSUE TITLE
mongoDb-operator pod in error state : request.go:621] Throttling request took 1.046072429s, request: GET:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s

### ISSUE THREAD

**Issue by jagurram** [mongodb/mongodb-kubernetes-operator#341]
Hello,

What wrong on the config pull on the repo ?

**What did you do to encounter the bug?**
1. kubectl apply -f /crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
2. kubectl apply -f mongodb-kubernetes-operator/config/rbac/role.yaml
3. kubectl apply -f mongodb-kubernetes-operator/config/rbac/role_binding.yaml
4. kubectl apply -f mongodb-kubernetes-operator/config/rbac/service_account.yaml
5. kubectl apply -f mongodb-kubernetes-operator/config/manager/manager.yaml

**What did you expect?**
all mongodb-kubernetes-operator pod's in running state

**What happened instead?**

pod in error state. 
kubectl get logs : 
I0218 19:15:28.282206       1 request.go:621] Throttling request took 1.046072429s, request: GET:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s

**Screenshots**

**Operator Information**
 - Minikube 8gb RAM

**Comment by bznein** [comment]
HI @jagurram, 
We troubleshoot the issue and what happened is that you are probably applying CRDs from `master` but using operator `0.5.0`. 

There are two workarounds to this: 
either checkout `v0.5.0` tag on the repository and use the CRDs files from that tag
or wait for `v0.5.1` release, which is coming soon.

Thanks
Nikolas

**Comment by jagurram** [comment]
Hi, thanks for the reply. The workaround works well. I have use the old crd.
You can close the ticket.
