### ISSUE TITLE
no matches for kind "MongoDB" in version "mongodb.com/v1"

### ISSUE THREAD

**Issue by edenjiga** [mongodb/mongodb-kubernetes-operator#353]
no matches for kind "MongoDB" in version "mongodb.com/v1"
1. Install mongodb-kubernetes-operator
2. Execute kubectl apply -f infra/k8s/delivery-mongo-depl.yaml
![image](https://user-images.githubusercontent.com/19752691/108733977-fa9b6280-74fc-11eb-824c-c39e15b5dfde.png)

3. See error
![image](https://user-images.githubusercontent.com/19752691/108734046-0c7d0580-74fd-11eb-94da-df654166b193.png)

**What did you expect?**
Create a 3 new pods.
**What happened instead?**
recive a error

**Comment by bznein** [comment]
Hi @edenjiga,

I see you are referring to a local file `infra/k8s/delivery-mongo-depl.yaml`. This file however is for the old CRD. In Version 0.4.0 we released a breaking change in which we renamed our CRDs from MongoDB to MongoDBCommunity.

Can you make sure to either use updated CRDs or a compatible version of the operator?

**Comment by joshua-hester** [comment]
He was probably following the same blog post I was following by Mongo:
https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper

The links don't even work in this article and I got the same error.

**There needs to be more consistency, this article (by Mongo team) was only create two months ago and has bad info.**

**Comment by joshua-hester** [comment]
@edenjiga this is the correct naming convention based on release v0.51 of this repo that @bznein was referencing.

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity

metadata:
  name: mongodb
```

**Hopefully they update the article.**

**Comment by joshua-hester** [comment]
@chatton needs to update his blog post with the correct info. 

reference: https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper

**Comment by edenjiga** [comment]
@joshua-hester  thanks, its working now

**Comment by bznein** [comment]
Hi @joshua-hester @edenjiga, thank you for your contribution, we updated the blog post to reflect the breaking change: https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper

**Comment by pityonline** [comment]
At first, I followed [this article](https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-sharded-cluster/) and it says:

```
error: unable to recognize "mongodb.yaml": no matches for kind "MongoDB" in version "mongodb.com/v1"
```

Then I followed [this comment](https://github.com/mongodb/mongodb-kubernetes-operator/issues/353#issuecomment-786673812), it says:

```
error: unable to recognize "mongodb.yaml": no matches for kind "MongoDBCommunity" in version "mongodbcommunity.mongodb.com/v1"
```

At last, I tried the configuration in the [blog post](https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper) and it says:

```
error: unable to recognize "mongodb.yaml": no matches for kind "MongoDBCommunity" in version "mongodb.com/v1"
```

Now I am so confused. 😞

**Comment by bznein** [comment]
Hi @pityonline,

the first article you linked is for the enterprise operator, while this repo is for the community operator.

Regarding your other two errors, can you open a new issue with a detailed summary of the steps you took?
By looking at the error message, it looks like you didn't create the proper CRDs, but we can help you better if you create a separate issue :)

**Comment by pityonline** [comment]
@bznein Thanks for your tips. I'll try to create the proper CRDs. If I still have the problem, I'll update here.

**Comment by pityonline** [comment]
@bznein It works properly after the proper CRDs are created. Thanks.
