### ISSUE TITLE
TLS support for MongoDB 4.4

### ISSUE THREAD

**Issue by rajavignesh** [mongodb/mongodb-kubernetes-operator#359]
**What did you do to encounter the bug?**
When deploying cluster with MongoDB version 4.4.2 and TLS enabled, SSLHandshakeFailed error found in "mongod" container log and "mongodb-agent" pod goes down after few minutes.

The same TLS certificate works fine in 4.2.12, facing issues when deploying with MongoDB version 4.4.
Deploying 4.4.2 without TLS works fine.

1. Enable TLS connection parameter in CR file with 3 replica set and version set to 4.4.2
2. Deploy CR file

**What did you expect?**
No error to be logged in the container log and mongodb-agent should be up and running

**What happened instead?**
SSLHandshakeFailed issue logged in mongod container log and mongodb-agent container goes down after few minutes.

**Operator Information**
 - Operator Version: 0.5.1
 - MongoDB Image used: 4.4.2

**Additional context**

**mongodb-agent log**
[2021-02-24T08:52:08.522+0000] [.info] [src/mongoclientservice/mongoclientservice.go:sendClientToRequesters:709] [08:52:08.522] Server at ea-mongodb-version-0.ea-mongodb-version-svc.mongodb.svc.cluster.local:27017 (local=false) is down.  Informing all client requests and disposing of client (0x0)
[2021-02-24T08:52:08.523+0000] [.info] [src/mongoctl/processctl.go:newStartProcessCmd:549] <ea-mongodb-version-0> [08:52:08.523] Running command mongod with args [-f /data/automation-mongod.conf]
[2021-02-24T08:52:09.151+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [08:52:09.151] clusterConfig unchanged

**mongod log**
{"t":{"$date":"2021-02-24T08:28:45.759+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn6","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"The server is configured to only allow SSL connections"},"remote":"10.42.5.169:39724","connectionId":6}}
{"t":{"$date":"2021-02-24T08:28:45.759+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"10.42.5.169:39724","connectionId":6,"connectionCount":0}}
{"t":{"$date":"2021-02-24T08:28:46.259+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.42.5.169:39726","connectionId":7,"connectionCount":1}}

**mongodb-agent container status**
- containerID: docker://f57605f5650d6247be60c82151b4e861c0e69bd65bd4a75cecb7c84217c68e0f
  image: e-ppsc-docker-local.docker.lowes.com/dev/operators/mongodb/mongodb-agent:10.27.0.6772-1
  imageID: docker-pullable://e-ppsc-docker-local.docker.lowes.com/dev/operators/mongodb/mongodb-agent@sha256:00bc0c60aa7eb11494d8ff170281983a0dfa3b4378459885b5eda3129b16d4b4
  lastState: {}
  name: mongodb-agent
  ready: false
  restartCount: 0
  started: true
  state:
    running:
      startedAt: "2021-02-24T08:25:20Z"

Deploying with MongoDB version 4.2.12, it was using mongo-go-driver v1.3.4 as in the container log below. Not sure mongo-go-driver 1.4 will be used for MongoDB version 4.4 as GO driver 1.3 is not compatible with MongoDB 4.4

https://docs.mongodb.com/drivers/go/

**4.2.12 version mongod log**
2021-02-24T09:11:50.489+0000 I  NETWORK  [conn3] received client metadata from 10.42.5.170:48542 conn3: { driver: { name: "mongo-go-driver", version: "v1.3.4" }, os: { type: "linux", architecture: "amd64" }, platform: "go1.14.7", application: { name: "MongoDB Automation Agent v10.27.0.6772 (git: b6ac87001d068f429c8443e4d21583570ca955bb)" } }
2021-02-24T09:11:50.490+0000 I  NETWORK  [listener] connection accepted from 10.42.5.170:48544 #4 (2 connections now open)

**Comment by antonlisovenko** [comment]
hi @rajavignesh 

thanks for your report! have created an internal ticket to track the issue

**Comment by antonlisovenko** [comment]
hi @rajavignesh 

We have a couple of e2e tests that check TLS with 4.4.0, one of them is: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/test/e2e/replica_set_tls/replica_set_tls_test.go

We tried 4.4.2 and that also worked... Can you please double-check your configuration - and maybe the test above will help you to verify the correctness of the configuration.

**Comment by mau21mau** [comment]
Can anyone helpme with that? I'm trying to deploy on GKE and getting the same error: 

```
{
code: 141
codeName: "SSLHandshakeFailed"
errmsg: "The server is configured to only allow SSL connections"
}
```

**Comment by kavaka123** [comment]
Hi, even I get the same error on mongoDB version "6.0.5". Can someone please help me?
