### ISSUE TITLE
Terraform plan and apply fails after the initial deployment of a ReplicaSet

### ISSUE THREAD

**Issue by dgdevops** [mongodb/mongodb-kubernetes-operator#372]
**Introduction:**
I have been testing the MongoDBCommunity Kubernetes Operator in the past weeks and initially I was trying to deploy the CRD and the ReplicaSet (+ its secret) simply with kubectl but to make the deployment and the resources stateful I decided to take the Terraform road and use the generic "kubernetes" provider to deploy the default resources and the "kubernetes-alpha" provider for the CRD and the MongoDBCommunity kind resources. I successfully deployed the CRD to my k8s cluster (terraform plan & terraform apply both succeeded), however when I deployed the replicaset (based on: [https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml](url)) using the "kubernetes-alpha" operator the initial terraform plan and apply succeeded and the ReplicaSet was created, however without any change in the code the next terraform plan and apply both failed with the following error:
`Error: rpc error: code = Unknown desc = update dry-run for 'mongodb/mongodb-qa' failed: Apply failed with 1 conflict: conflict with "manager" using mongodbcommunity.mongodb.com/v1: .spec.users`

To fix the error I removed the .spec.users section from the code by commenting it and tried the terraform plan and apply again and they failed again but due to a different error:
`Error: rpc error: code = Unknown desc = update dry-run for 'mongodb/mongodb-qa' failed: MongoDBCommunity.mongodbcommunity.mongodb.com "mongodb-qa" is invalid: spec.statefulSet.spec: Invalid value: "null": spec.statefulSet.spec in body must be of type object: "null"`

**What did you do to encounter the bug?**
1. Use Terraform 13.06 or 0.14.7 (example)
2. Use kubernetes-alpha provider for the ReplicaSet deployment (version 0.2.1 or 0.1.0) and configure it with the cluster settings
3. Convert the YAML file (mentioned above) to a kubernetes_manifest resource using tfk8s tool and save its output to a *.tf file
4. Execute "terraform plan" command and verify the resources to be created
5. Execute "terraform apply" and deploy the resources (2 in total - ReplicaSet and Secret)
6. Execute "terraform plan" again, it will fail due to the `.spec.users` error
7. Navigate to the ReplicaSet's tf file and comment out the .spec.users section
8. Execute "terraform plan" again, it will fail due to the `spec.statefulSet.spec` error

**What did you expect?**
Expected to have the terraform plan and apply to be successful after the initial deployment.

**What happened instead?**
The terraform plan and apply failed after the initial deployment of the ReplicaSet despite the fact that there were no code changes.

**Operator Information**
 - Operator Version: `0.5.1` `community`
 - MongoDB Image used: `4.2.6`

**Kubernetes Cluster Information**
 - Distribution: `GKE`
 - Version: `1.17.15`
 - Image Registry location (quay, or an internal registry): `quay`

If possible, please include:
Output of `kubectl describe crd mongodbcommunity.mongodbcommunity.mongodb.com` : https://jpst.it/2rptL
YAML definitions:
CRD: [https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml](url)
Operator deployment: [https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/manager/manager.yaml](url)
ReplicaSet: [https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml](url)
Logs: N/A

**Comment by rodrigovalin** [comment]
Hello @dgdevops 

Thanks for your report. Unfortunatelly, we don't have any experience with Terraform and I'm not familiar with the process of installing the Operator with it.

This is not something we can help you with. I will tag this issue as _help wanted_ to see if someone from the community can give us a hand.
