### ISSUE TITLE
Documentation: Operator watch namespace git repo files clarification

### ISSUE THREAD

**Issue by mblaubscher** [mongodb/mongodb-kubernetes-operator#379]
The documentation ( [https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#operator-in-different-namespace-than-resources](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#operator-in-different-namespace-than-resources) ) define role.yaml and role_bindings.yaml to apply from repository folder ./deploy/operator for each namespace to watch by operator.<br/>
`kubectl apply -f deploy/operator/role.yaml -n <namespace> && kubectl apply -f deploy/operator/role_binding.yaml -n <namespace>` <br/>
Are these yaml resources to be copied from ./deploy/clusterwide and modified or an omission by not included in ./deploy/operator ?

**Comment by rodrigovalin** [comment]
Hello @mblaubscher 

Thanks for reporting; the docs are updated. I've created a PR to update the docs pointing at where the new role, role_bindings and service_account yaml files are located.
