### ISSUE TITLE
Operator should create ServiceAccount and RoleBinding for managed pods

### ISSUE THREAD

**Issue by lchdev** [mongodb/mongodb-kubernetes-operator#380]
The latest documentation has clarified how to use the operator to watch multiple namespaces.
However, I think the way it operates is too tedious for the user, especially regarding the manual steps required to create a Role/RoleBinding/ServiceAccount in each and every watched namespace.

In my opinion, the Operator should create the proper RoleBinding/ServiceAccount in the target namespace when deploying a mongodbcommunity resource.

In addition, the ServiceAccount used by the pods should use a distinct role that has less privileges than the operator itself (I don't exactly know what API calls are made by the pods, but I guess it's only a subset of what the operator itself does).

**Comment by rodrigovalin** [comment]
Hello @lchdev 

Thanks for reporting this issue. This is something we would like to do of course.

In concrete terms:

1. The Operator uses a set of Roles which will include now Role & ServiceAccount creation capabilities
2. The database Pods will use a different set of roles, with less privileges than the Operator one
3. The Operator will create Roles & ServiceAccounts per deployed MongoDB resource.

I think this is a _good first issue_, for anyone willing to contribute!

**Comment by chatton** [comment]
Hi @lchdev 

For now we have decided not to have the operator create Role/RoleBinding/ServiceAccount in each and every watched namespace. We would like to follow the Principle of Least Privilege in this case, and supporting this scenario in both namespaced and clusterwide operators will lead to an increase in complexity of the operator itself.

However, as you mentioned there should be separate Service Accounts for the database and operator pods, you are right in saying that they do not require the same permissions.

We will improve the current documentation, and we hope to add some [templating solutions](https://github.com/mongodb/mongodb-kubernetes-operator/issues/193) to alleviate some of the manual steps involved in deploying a cluster wide operator, you are welcome to contribute!

**Comment by lchdev** [comment]
Hi !

Thanks for the feedback.

I'll try to have a look at it if I can.
