### ISSUE TITLE
Is it possible to install Ops Manager in Community Operators

### ISSUE THREAD

**Issue by paptimuslun** [mongodb/mongodb-kubernetes-operator#383]
I have just discovered that the Ops Manger can be used in Community Version
and just finished the installation by following the instructions in Github.
But I cannot find the installation guide for Ops Manager, and cannot install the manager under `mongodbcommunity.mongodb.com/v1`
I can only find the guide in enterprise operator, can anyone help?

**Comment by bznein** [comment]
Hi @paptimuslun, 

the Community operator does not support Ops Manager.

**Comment by paptimuslun** [comment]
Thanks, so the only method is expose SVC and use dB tools such as studio 3T to manage it?
