### ISSUE TITLE
Permissions still broken in 1.9.2

### ISSUE THREAD

**Issue by mrethers** [mongodb/mongodb-kubernetes-operator#398]
Following-up on #311, I've installed version 1.9.2 and still getting a permission error, though slightly different this time:

(combined from similar events): Readiness probe failed: panic: pods "opsmanager-db-0" is forbidden: User "system:serviceaccount:handshake:mongodb-enterprise-appdb" cannot patch resource "pods" in API group "" in the namespace "handshake" goroutine 1 [running]: main.isPodReady(0x8fc2b40, 0xa9c2f20, 0xa83a04e, 0x9, 0xa83a009, 0xf, 0xa83c016, 0x14, 0x8e30d7d, 0x38, ...) /build/readiness.go:71 +0x435 main.main() /build/readiness.go:223 +0x1f8

**Comment by bznein** [comment]
Hi @mrethers, 

This ticket relates to the Enterprise Operator, and this repo is for the Community Operator. 
For support on the Enterprise Operator, you can use the [Enterprise Repo](https://github.com/mongodb/mongodb-enterprise-kubernetes), refer to the [Enterprise Operator Docs](https://docs.mongodb.com/kubernetes-operator/master/) visit the [Support Center](https://support.mongodb.com/welcome). 
Hope that these links help you resolve your issue
