### ISSUE TITLE
Operator - All namespaces does not create sts

### ISSUE THREAD

**Issue by ghabarid** [mongodb/mongodb-kubernetes-operator#408]
**What did you do to encounter the bug?**
Changed the manager.yaml to 
 - name: WATCH_NAMESPACE
              value: "*"
- Installed the operator
Tried to create cr, 
k apply mongodb.com_v1_mongodbcommunity_cr.yaml

**What did you expect?**
A new cr, secret, cluster etc. is created

**What happened instead?**
All resource are created. Except the sts.

**Operator Information**
 - Operator Version: From the master branch

**Kubernetes Cluster Information**
Client Version: v1.19.3
Server Version: v1.17.4
PS: When I use the default value of WATCH_NAMESPACE, then things work fine.

**Comment by bznein** [comment]
Hi @ghabarid 

To be able to deploy the operator as a cluster-wide operator, you also need the two following steps (taken fron [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#operator-in-different-namespace-than-resources)):

```Run the following command to create cluster-wide roles and role-bindings in the default namespace:

kubectl apply -f deploy/clusterwide
For each namespace that you want the Operator to watch, run the following commands to deploy a Role, RoleBinding and ServiceAccount in that namespace:

kubectl apply -k config/rbac --namespace <my-namespace>```

I just tried it and was able to succesfully install the operator in a namespace, with clusterwide permission, and deploy replica sets in different namespaces.

Let me know if this works
