### ISSUE TITLE
Operator install hangs when using OLM single namespace install on multiple namespaces

### ISSUE THREAD

**Issue by ctrought** [mongodb/mongodb-kubernetes-operator#409]
**What did you do to encounter the bug?**
1. Install operator in namespace 1 using single namespace installation mode (operator within same namespace as mongo resources)
2. Installation completes successfully
3. Install operator in namespace 2 using single namespace installation mode
4. Operator install does not complete

**What did you expect?**
Single namespace install mode should be isolated and allow for multiple installations in a cluster. I am not sure if there is some conflict due to cluster roles (often single namespace installs should be scoped only to that namespace) but this has permissions for CSR's and ValidatingWebhookConfigurations.

**What happened instead?**
First operator install succeeds. Second does not.

**Operator Information**
 - Operator Version: mongodb-enterprise.v1.9.2

**Kubernetes Cluster Information**
 - Distribution: OpenShift
 - Version: 4.6.16

**Additional context**
Are there any security concerns providing the operator service account a cluster role with validating webhook configuration? As a non cluster admin user can login to this service account via token if using the same namespace installation mode, and then possibly create additional validating webhook configurations scoped at cluster level. Please let me know if I've missed something. I do realize a cluster wide install would absolve these potential concerns, and negate the need to install multiple times which may be the path I must follow if these issues cannot be resolved in single namespace mode.

![image](https://user-images.githubusercontent.com/65360454/113188437-0975e300-9228-11eb-9c30-c9e0e4241412.png)

![image](https://user-images.githubusercontent.com/65360454/113188521-24e0ee00-9228-11eb-955e-be60438126c8.png)

Thanks!

**Comment by bznein** [comment]
Hi @ctrought 

This ticket relates to the Enterprise Operator, and this repo is for the Community Operator. 
For support on the Enterprise Operator, you can use the [Enterprise Repo](https://github.com/mongodb/mongodb-enterprise-kubernetes), refer to the [Enterprise Operator Docs](https://docs.mongodb.com/kubernetes-operator/master/) visit the [Support Center](https://support.mongodb.com/welcome). 
Hope that these links help you resolve your issue
