### ISSUE TITLE
replica set could not be created successfully following readme 

### ISSUE THREAD

**Issue by suisuitj** [mongodb/mongodb-kubernetes-operator#41]
Hi 
Thanks for your sharing of mongodb operator. I'm learning how to build k8s operator by mongodb these days. I tried to create mongodb operator following readme insturctions. But it failed for :

[failure descripiton]
There is an error in operator while checking satus of replica set. When Reconcile is called again, and an error was returned by `r.client.CreateOrUpdate(&svc)`
` The service already exists... moving forward: Service "example-mongodb-svc" is invalid: metadata.resourceVersion: Invalid value: "": must be specified for an update`

![image](https://user-images.githubusercontent.com/23504932/81553964-8ef66780-93b8-11ea-91ba-b1bec1c6bc5b.png)

I tried to fix it by [Kubernetes Service invalid clusterIP or resourceVersion](https://www.timcosta.io/kubernetes-service-invalid-clusterip-or-resourceversion/). But it didn't work.

my k8s version:
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`
Any response/help will be much appreciated.

**Comment by chatton** [comment]
Hi @suisuitj, thanks for the report,

It looks like at the moment this particular error only occurs on a service **_update_**, but not on creation. The operator is incorrectly updating the service.

Meaning that even though there are errors in the logs this shouldn't effect your deployment unless you are manually making changes to the underlying kubernetes service created by the operator.

Tracking this internally as `CLOUDP-62351`

**Comment by suisuitj** [comment]
Thanks for your quick reply. 
Yes, from the log, the inital creation of stateful set is successful. The failure occurs during checking the status of `stateful set ready`.  

I am learning to debug/fix the failure.  Maybe my creation of stateful set failed during the checking phase of `stateful set ready`. I will report to you if have any progress.
