### ISSUE TITLE
Use 0.5.2tag number code. The mongodb-agent version is 10.29.0.6830-1, and there is no permission in the pod #

### ISSUE THREAD

**Issue by hayazan** [mongodb/mongodb-kubernetes-operator#416]
![image](https://user-images.githubusercontent.com/18796907/113372315-f5062780-939a-11eb-8c1d-867c96918e86.png)

I want to use the mongorestore command to import data to the mongo database, and it prompts no permission

![image](https://user-images.githubusercontent.com/18796907/113372416-431b2b00-939b-11eb-8031-96002dc5aed1.png)

**Comment by hayazan** [comment]
![Uploading image.png…]()

**Comment by hayazan** [comment]
I want to use the mongorestore command to import data to the mongo database, and it prompts no permission

**Comment by hayazan** [comment]
whoami: cannot find name for user ID 2000

**Comment by bznein** [comment]
Hi @hayazan,

with 0.5.2, the mongod container does not run as root anymore.
However, you can stil perform this operation by simply copying your `admin` folder in a different path (not `/`) in which the user has write permissions. For example, I managed to perform it by copying it into `/tmp` and then pointing `mongorestore` there.

Let me know if this works,
Nikolas

**Comment by hayazan** [comment]
> Hi @hayazan,
> 
> with 0.5.2, the mongod container does not run as root anymore.
> However, you can stil perform this operation by simply copying your `admin` folder in a different path (not `/`) in which the user has write permissions. For example, I managed to perform it by copying it into `/tmp` and then pointing `mongorestore` there.
> 
> Let me know if this works,
> Nikolas

it works
