### ISSUE TITLE
Deleting and recreating a MongoDBCommunity resource can get in a bad state

### ISSUE THREAD

**Issue by steeling** [mongodb/mongodb-kubernetes-operator#417]
Create a MongoDBCommunity resource, then delete it, then recreate it. The mongodb-agent fails with 

` [.info] [src/mongoclientservice/mongoclientservice.go:sendClientToRequesters:709] [18:55:34.867] Server at <service>:27017 (local=false) is down.  Informing all client requests and disposing of client (0x0)`

which inevitably crash-loops the whole thing

**Comment by bznein** [comment]
Hi @steeling,

thanks for your report. I tried several times to reproduce the issue but was not able to.
Can you provide more details on the exact steps you took to get this error together with logs?

Thanks!
