### ISSUE TITLE
 MongoDB Version Upgrade stuck in pending state.

### ISSUE THREAD

**Issue by yveskaufmann** [mongodb/mongodb-kubernetes-operator#421]
**What did you do to encounter the bug?**

I tried to upgrade from mongodb version 4.0.21 to 4.2.7 by modifying the mongodb.com/v1 resource
by following the steps described [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#upgrade-your-mongodb-resource-version-and-feature-compatibility-version).

I updated our mongodb.com/v1 resource like below.

```diff
  apiVersion: mongodb.com/v1
  kind: MongoDB
  metadata:
    name: parloa-mongodb
  spec:
    type: ReplicaSet
+  version: "4.2.7"
-  version: "4.0.21"
+  featureCompatibilityVersion: "4.0"
    ...
```  

Since then mongodb resource is in pending state, from our 6 parloa-mongodb pods was only the pod parloa-mongodb-0 upgraded to desired version. We also experienced that we lost the pods parloa-mongodb-2 and parloa-mongodb-3.   

![image](https://user-images.githubusercontent.com/1507553/114030944-27bc8e00-987b-11eb-8470-8542ada7e943.png)

The mongodb-agents of the not already upgraded pods are logging repeatedly the lines below. 

```
[2021-04-08T13:07:54.829-00] [.info] [cm/director/director.go:tracef:772] <parloa-mongodb-1> [13:07:54.829] 
Running step: 'WaitCanUpdate' of move 'ChangeVersion' because ['currentState.Up' = true]
[2021-04-08T13:07:54.829-00] [.info] [cm/director/director.go:planAndExecute:563] <parloa-mongodb-1> [13:07:54.829]
 Step=WaitCanUpdate as part of Move=ChangeVersion in plan failed : <parloa-mongodb-1> [13:07:54.829] Postcondition not yet met for step WaitCanUpdate because 
['currentState.CanUpdate' = false].
```   
What does it means that the agent says ['currentState.CanUpdate' = false] and how can it be resolved manually? 

**What did you expect?**
I expected that all our mongodb pods were upgraded to the version 4.2.7.

**What happened instead?**
Only the first pod were upgrade the rest of the mongodb pods were not updated, and the mongodb agents seems to be stuck in the upgrade process.

**Operator Information**
 - Operator Version:  0.3.0
 - MongoDB Image used (new) registry.hub.docker.com/library/mongo:4.2.7
 - MongoDB Image used (old) registry.hub.docker.com/library/mongo:4.0.21

**Kubernetes Cluster Information**
 - Distribution: gke
 - Version: v1.16.15-gke.7800

[parloa-mongodb-0-mongodb-agent.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6279032/parloa-mongodb-0-mongodb-agent.log)
[parloa-mongodb-1-mongodb-agent.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6279033/parloa-mongodb-1-mongodb-agent.log)
[operator.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6279039/operator.log)
[describe-mongodb.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6279056/describe-mongodb.txt)

**Comment by jamesbroadhead** [comment]
Could you please upgrade the Operator to the latest version & try again? 

Before upgrading, please take a look at the notes about CR changes in our Release Notes

**Comment by yveskaufmann** [comment]
I forgot to report that a previously performed automatic gke cluster upgrade solved the issue for us.
The upgrade re-created the Statefulset which apparently solved the issue in our cluster.

The problem seems not so easy reproducible we did the same in a different environment and didn't had this issue. 
When we encounter the problem again, we will try it with the latest operator version.   

For us the issue is solved for now, if you need any information to find the underlying issue don't hesitate to ask.  

Thank you for your support.

Yves
