### ISSUE TITLE
Readiness probe fail - mongodb-agent

### ISSUE THREAD

**Issue by daniloasfigueiredo** [mongodb/mongodb-kubernetes-operator#462]
Hello, we instaled the last version of operator with mongodb 4.4.0 and the mongod container it works well but the mongodb-agent returns healthcheck and readiness probe error and sometimes the primary instance goes down without any error in mongodb service.

**What did you do to encounter the bug?**
kubectl describe pod mongodb-1

Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               11m    default-scheduler        Successfully assigned shared-database/hml-mongodb-0 to aks-agentpool-86273347-vmss000003
  Normal   SuccessfulAttachVolume  10m    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-fcd8a6ee-7530-4ac8-94d8-6db378c29672"
  Normal   SuccessfulAttachVolume  10m    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-6fab6e41-18ab-42c2-9253-f618732f8110"
  Normal   Started                 10m    kubelet                  Started container mongod-posthook
  Normal   Pulled                  10m    kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2" in 150.293353ms
  Normal   Created                 10m    kubelet                  Created container mongod-posthook
  Normal   Pulling                 10m    kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Pulling                 10m    kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.3"
  Normal   Started                 10m    kubelet                  Started container mongodb-agent-readinessprobe
  Normal   Pulled                  10m    kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.3" in 218.797941ms
  Normal   Created                 10m    kubelet                  Created container mongodb-agent-readinessprobe
  Normal   Pulled                  10m    kubelet                  Container image "registry.hub.docker.com/library/mongo:4.4.0" already present on machine
  Normal   Created                 10m    kubelet                  Created container mongod
  Normal   Started                 10m    kubelet                  Started container mongod
  Normal   Pulling                 10m    kubelet                  Pulling image "quay.io/mongodb/mongodb-agent:10.29.0.6830-1"
  Normal   Pulled                  10m    kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-agent:10.29.0.6830-1" in 156.204479ms
  Normal   Created                 10m    kubelet                  Created container mongodb-agent
  Normal   Started                 10m    kubelet                  Started container mongodb-agent
  **Warning  Unhealthy               9m51s  kubelet                  Readiness probe failed:**

kubectl logs mongodb-1 -c mongod
2021-05-01T14:54:02.924Z        INFO    versionhook/main.go:34  Running version change post-start hook
2021-05-01T14:54:02.924Z        INFO    versionhook/main.go:41  Waiting for agent health status...
**2021-05-01T14:54:03.925Z        ERROR   versionhook/main.go:49  Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
        /go/cmd/versionhook/main.go:49
runtime.main
        /usr/local/go/src/runtime/proc.go:225
{"t":{"$date":"2021-05-01T14:54:08.955Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/var/log/mongodb-mms-automation/mongodb.log","newLogPath":"/var/log/mongodb-mms-automation/mongodb.log.2021-05-01T14-54-08"}}**

**Operator Information**
 - mongodb-kubernetes-operator:0.6.0
 - mongodb version 4.4.0

**Kubernetes Cluster Information**
 - Azure Kubernetes Service 
 - Version 1.19.7
 - Image Registry location (quay)

Config file attached.

[mongo-db-config.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6409953/mongo-db-config.txt)

**Comment by daniloasfigueiredo** [comment]
We instaled the last version of operator with mongodb 4.4.0, the mongod it works properly but the agent returns healthcheck error, we are using the defualt yaml configurations without any customization. 

Another problem is sometimes our primary instance is down and failover to secondary replicaset did not work, making our cluster in read only state.

**Comment by daniloasfigueiredo** [comment]
We tried to add "MANAGED_SECURITY_CONTEXT" in config files following reference below, but did not work 
https://github.com/mongodb/mongodb-kubernetes-operator/issues/58#issuecomment-642528641

**Comment by stefangraber** [comment]
We have the same issue with 4.4.4 on GKE 1.17.17

**Comment by daniloasfigueiredo** [comment]
As a workaround, we disabled the readiness probe from mongodb-agent.

**Comment by ties-s** [comment]
I also have this issue:
`ERROR	versionhook/main.go:49	Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory`

**Comment by chatton** [comment]
Hi @daniloasfigueiredo,

The error message you are referring to is actually a bit misleading, this message is coming from a **post-start hook**, not the readiness probe.

The post start hooks reads a file that is written by the `mongodb-agent` container and is only used during version upgrades. This file will not exist upon startup so it looks like we need to re-evaluate the severity of this log message, it is not actually an error in this case.

> As a workaround, we disabled the readiness probe from mongodb-agent.

This error message is not coming from the readiness probe, and disabling the readiness probe could potentially cause a lot of problems. The readiness probe relays the internal state of agents to ensure that pods are not erroneously terminated.

Does the StatefulSet eventually get into the running state? It is expected that there might be a few readiness probe health check failures while the mongodb replica set is being deployed.

**Comment by daniloasfigueiredo** [comment]
Hi @chatton, thanks for you response, makes sense and it's clear for me about these erros - mongod container log and mongodb-agent readiness probe. 

We have another problem that our primary instance goes down unexpectedly, but we upgrade mongodb to version 4.4.5 and replicaset count from 2 to 3 to enable automatic primary role promote and "failover", we will monitoring system logs and metrics in next days and get back with an feedback.

Thanks

**Comment by daniloasfigueiredo** [comment]
Hi @chatton, 

![image](https://user-images.githubusercontent.com/81190453/117592828-7d04ed00-b110-11eb-844e-ada7fa9772ef.png)

**Comment by daniloasfigueiredo** [comment]
Hi @chatton 

is it expected this amount of errors for mongodb-agent readiness probe?

![image](https://user-images.githubusercontent.com/81190453/117592911-be959800-b110-11eb-9940-a44ed9d580cf.png)

**Comment by daniloasfigueiredo** [comment]
@chatton, 

Sometimes our primary instance is goes down unexpectedly (without any mongodb service error and mongod and mongodb-agent container is up and running) and we did a pod restart, but the mongodb-agent don't start properly with readiness probe error x4, x10, x30, x100, etc...

![image](https://user-images.githubusercontent.com/81190453/117844397-070a9e00-b256-11eb-9ee5-33d87ea49e29.png)

![image](https://user-images.githubusercontent.com/81190453/117844724-4c2ed000-b256-11eb-8a73-3a3dd9688ace.png)

is there any fixes for this issue?

**Comment by adthonb** [comment]
I have the same problem with the readiness probe. The error comes from `mongod` container. The StatefulSet doesn't get a running state and only one container running in the pod.

**Operator Information**
- mongodb-kubernetes-operator 0.6.0
- mongodb 4.2.14

**Kubernetes Cluster Information**
- My Own Kube Cluster
- Version 1.20.2

**Comment by chatton** [comment]
Hi @daniloasfigueiredo 

Would you be able to provide some more logs to help us diagnose it?

The logs of the readiness probe can be found at `/var/log/mongodb-mms-automation/readiness.log` in the agent pods. 

The readiness probe indicates whether or not the agent has reached the desired state, so some number of readiness probe failures when performing operations such as initial rs config, scaling, version changes etc are expected.

But it does look like something is stuck, could you provide the output of `kubectl describe` on the underlying stateful set as well as the logs for the `mongod` and `mongodb-agent` containers?

If you suspect it is a memory/cpu error you could try reducing the resource limits/requests.

You can specify these for the MongoDBCommunity resource by adding the following to the spec if you have not done so already.

```yaml
statefulSet:
  spec:
    template:
      spec:
        containers:
          - name: mongod
            resources:
              limits:
                cpu: "0.2"
                memory: 250M
              requests:
                cpu: "0.2"
                memory: 200M
          - name: mongodb-agent
            resources:
              limits:
                cpu: "0.2"
                memory: 250M
              requests:
                cpu: "0.2"
                memory: 200M
```

**Comment by chatton** [comment]
@adthonb what sort of errors can you see in the statefulset?

Are you running a cluster locally? If so you could try lowering the resources as mentioned above.

**Comment by adthonb** [comment]
@chatton Thank you for pay attention to my problem. I can run it successfully now.

This below this my error. Sometimes it make me confuse and don't sure what's the problem.

```
ERROR   versionhook/main.go:49  Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
        /go/cmd/versionhook/main.go:49
runtime.main
        /usr/local/go/src/runtime/proc.go:225
```

**Comment by chatton** [comment]
Hi @adthonb , sorry about the confusion - this is actually just a bad choice of log severity that we need to address.

It's fine if this file does not exist when initially creating the resource. There are certain situations in which this file not existing should be an actual error. This is likely not an actual error.

Can you confirm that your mongodb replica set is up and running?

**Comment by adthonb** [comment]
@chatton Yes, I confirm it running successfully.

![image](https://user-images.githubusercontent.com/18661601/117972398-4cfa5b80-b355-11eb-96d2-ac0ec9949be5.png)

**Comment by chatton** [comment]
@adthonb  okay good to hear, in this case you can dis-regard this error message and we will re-assess the severity level.

**Comment by daniloasfigueiredo** [comment]
Hi @chatton, follow attached the requested files and logs.

[mongodb-agent logs.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6505072/mongodb-agent.logs.txt)
[mongod-logs.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6505073/mongod-logs.txt)
![pod_status](https://user-images.githubusercontent.com/81190453/118739785-a9132300-b820-11eb-9fec-ffa14e039713.PNG)
![describe pod](https://user-images.githubusercontent.com/81190453/118739787-a9abb980-b820-11eb-9e00-4ebdd12d2426.PNG)
[kubectl describe statefulset.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6505081/kubectl.describe.statefulset.txt)

**Comment by zeemba** [comment]
> I have the same problem with the readiness probe. The error comes from `mongod` container. The StatefulSet doesn't get a running state and only one container running in the pod.
> 
> **Operator Information**
> 
> * mongodb-kubernetes-operator 0.6.0
> * mongodb 4.2.14
> 
> **Kubernetes Cluster Information**
> 
> * My Own Kube Cluster
> * Version 1.20.2

Hello, did you ever find a resolution to this issue? I'm experiencing the same problem .

**Comment by dongluyang** [comment]
> > I have the same problem with the readiness probe. The error comes from `mongod` container. The StatefulSet doesn't get a running state and only one container running in the pod.
> > **Operator Information**
> > 
> > * mongodb-kubernetes-operator 0.6.0
> > * mongodb 4.2.14
> > 
> > **Kubernetes Cluster Information**
> > 
> > * My Own Kube Cluster
> > * Version 1.20.2
> 
> Hello, did you ever find a resolution to this issue? I'm experiencing the same problem. I've also reduced the resource request and limits to no avail. @chatton

have you resolve above problem, i meet the same issue with you
