### ISSUE TITLE
Cannot list resource "mongodbcommunity" in API group "mongodbcommunity.mongodb.com" at the cluster scope

### ISSUE THREAD

**Issue by sangnguyen7** [mongodb/mongodb-kubernetes-operator#467]
**What did you do to encounter the bug?**
I got this issue "cannot list resource "mongodbcommunity" in API group "mongodbcommunity.mongodb.com" at the cluster scope" as long as I deploy the operator on a namespace difference than the default namespace..

Here is the log I'm getting from a mongodb-kubernetes-operator pod where I deployed on a namespace named "mongodb-operator":

"
E0506 16:49:11.053079 11 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.MongoDBCommunity: failed to list *v1.MongoDBCommunity: mongodbcommunity.mongodbcommunity.mongodb.com is forbidden: User "system:serviceaccount:mongodb-operator:mongodb-kubernetes-operator" cannot list resource "mongodbcommunity" in API group "mongodbcommunity.mongodb.com" at the cluster scope
"

**What did you expect?**
Should work with any namespace as the guide stating.. Deployed the operator to a specified namespace and watch all other namespaces

**What happened instead?**
Only works when deploying on the default namespace

**Screenshots**

**Operator Information**
 - Operator Version: 0.60
 quay.io/mongodb/mongodb-kubernetes-operator:0.6.0
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version: 1.20.5
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by rodrigovalin** [comment]
Hi @sangnguyen7,

For the operator to be able to watch resources in a different namespace, you should follow the steps in "[Operator in Different Namespace Than Resources](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#operator-in-different-namespace-than-resources)".

This way, the `mongodb-kubernetes-operator` Role will be able to watch over resources in any Namespace, no matter in which namespace the operator was installed.
