### ISSUE TITLE
Ability to connect to MongoDB via SRV DNS Record

### ISSUE THREAD

**Issue by jmcollin78** [mongodb/mongodb-kubernetes-operator#468]
Original title: Impossible to connect to MongoDB via SRV DNS Record

**What did you do to encounter the bug?**
Install MongoDB via mongodb-kubernetes-operator

**What did you expect?**
A client application should be able to connect to the MongoDB Cluster via an connection string using SRV DNS record like:

`mongo mongodb+srv://mongodb-svc.mongodb-ns.svc.cluster.local`

**What happened instead?**
The connection failed with the error:

`DNSHostNotFound: Failed to look up service "_mongodb._tcp.mongodb-svc.mongodb-ns.svc.cluster.local"`

Note that the connection works well when N

**Operator Information**
```
{
  "mongodb-kubernetes-operator": "0.6.0",
  "version-upgrade-hook": "1.0.2",
  "readiness-probe": "1.0.3",
  "mongodb-agent": {
      "version": "10.29.0.6830-1",
      "tools_version": "100.2.0"
  }
}
```
 - MongoDB 4.4.5

**Kubernetes Cluster Information**
 - Distribution :  GKE
 - Version : 1.18.16-gke.2100
 - Image Registry location: quay

If possible, please include:
 - `kubectl describe mongodb-svc` output:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-05-06T10:45:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":27017,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:publishNotReadyAddresses: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: manager
    operation: Update
    time: "2021-05-06T10:45:06Z"
  name: mongodb-core-svc
  namespace: mongodb-int-ns
  resourceVersion: "771103"
  selfLink: /api/v1/namespaces/mongodb-int-ns/services/mongodb-core-svc
  uid: 6b2c7aff-2d3d-4120-acad-9ec28b54c667
spec:
  clusterIP: None
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  publishNotReadyAddresses: true
  selector:
    app: mongodb-core-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Note that traditional connection (NOT using SRV record) like: mongodb://<host>.<sv>.<ns>.svc.cluster.local works fine. But we must declare all mongodb cluster member in the connection string.

**Comment by jamesbroadhead** [comment]
@jmcollin78 glad you managed to figure this out! 

We know about this issue - but also believe that setting the port like this has compatibility problems with istio. We have some work planned to investigate and try to find something which works for both use-cases. 

related: #146

**Comment by jmcollin78** [comment]
Glad to here that. In my opinion, SRV records is a MUST have. Istio is more a nice to have.

Moreover, I don't see why this could cause an issue on Istio to name the port.

**Comment by theyough** [comment]
Any update ?

**Comment by irajdeep** [comment]
Hello, @jmcollin78 We have added the support for SRV connection string now, could you please verify if the issue still persists?

**Comment by jmcollin78** [comment]
Hello, glad to here that, but I will not be able to test this. Maybe in july or august I will have some time.

**Comment by irajdeep** [comment]
Cool, I am closing this, for now, feel free to reopen if the issue still persists.
