### ISSUE TITLE
Operator crashes whem there is more ReplicaSet memebers than replicaSetHorizons entries

### ISSUE THREAD

**Issue by caiorcferreira** [mongodb/mongodb-kubernetes-operator#488]
**What did you do to encounter the bug?**
1. Deploy a ReplicaSet with 3 members and the corresponding `replicaSetHorizons` with 3 entries.
2. Scale the ReplicaSet to 4 members, **without** adding a new `replicaSetHorizons` entry.
3. The operator will crash due to a handled panic:
```
panic: runtime error: index out of range [3] with length 3 [recovered]
	panic: runtime error: index out of range [3] with length 3
```

**What did you expect?**
If the configuration cannot be performed with a size mismatch between members and `replicaSetHorizons`, then an error should be produced instead of allowing slice access without checks.

Also, if a panic occurs for any reason this should not crash the container. The entry point of the container should use a [recover](https://blog.golang.org/defer-panic-and-recover) to log the panic and keep the operator up.

**What happened instead?**
The container crashes and does not recover unless the configuration is fixed.

**Operator Information**
 - Operator Version: v0.6.0
 - MongoDB Image used: v4.2.13

**Additional context**
I believe that the code responsible for it is this:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/05b67abc9a175ed405cad05445839fbfbb55f029/pkg/automationconfig/automation_config_builder.go#L238

**Comment by caiorcferreira** [comment]
Hi @chatton, if you could help me with a direction because I'm not familiar with the internals of automation configuration what should be the best outcome in this case? Knowing that I can make a PR to solve this.

**Comment by chatton** [comment]
Hi @caiorcferreira, 

you're right this is definitely cause of the panic. In the case of `members != len(replicaSetHorizons)`, this is not a validation that is possible via the CRD, so I think it could be a good option to validate the state of the resource at the beginning of the Reconciliation loop. 

Perhaps [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/dcddbfb1a19e3fa65454e3963a8741d2446590c5/controllers/replica_set_controller.go#L129), this will put the resource into the `Failed` state when an invalid spec is provided.


If we allow a mismatch to be sent to the automation config, this will fail validation by the MongoDB Agents and the pods will never become ready.

**Comment by caiorcferreira** [comment]
Nice! I will work on this as soon as I can, thanks for the support 😄
