### ISSUE TITLE
caConfigMapRef configuring cert

### ISSUE THREAD

**Issue by flmmartins** [mongodb/mongodb-kubernetes-operator#519]
Hello, 

I would like to generate the certificate using cert-manager and letsencrypt. Currently cert-manager only support the creation of the secret which contains the .tls and .key but not the ca.crt itself.

Is it possible to omit caConfigMapRef from the configuration?

Also is it possible to have an integration with cert-manager and mongo operator? Tks!

**Comment by rodrigovalin** [comment]
Hello @flmmartins thanks for reaching us.

The `caConfigMapRef` attribute is optional, so can leave it out if you don't need it. You need to make sure that the certificates you want to trust are part of the validation chain in the Pods and you should be good to go.

If you are using your own (not-publicily recognizable) CA authority, you'll have to provide this CA for MongoDB to work, somehow. If this is the case, I recommend you to create the ConfigMap yourself for MongoDB to trust your custom Certification Authority.

With regards to cert-manager and letsencrypt, I know that letsencrypt will not generate certificates for hosts that can't be reached from the public Internet. I know people have used it to generate certificates for their Kubernetes Pods, but I'm not sure it is straightforward or much less, "automatable" experience.

We have operator + cert-manager integration in our plans, but unfortunately, that will not happen yet.
