### ISSUE TITLE
Linting errors due to not implementing principle of least privilege

### ISSUE THREAD

**Issue by afzalch** [mongodb/mongodb-kubernetes-operator#538]
**What did you do to encounter the bug?**
I installed Mongodb operator - run lint on cluster and get errors:

**What did you expect?**
No linting errors as linter expects that containers implement the principle of least privilege to minimize security risks by dropping ALL capabilities at securityContext.capabilities.drop before adding back only the privileges that are necessary for the container.

**What happened instead?**
Errors due to not implementing principle of least privilege

**Logs**
```
[ERROR] scanned-deployment-staging-mongodb-kubernetes-operator.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-job-staging-staging-mongodb-certconvert.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-job-staging-staging-mongodb-ready.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: "ALL" not found in spec.template.spec.containers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: "ALL" not found in spec.template.spec.containers[1].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: "ALL" not found in spec.template.spec.initContainers[0].securityContext.capabilities.drop (ContainerHasDropAll)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: "ALL" not found in spec.template.spec.initContainers[1].securityContext.capabilities.drop (ContainerHasDropAll)
```

**Operator Information**
 - Operator Version
 - MongoDB Image used: Image ID: quay.io/mongodb/mongodb-kubernetes-operator@sha256:3ea8935ce639ef43ca1aa25ff244719a163d6e081f398674eb678f8bd475bdfa

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by afzalch** [comment]
This is still an error that I would like to see addressed if possible.

**Comment by priyolahiri** [comment]
Which linter are you using? Are you running it on the cluster with something like https://github.com/digitalocean/clusterlint?
