### ISSUE TITLE
Linting error due to there being undefined product id, product metric and product name annotations

### ISSUE THREAD

**Issue by afzalch** [mongodb/mongodb-kubernetes-operator#540]
**What did you do to encounter the bug?**
I installed Mongodb operator - run lint on cluster and get errors:

**What did you expect?**
No linting errors

**What happened instead?**
Errors due to lack of product id, product metric, product name annotations

**Logs**
```
[ERROR] deployment-staging-mongodb-kubernetes-operator.yaml: metering annotations ["productID", "productMetric" "productName"] not found under spec.template.metadata.annotations
```

**Operator Information**
 - Operator Version
 - MongoDB Image used: Image ID: quay.io/mongodb/mongodb-kubernetes-operator@sha256:3ea8935ce639ef43ca1aa25ff244719a163d6e081f398674eb678f8bd475bdfa

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by afzalch** [comment]
This is still an issue that I would like to see get resolved in the future if possible.

**Comment by rodrigovalin** [comment]
Hi @afzalch

Do you think you could provide the required annotations as a pull-request? I'm not really sure I understand the need of this, and why your linter is failing. I'm also not familiar with what is the meaning of `productID` and `productMetric`.
