### ISSUE TITLE
lint error: ContainerDefinesResources

### ISSUE THREAD

**Issue by RyshMan** [mongodb/mongodb-kubernetes-operator#543]
Hello team
When I am run lit against resources on my cluster I faced with this error: (ContainerDefinesResources)

Each container of a Pod must specify one or more of the following:

spec.containers[].resources.limits.cpu
spec.containers[].resources.limits.memory
spec.containers[].resources.requests.cpu
spec.containers[].resources.requests.memory

[ERROR] scanned-deployment-staging-mongodb-kubernetes-operator.yaml: spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-deployment-staging-mongodb-kubernetes-operator.yaml: spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-mongodb-kubernetes-operator-8678bf444b-jvtvk.yaml: spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-mongodb-kubernetes-operator-8678bf444b-jvtvk.yaml: spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: neither spec.initContainers[0].resources.limits.cpu nor spec.initContainers[0].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: neither spec.initContainers[1].resources.limits.cpu nor spec.initContainers[1].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: spec.initContainers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: spec.initContainers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: spec.initContainers[1].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-pod-staging-staging-mongodb-0.yaml: spec.initContainers[1].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-replicaset-staging-mongodb-kubernetes-operator-75ffd5bd68.yaml: spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-replicaset-staging-mongodb-kubernetes-operator-75ffd5bd68.yaml: spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-replicaset-staging-mongodb-kubernetes-operator-8678bf444b.yaml: spec.template.spec.containers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-replicaset-staging-mongodb-kubernetes-operator-8678bf444b.yaml: spec.template.spec.containers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: neither spec.template.spec.initContainers[0].resources.limits.cpu nor spec.template.spec.initContainers[0].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: neither spec.template.spec.initContainers[1].resources.limits.cpu nor spec.template.spec.initContainers[1].resources.requests.cpu is defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: spec.template.spec.initContainers[0].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: spec.template.spec.initContainers[0].resources.requests.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: spec.template.spec.initContainers[1].resources.limits.memory not defined (ContainerDefinesResources)
[ERROR] scanned-statefulset-staging-staging-mongodb.yaml: spec.template.spec.initContainers[1].resources.requests.memory not defined (ContainerDefinesResources)

**What did you do to encounter the bug?**

**What did you expect?**

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by FlorentinaSimlinger** [comment]
Unfortunately we weren't able to reproduce the error. Would you be able to share more information, including the yaml file(s) and linter used? Thanks.

**Comment by irajdeep** [comment]
I am closing this ticket now, feel free to re-open if the issue still persists.
