### ISSUE TITLE
[[Feature Request]] Mongodbcommunity CR version field to support ImageDigest/SHA for AirGap scenarios

### ISSUE THREAD

**Issue by joshho** [mongodb/mongodb-kubernetes-operator#563]
Currently the Mongodb Operator uses the Mongodbcommunity CR.version field as a tag.
In AirGapped Openshift environments, if a ImageDigest/SHA256 is used, the Openshift layer (via ImageContentSourcePolicy) can redirect/mirror from a private Docker registry using the SHA.

Also, [there is a RFE open against Openshift to control ImageContentSourcePolicy](https://bugzilla.redhat.com/show_bug.cgi?id=1921049)

**Comment by chatton** [comment]
Hi @joshho,

if you need to override fields in the underlying StatefulSet (such as image/tag)

you can use the statefulSet overridel.

See [this example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml) and update it is required.

Let me know if this solves your issue.

**Comment by chatton** [comment]
Hi @joshho, closing this issue assuming that the provided solution works for you, if you are still having a problem feel free to re-open!
