### ISSUE TITLE
Mongodb Agent-Openshift Issue

### ISSUE THREAD

**Issue by mtarekfouad** [mongodb/mongodb-kubernetes-operator#572]
We deployed MongoDB Kubernetes Operator and the opsmanager on openshift 4.7 and they are working fine but once we are trying to deploy the mongoDB pod we are getting below error

{“logType”:“agent-launcher-script”,“contents”:“Using Kubernetes CA file”}
{“logType”:“agent-launcher-script”,“contents”:“Created symlink: /data/journal → /journal”}
{“logType”:“agent-launcher-script”,“contents”:“Downloading a Mongodb Agent from https://ops-manager-dev-svc-mtx-db-dev.apps.com}
{“logType”:“agent-launcher-script”,“contents”:“Error while downloading the Mongodb agent”}
{“logType”:“agent-launcher-script”,“contents”:”* Trying 10.27.137.46…"}
{“logType”:“agent-launcher-script”,“contents”:"* TCP_NODELAY set"}
{“logType”:“agent-launcher-script”,“contents”:"* Connected to ops-manager-dev-svc-mtx-db-dev.apps.com (10.27.137.46) port 443 (#0)"}
{“logType”:“agent-launcher-script”,“contents”:"* ALPN, offering h2"}
{“logType”:“agent-launcher-script”,“contents”:"* ALPN, offering http/1.1"}
{“logType”:“agent-launcher-script”,“contents”:"* successfully set certificate verify locations:"}
{“logType”:“agent-launcher-script”,“contents”:"* CAfile: /etc/pki/tls/certs/ca-bundle.crt"}
{“logType”:“agent-launcher-script”,“contents”:" CApath: none"}
{“logType”:“agent-launcher-script”,“contents”:"} [5 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (OUT), TLS handshake, Client hello (1):"}
{“logType”:“agent-launcher-script”,“contents”:"} [512 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (IN), TLS handshake, Server hello (2):"}
{“logType”:“agent-launcher-script”,“contents”:"{ [122 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (IN), TLS handshake, [no content] (0):"}
{“logType”:“agent-launcher-script”,“contents”:"{ [1 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):"}
{“logType”:“agent-launcher-script”,“contents”:"{ [10 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (IN), TLS handshake, [no content] (0):"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (IN), TLS handshake, Certificate (11):"}
{“logType”:“agent-launcher-script”,“contents”:"{ [1416 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* TLSv1.3 (OUT), TLS alert, unknown CA (560):"}
{“logType”:“agent-launcher-script”,“contents”:"} [2 bytes data]"}
{“logType”:“agent-launcher-script”,“contents”:"* SSL certificate problem: self signed certificate"}
{“logType”:“agent-launcher-script”,“contents”:"* Closing connection 0"}

**Comment by mtarekfouad** [comment]
MongoDB Yaml : 
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mtx-mongodb-dev
spec:
  version: 4.4.6
  opsManager:
    configMapRef:
      name: mtx-dev-project-config
  credentials: mtx-dev-orga-api-key
  
  type: Standalone
  persistent: true
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongo-mtx-dev-pvc
  terminationGracePeriodSeconds: 10

**Comment by bznein** [comment]
Hi @mtarekfouad, this repository is for the Community Operator while your problem is related to the Enterprise Operator. 

Please follow the instructions you find here: https://github.com/mongodb/mongodb-enterprise-kubernetes#support-feature-requests-and-community
