### ISSUE TITLE
File System Snapshot

### ISSUE THREAD

**Issue by rajavignesh** [mongodb/mongodb-kubernetes-operator#573]
**What did you do to encounter the bug?**
MongoDB Version: 4.2.11
Take a snapshot of the persistence volume using Cohesity or Velero and restore the PVC
Pods will go in Error or CrashLoopBackOff state
Note: even copying the files from pod to VM, facing the same issue

**What did you expect?**
Pod should come up using the data files that have been restored

**What happened instead?**
Facing checksum issue (attached the complete error description)

**Screenshots**
Attached the error 

**Operator Information**
 - Operator Version: 0.5.0
 - MongoDB Image used: 4.2.11

[file_snapshot_error.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6663500/file_snapshot_error.txt)

**Comment by bznein** [comment]
Hi @rajavignesh 

The usage of tools such as Cohesity or Velero is not something we support at the moment. 
The suggested approach to save and restore data is through the use of `mongodump` and `mongorestore`.

The enterprise operator supports more advanced backup configurations.
