### ISSUE TITLE
Insufficient CPU error without any reason

### ISSUE THREAD

**Issue by 205g0** [mongodb/mongodb-kubernetes-operator#578]
**What did you do to encounter the bug?**
- Create 4 instances w/2vCPU and 4GB RAM, install k3s with three servers and one worker on them
- Install a 3-Mongo-replica-set
- `kubectl delete node <one node with a mongo replica>`

**What did you expect?**
Mongo schedules the lost replica to one of the left nodes where a Mongo replica set hasn't been installed yet.

**What happened instead?**
I got:

```
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  4m20s  default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 2 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  4m19s  default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 2 node(s) had volume node affinity conflict.
```

But my cluster should have sufficient resources:
```
CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
274m         13%    2030Mi          51%
132m         6%     2049Mi          52%
192m         9%     1760Mi          44%
```
Every node has `2,000m` max CPU and and the one replica is already on the first node running and the other one on the last one, so the new one could have been scheduled on the second node.

**Operator Information**
 - Operator 0.6.1

**Kubernetes Cluster Information**
 - Distribution k3s
 - Version v1.21.1+k3s1

**Comment by priyolahiri** [comment]
Could not reproduce with three worker node K3S Cluster and switching off 1 worker node for a 3 member replica set.
