### ISSUE TITLE
CustomResourceDefinition needs upgrade from v1beta1 to v1 to work with k8s version 1.19.11

### ISSUE THREAD

**Issue by raffimohammed** [mongodb/mongodb-kubernetes-operator#606]
**What did you do to encounter the bug?**
While running ' kubectl apply -f config/crd
/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml' 

kubectlWarning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/mongodbcommunity.mongodbcommunity.mongodb.com created

1. git clone https://github.com/mongodb/mongodb-kubernetes-operator.git
2. cd mongodb-kubernetes-operator
3. kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
4. The pod operator and the rolebinding were not getting created. The crd/mongodbcomm
unity.mongodbcommunity.mongodb.com did get created. 

**What did you expect?**
A. Upgrade the CustomResourceDefinition for the operator from apiVersion v1beta1 to v1. The yaml does need changes. The 'validation' in v1beta1 is now 'schema' in v1. 

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version: 0.6.0
 - MongoDB Image used: 

**Kubernetes Cluster Information**
 - Distribution: Kubernetes services on Azure. 
 ( kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1 )
 - Version: 1.19.11
 - Image Registry location (quay, or an internal registry)
 

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by irajdeep** [comment]
Hi, @raffimohammed  thanks for reporting this -- we are aware of this issue. 
We are hoping to update the CRDs to v1 in the next 2 weeks.

**Comment by irajdeep** [comment]
Fixed as part of this: https://github.com/mongodb/mongodb-kubernetes-operator/pull/617
