### ISSUE TITLE
Unable to store logs and data in a single persistence volume

### ISSUE THREAD

**Issue by bmv-ce** [mongodb/mongodb-kubernetes-operator#608]
**What did you do to encounter the bug?**
Use MongoDB Kubernetes Community Operator to create a Replica Set with the following settings:

> ...
> podSpec:
>    persistence:
>      single:
>        storage: 3Gi
>        storageClass: "glusterfs-storage"
> ...
> statefulSet:
>...

**What did you expect?**
A single PVC is created for each Pod running a replica set member

**What happened instead?**
The setting get ignored, and two PVCs are created for each pod: one for "data-volume", and another for "logs-volume"

**Operator Information**
 - Community latest
 - 4.4.0

**Question**
Is it only possible to have a single PVC in enterprise version of the operator?

**Comment by bznein** [comment]
Hi @bmv-ce,

the specification you are using is for the enterprise operator. The Community one does not have `podSpec` fields. 

Please note that from the latest release (0.6.2) the logs will be automatically sent to `stdout` (this can be overridden with `spec.additionalMongodConfig`. The logs pvc will still be created as a backward-compatible change.

**Comment by bmv-ce** [comment]
Thanks @bznein, understood!
Does it mean that there is no way to get rid of the second PVC for logs when using the Community version of the operator?

**Comment by bznein** [comment]
Hi @bmv-ce,

currently you are correct, it is not possible. We might in a near release do that, but this will break the existing statefulset and require a restart of the pods. I will create an internal ticket to track this.

**Comment by bmv-ce** [comment]
@bznein 

Thanks, could you please also let me know how that "logs-volume" is mounted by default?
What would be the log directory when I SSH to the mongod pod? And what happens, if the "logs-volume" max size is reached?

**Comment by bznein** [comment]
Hi @bmv-ce, sorry for the delay in the reply.

the logs-volume is by default mounted to 

`/var/log/mongodb-mms-automation`

Unfortunately, is the max size is reached, `mongodb` will go down, see #570.

If you are running an older operator which has this issue, you should periodically free up space in the folder.

Hope this helps!

**Comment by bmv-ce** [comment]
Hi @bznein, thanks for the reply.

As I understand, this ticket addressed the issue, and now it is possible to not log into file, but only stdout: https://github.com/mongodb/mongodb-kubernetes-operator/pull/584

Does this setting work for the Community version of the operator? And if yes, what happens to the "logs-volume" PVC? You mentioned above, that there is no way to get rid of it currently, and it doesn't make sense if "stdout" is used.

**Comment by bznein** [comment]
> As I understand, this ticket addressed the issue, and now it is possible to not log into file, but only stdout: #584

It is still possible to log onto a file, by specifying a setting in `spec.additionalMongodConfig`. I can provide an example if you need it. However, the default now is to log to stdout.



> Does this setting work for the Community version of the operator? 
Yes, it is actually part of the release notes of version 0.6.2 (https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.6.2)

> And if yes, what happens to the "logs-volume" PVC? You mentioned above, that there is no way to get rid of it currently, and it doesn't make sense if "stdout" is used.

You are right, it doesn't. But it is not possible to change `volumeClaimTemplate` on an existing StatefulSet and so we decided, to ensure backward compatibility without requiring users to restart their deployment, to keep it for now. It will get removed in a future release.
There is a way to "hack" it by manually creating a Persistent Volume that is based on hostpath or localpath, if you want to avoid creating a dynamic PV that will not be used. I will merge an example that tests this soon

**Comment by bmv-ce** [comment]
Awesome, thanks for the answers, and looking forward to seeing some examples.

**Comment by bmv-ce** [comment]
One last question, probably: now I understood that `mongod` logs can be output to `stdout`, but there are also `healthstatus` directory and `readiness.log` file in the mounted `/var/log/mongodb-mms-automation` directory.
I can see that `readiness.log` grows constantly in size as well. Is there a setting to disable it somehow (similar to mongod output)? Otherwise, the persistence volume will run out of space anyway...

**Comment by bznein** [comment]
Hi @bmv-ce,

the `healthstatus` file will not be an issue as it gets overwritten each time.

The `readiness.log` file might pose the same problem as the mongod logs; we aware of this and will put up a fix soon.

**Comment by stanxing** [comment]
currently, has any idea to disable logs-volume pvc?  It 's not necessary to create mongodb

**Comment by jicki** [comment]
has any idea to disable logs-volume pvc ?

**Comment by omaratros** [comment]
While Issue #608 of the Mongodb operator repository may be considered stale, **it is important to keep in mind that this issue may still be relevant and important to users. As a result, it is important to handle the issue, either by addressing it or by closing it with an appropriate explanation.**

Furthermore, closing the issue with an appropriate explanation can help to manage user expectations and avoid any potential confusion or frustration. Users who may have been following the issue may appreciate an update on its status, even if it has been closed.

Overall, while it may be tempting to close stale issues without addressing them, it is important to consider the impact on the user community and handle the issue appropriately.
