### ISSUE TITLE
no matches for kind "MongoDBCommunity" in version "MongoDBCommunity.mongodb.com/v1" 

### ISSUE THREAD

**Issue by nesspll** [mongodb/mongodb-kubernetes-operator#614]
no matches for kind "MongoDBCommunity" in version "MongoDBCommunity.mongodb.com/v1"

OR

no matches for kind "MongoDBCommunity" in version "mongodb.com/v1"

`apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: mongodb`

`apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: mongodb`

Both result in the same error.

SOURCE: [https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper](https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper)

**Comment by bznein** [comment]
Hi @nesspll,

did you install the CRDs as pointed out as prerequisites for point 1 in the installation?
I realize now we don't explicitly tell users how to do it, but you can by running

`kubectl apply -f ttps://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml`
