### ISSUE TITLE
The CustomResourceDefinition "mongodbcommunity.mongodbcommunity.mongodb.com" is invalid

### ISSUE THREAD

**Issue by MieleVL** [mongodb/mongodb-kubernetes-operator#621]
**What did you do to encounter the bug?**
Deploying the `mongodbcommunity.mongodb.com_mongodbcommunity.yaml` does not work anymore since the latest update.

Running the following cmd returns an error:
```shell
kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
```
Error:
The CustomResourceDefinition "mongodbcommunity.mongodbcommunity.mongodb.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

**What did you expect?**
A successful deployment

**What happened instead?**
An error was thrown

**Kubernetes Cluster Information**
Using Autopilot on Google Cloud Kubernetes

**Comment by irajdeep** [comment]
Hi @MieleVL We have upgraded the CRD to version `v1`. Could you try adding the following to the `spec` in the CRD YAML.

```
preserveUnknownFields: false
```
and apply again. It is documented here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/RELEASE_NOTES.md#kubernetes-operator

**Comment by MieleVL** [comment]
@irajdeep ah ok, didn't notice this was documented. Will give that a try, thx!
