### ISSUE TITLE
Uneven experience with k8s 1.21.1 (?)

### ISSUE THREAD

**Issue by bodomic2** [mongodb/mongodb-kubernetes-operator#630]
Sorry for not making a bug report but more of a discussion post but there are things that do not just go fine and I have to re-create the whole cluster again and again (it's great that I have this opportunity).
My experience with this software is so far followed by these warnings and issues;
1.
```
# kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/mongodbcommunity.mongodbcommunity.mongodb.com created
```
I understand this is just a warning but it looks like there is a v1 version in place so maybe I'm using sorta outdated setup for 1.21.1 and maybe it brings the issues.

2.
```
kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace default
```
_(again I have to notice that api version 'v1' is used here instead of v1beta1 in `config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml`)_
Example set has been created just fine but I've found no way to remove it. Even with advise from @fireba11 to remove the resource so that related pods will go away, I've got all those pods recreated again even after resource had been deleted.

3. I've created a custom replica set definition (closely copied from documentation and comments here though).
As I already said, I've did it plenty of times already ;) and the best result I've reached with custom statefulSet to use real world memory allowances would be:
```
# kubectl get mongodbcommunity.mongodbcommunity.mongodb.com/mongodb-replica-set
NAME                  PHASE     VERSION
mongodb-replica-set   Pending

# kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-kubernetes-operator-7c6c4d8cff-gmjgv   1/1     Running   0          15m
mongodb-replica-set-0                          2/2     Running   0          8m40s
mongodb-replica-set-1                          2/2     Running   0          7m28s
mongodb-replica-set-2                          1/2     Running   0          6m5s

# kubectl logs mongodb-replica-set-2 mongodb-agent
...

[2021-07-11T12:40:28.634+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <mongodb-replica-set-2> [12:40:28.634] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {lastVersion 57} {nextVersion 57}]}] and upsert=true on local.clustermanager
[2021-07-11T12:40:38.270+0000] [.info] [main/components/agent.go:Iterate:848] [12:40:38.270] All 1 Mongo processes are in goal state.
[2021-07-11T12:40:38.270+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [12:40:38.270] clusterConfig unchanged
[2021-07-11T12:40:38.677+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1577] [12:40:38.677] Testing auth with username __system db=local to mongodb-replica-set-2.mongodb-replica-set-svc.default.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false
[2021-07-11T12:40:38.701+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:1985] <mongodb-replica-set-2> [12:40:38.700] Able to successfully auth to mongodb-replica-set-2.mongodb-replica-set-svc.default.svc.cluster.local:27017 (local=false) using desired auth key
[2021-07-11T12:40:38.781+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <mongodb-replica-set-2> [12:40:38.781] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 57}]}] and upsert=true on local.clustermanager
[2021-07-11T12:40:38.782+0000] [.info] [src/director/director.go:planAndExecute:537] <mongodb-replica-set-2> [12:40:38.782] In Goal State for clusterConfig version: 57
[2021-07-11T12:40:38.784+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <mongodb-replica-set-2> [12:40:38.784] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {lastVersion 57} {nextVersion 57}]}] and upsert=true on local.clustermanager
```

4. As I'm repeating my experience while writing this post, I have to report that just 5-6 minutes later all the rest of agents are crashed:
```
# kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-kubernetes-operator-7c6c4d8cff-gmjgv   1/1     Running   0          20m
mongodb-replica-set-0                          1/2     Running   0          13m
mongodb-replica-set-1                          1/2     Running   0          12m
mongodb-replica-set-2                          1/2     Running   0          11m
```

Replica set is out of order, still.
I'm adding the resource description I've used to launch this set. If I create it without statefulSet.spec part, I get it up and running as in point 2 above but there is no production use of MongoDB running on 500 Mb of RAM (_please consider revising this in default CRDs_).
```
# cat mongodb-community.yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    <some valid users and roles here>
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 200m
                  memory: 400M
                limits:
                  cpu: 1000m
                  memory: 500M
            - name: "mongod"
              resources:
                requests:
                  cpu: 2000m
                  memory: 2000M
                limits:
                  cpu: 4000m
                  memory: 4000M
```
Version information:
```
Containers:
  mongodb-kubernetes-operator:
    Container ID:  containerd://8401da467efd26639f12dc61d8a46eae957477fe07d23376b49e5af9eb90fa7d
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.7.0
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator@sha256:e19ae43539521f0350fb71684757dc535fc989deb75f3789cd84b782489eda80
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/entrypoint
    State:          Running
      Started:      Mon, 12 Jul 2021 11:15:31 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1100m
      memory:  1Gi
    Requests:
      cpu:     500m
      memory:  200Mi
    Environment:
      WATCH_NAMESPACE:             default (v1:metadata.namespace)
      POD_NAME:                    mongodb-kubernetes-operator-957dff59d-kqmzh (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:11.0.5.6963-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      READINESS_PROBE_IMAGE:       quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4
      MONGODB_IMAGE:               mongo
      MONGODB_REPO_URL:            docker.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kcz2v (ro)
```

**Comment by bodomic2** [comment]
P.S.: Actually, on my very first try I've got another mixed experience - my set got running on default settings, it's actually got `.status.mongoUri` set and I have connected to it several times until I realized it's running on 500 Mb RAM and dying from OOM killer on any meaningful actions.
All three agents were in crashed state all the way back then though, and `mongodbcommunity.mongodbcommunity.mongodb.com` resource was in the same `Pending` state.

**Comment by bodomic2** [comment]
P.P.S: on the recent try that I'm describing here I've managed to connect to replica set by borrowing mongodb uri from previous tries. It looks quite usable, however, I'm not sure it makes any sense to try running production on semi-failed k8s deployment...

**Comment by irajdeep** [comment]
Hi @bodomic2 , regarding points 1 and 2, we have now migrated the CRDs to version `v1` -- so you shouldn't be seeing those warnings anymore.

Regarding the agents crashing -- could you please share the detailed agent logs? Thanks.

**Comment by bodomic2** [comment]
Hi @irajdeep, sorry for delay, I've been offline for a while.
As agent keeps crashing, it seems that `kubectl logs` only dumps latest logs, so here they are.
[agent.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6836597/agent.log)

I have to state again that this or another side-effect causes replicaSet degradation to a single pod (with agent crashing in it, the same). This log is from this degraded case with one pod - I need to allocate several hours to recreate cludter and get the updated logs from 'one of three pods'.
Hope this helps.

**Comment by bodomic2** [comment]
I've recreated the cluster and got two agent logs 
- [agent-2.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6840992/agent-2.log) - log of crashing agent in replica-2 pod (while two other agents are considered as alive).
- [agent-3.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6840994/agent-3.log) - log of crashing agent in replica-0 pod (after all three agents are considered dead)

**Comment by irajdeep** [comment]
@bodomic2 nothing stand out to me in the agent logs, could you please share the outout of `kubectl describe mdbc` i.e the CR spec you're trying to deploy. Thanks

**Comment by bodomic2** [comment]
@irajdeep, here you are: 
[mdbc.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6846936/mdbc.txt)

**Comment by irajdeep** [comment]
Hi @bodomic2 I couldn't reproduce this issue against the latest operator version and CRDs, we fixed some issues with the CRD in last few weeks. Could you please try again against the latest CRD in master and the operator release and check if the issue still persists.

**Comment by bodomic2** [comment]
hi, thanks for the update, I've let down the whole mongodb k8s idea since then.
I'll keep this noted, I believe this very issue can be closed for now.
