### ISSUE TITLE
Latest master fails to create CRD

### ISSUE THREAD

**Issue by bodomic2** [mongodb/mongodb-kubernetes-operator#631]
**What did you do to encounter the bug?**
I've pulled the latest master (e8c4d350c6738dcc6452234707aa2f498b0ee339) and just can not create a resource.
The saddest part I've already removed the previous `mongodbcommunity.mongodb.com_mongodbcommunity`

**What did you expect?**
I've expected the resource will be recreated from scratch.

**What happened instead?**
```
# kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
The CustomResourceDefinition "mongodbcommunity.mongodbcommunity.mongodb.com" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

**Operator Information**
 - master at e8c4d350c6738dcc6452234707aa2f498b0ee339
 
Sorry, not sure how to collect all the rest of data, will spend time on it if there is no easy way out.

PS: the reason I've pulled the latest master was the hope to get SCRAM-SHA-1 authentication working.
If there is no easy way to get `master` version working at all and with SCRAM-SHA-1 particularl, please advise.

**Comment by bznein** [comment]
Hi @bodomic2, please see #621 for the first part of your question

Regarding tour PS, we released yesterday 0.6.3 which supports SCRAM-SHA-1

**Comment by bodomic2** [comment]
Oh thanks for rapid answer!
It seems to fix everything for me, let me recreate everything and try to connect again.

**Comment by bodomic2** [comment]
I'm not sure why it is so but it has definitely changed just now.
```
# kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml --namespace default
customresourcedefinition.apiextensions.k8s.io/mongodbcommunity.mongodbcommunity.mongodb.com configured
# kubectl apply -k config/rbac/ --namespace default
serviceaccount/mongodb-kubernetes-operator unchanged
rolebinding.rbac.authorization.k8s.io/mongodb-kubernetes-operator unchanged
error: the namespace from the provided object "mongodb" does not match the namespace "default". You must pass '--namespace=mongodb' to perform this operation.
# kubectl apply -k config/rbac/ --namespace=mongodb
Error from server (NotFound): error when creating "config/rbac/": namespaces "mongodb" not found
Error from server (NotFound): error when creating "config/rbac/": namespaces "mongodb" not found
Error from server (NotFound): error when creating "config/rbac/": namespaces "mongodb" not found
```

**Comment by bznein** [comment]
You are trying to create a resource that specifies namespace `mongodb` but you are in another namespace.

Try to create the namespace

`kubectl create ns mongodb` 

And then move there

`kubectl namespace mongodb`

And then try again

**Comment by bodomic2** [comment]
ok, sorry, I'm a bit overwhelmed by all these entities, I've changed namespace in those two files (`config/rbac/role.yaml` and `config/manager/manager.yaml`) to get going (I don't need an extra NS at the moment).
Thanks again.

**Comment by bodomic2** [comment]
I'm sorry again, @bznein, can ou help me a bit more?
After recreation I have got only one pod running (with Agent permanently crashing) - I've seen this many times while working with this operator but I don't know how to debug or fix the issue apart from deleting the cluster altogether and starting from scratch.
I've tried to apply patch and to delete a pod (as the end of `Upgrading` section says - without any luck.
Is that something known too?

**Comment by bznein** [comment]
Hi @bodomic2,

if the agent crashes, it might be worth to file a new issue with detailed logs.

`kubectl logs <name-of-the-crashing-pod>` might help!

**Comment by bodomic2** [comment]
@bznein - I've already filed it here - https://github.com/mongodb/mongodb-kubernetes-operator/issues/630
I've just recreated cluster from the scratch on latest master and repeated https://github.com/mongodb/mongodb-kubernetes-operator/issues/630 wholly
