### ISSUE TITLE
namespace error on upgrade to 0.7.0

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#639]
**What did you do to encounter the bug?**
1. have 0.6.0 running
2. try to upgrade to 0.7.0

**What did you expect?**

**What happened instead?**
$ kubectl create -f config/manager/manager.yaml --namespace mongo
error: the namespace from the provided object "mongodb" does not match the namespace "mongo". You must pass '--namespace=mongodb' to perform this operation.

my guess is there are some changes expecting the namespace to be named mongodb ..
upgrade to 0.6.2 worked

**Operator Information**
 - Operator Version 0.6.0
 - MongoDB Image used 4.2.10

**Kubernetes Information**
 - Version 1.19.7 (server), 1.21.2 (client)

**Comment by irajdeep** [comment]
Hi @fireba11 , it looks like we have hardcoded the `namespace` in `manager.yaml` in latest release -- (we should probably remove it), meanwhile you can remove the `namespace` key from here - https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/manager/manager.yaml#L9 and it should work.
