### ISSUE TITLE
Configure resources requests & limits

### ISSUE THREAD

**Issue by ManAnRuck** [mongodb/mongodb-kubernetes-operator#66]
How to configure the resource limits for the mongodb pods?

I didn't find any documentation about this.

**Comment by chatton** [comment]
Hi @ManAnRuck

This feature is currently being worked on. Configuration of the underlying StatefulSet should be possible within the next few weeks.

**Comment by ledux** [comment]
Hi @chatton 
Will the configuration of the StatefulSet include the size of the PersistentVolume?

**Comment by chatton** [comment]
Hi, it should be possible to configure anything that is in the statefulset podTemplateSpec as of operator v0.1.1 see [this example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml)

**Comment by chatton** [comment]
configuring requests/limits is no supported via custom stateful set configuration. See https://github.com/mongodb/mongodb-kubernetes-operator/pull/157 for a small example.
