### ISSUE TITLE
Readiness probe failing continuously with operator 0.7.0

### ISSUE THREAD

**Issue by lchdev** [mongodb/mongodb-kubernetes-operator#668]
When deploying MongoDB with the latest release of the operator (0.7.0), the readiness probe generates a continuous stream of "Unhealthy pods" warning events on each of the mongodb pods:

```
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  4m8s (x52352 over 18d)  kubelet  Readiness probe failed:
```

This does not seem to impact the mongodb-agent container (nor the pod) behavior (still marked `ready` by kubernetes), so I guess that only some of the checks are failing, not all of them. 

There does not seem to be anything special in the mongodb/mongodb-agent logs, and the readiness check itself does not seem to provide any additional information, so I opened a shell in the container and executed the probe manually. What I found is that some executions took more that 1 second (the configured timeout), thus failing the readiness check:

```
I have no name!@mongodb-cluster-0:/$ while true ; do time /opt/scripts/readinessprobe ; sleep 10 ; done

real    0m0.181s
user    0m0.034s
sys     0m0.005s

real    0m0.348s
user    0m0.054s
sys     0m0.016s

real    0m0.532s
user    0m0.037s
sys     0m0.016s

real    0m1.244s
user    0m0.039s
sys     0m0.014s

real    0m0.715s
user    0m0.035s
sys     0m0.012s

real    0m0.520s
user    0m0.032s
sys     0m0.008s

real    0m0.088s
user    0m0.027s
sys     0m0.005s

real    0m0.660s
user    0m0.031s
sys     0m0.011s

real    0m0.422s
user    0m0.042s
sys     0m0.011s

real    0m1.281s
user    0m0.050s
sys     0m0.011s
```

It seems thus that:
* the readiness check is taking too long at some moments, but why ?
* the configured timeout on the readiness probe is too small t account for the check

Since the failure count of the readiness probe is set to 40 (!), it does not impact the global behavior, but it still generates a LOT of undesirable warning events...

**Comment by chatton** [comment]
Hi @lchdev, thanks for the report.

The log for the readiness probe itself can be found at `/var/log/mongodb-mms-automation/readiness.log` in the agent pods. Would you be able to provide them?

**Comment by lchdev** [comment]
Hi,

The log file only contains the same line repeated every 10 seconds:

```I have no name!@mongodb-cluster-0:/$ tail /var/log/mongodb-mms-automation/readiness.log
2021-08-17T08:09:29.151Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:09:39.415Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:09:49.493Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:10:39.784Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:10:50.001Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:10:59.172Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:11:19.438Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:11:49.497Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:11:59.977Z        INFO    build/main.go:75        Agent has reached goal state
2021-08-17T08:12:09.396Z        INFO    build/main.go:75        Agent has reached goal state
```

What kind of checks does the readiness probe execute ? 

Please note that there is close to no load at all on that mongodb cluster, thus I don't really explain why it would be slow every now and then.

**Comment by chatton** [comment]
Hi @lchdev 

The readiness probe parses some state written by the agent to determine if the deployment has reached the desired state.

This file is located at `/healthstatus/agent-health-status.json` in the agent pods. Would you be able to provide this file along with the agent logs? (`mongodb-agent` container)

I can take a look and hopefully help you figure this out.

If the logs are reporting the agent has reached goal state I would not be expecting the failures you are encountering!

**Comment by lchdev** [comment]
I found a few occurrences of this error in the readiness probe logs:

```
2021-07-26T09:14:09.025Z	ERROR	build/main.go:65	There was problem checking the health status: Get "https://10.3.0.1:443/api/v1/namespaces/uat/secrets/mongodb-cluster-config": dial tcp 10.3.0.1:443: connect: connection refused
main.isPodReady
	/build/main.go:65
main.main
	/build/main.go:220
runtime.main
	/usr/local/go/src/runtime/proc.go:204
```

This means that the readiness probe is actually calling the Kubernetes API during its check. If the API is a bit too slow to answer (i.e. takes more than 1s), the readiness probe would report a failure...

We known that our API server can be a bit slow, so it would be sufficient to explain the recurring failures. Is there by chance any mean to configure the readiness probe timeout, such that we can accommodate to a somewhat slow API server ?

**Comment by chatton** [comment]
Hi @lchdev,

Yes you are absolutely right, the readiness probe does make a few Kubernetes API calls to determine readiness. 

It is possible to adjust the readiness timeouts using the StatefulSet spec override in the MongoDBCommunity CR. You can use it like this

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              readinessProbe:
                timeoutSeconds: 3

```

(I've ommited every unrelated field)

You should be able to modify any underlying StatefulSet field using this mechanism.

**Comment by lchdev** [comment]
Thanks, this is much better now :)

Out of curiosity, is there any reason to have the readinessprobe configured with a low timeout (1s) but high failureThreshold (40) ?

**Comment by chatton** [comment]
Hi @lchdev,

There is no reason specifically for these values, but you do make a good point. We should re-assess these values. Since your original issue was resolved, I'm closing this issue.
