### ISSUE TITLE
security context not changing

### ISSUE THREAD

**Issue by Pantelispanka** [mongodb/mongodb-kubernetes-operator#673]
Cannot change security context of the containers

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.1"
  featureCompatibilityVersion: "4.4"
  security:
    authentication:
      modes: ["SCRAM"]
      ignoreUnknownUsers: False
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: jaqpot
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          labels:
            app: mongodb
      containers:
        - name: mongod
          securityContext:
            runAsNonRoot: false
            privileged: true
            runAsUser: 0
            fsGroup: 0
        - name: mongodb-agent
          securityContext:
            runAsNonRoot: false
            privileged: true
            runAsUser: 0
            fsGroup: 0

Operator continues to spin up containers with fsGroup 2000 and Non Root and gives me

Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied goroutine 1

**Comment by bartlomiejwulff** [comment]
Hi @Pantelispanka 

I think you are interpreting the function of security scope wrong. Try to use these statements. Pod scope 


```
securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
```

And in the container scope:

```
securityContext:
    runAsNonRoot: true
```

**Comment by Pantelispanka** [comment]
Hi @bartlomiejwulff !!

Thanks a lot!! Really helpful. 
 I was really confused, now t seems that the agent and the mongod container have access to the pv but i continue to get an error for the readiness probe. 

Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied goroutine 1 [running]: main.main() /build/main.go:216 +0x2df

**Comment by bartlomiejwulff** [comment]
Try to delete fsGroup

**Comment by Pantelispanka** [comment]
Worked! 
Scopes worked! Thanks for pointing out that. 
Some things to notice. 

Readiness probe fails many times before creating the replica set and that gives you the sense of a failure. 
Also the directory mounted was not empty and that created a lot of errors. Had to create the replica set on an empty directory and dumb / restore the data.

**Comment by dragonknight88** [comment]
@Pantelispanka @bartlomiejwulff what was the needed update to deployments? I'm facing a similar issue where the container is unable to access the PV.
