### ISSUE TITLE
Authorization Question

### ISSUE THREAD

**Issue by Pantelispanka** [mongodb/mongodb-kubernetes-operator#677]
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.1"
  featureCompatibilityVersion: "4.4"
  security:
    authentication:
      modes: ["SCRAM"]
      ignoreUnknownUsers: true
  users:
    - name: *
      db: admin
      passwordSecretRef:
        name: *
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          labels:
            app: mongodb
        spec:
          containers:
            - name: mongod
              securityContext:
                runAsNonRoot: false
                privileged: true
                runAsUser: 0
            - name: mongodb-agent
              securityContext:
                runAsNonRoot: false
                privileged: true
                runAsUser: 0
          initContainers:
            - name: mongod-posthook
              securityContext:
                runAsNonRoot: false
                privileged: true
                runAsUser: 0
            - name: mongodb-agent-readinessprobe
              securityContext:
                runAsNonRoot: false
                privileged: true
                runAsUser: 0
---
apiVersion: v1
kind: Secret
metadata:
  name: *
  namespace: mongodb
type: Opaque
stringData:
  password: *

Thats the Yamls for the deployment. 
Is there a way to disable auth? The db is not on production therefore not much security needed.

**Comment by chatton** [comment]
Hi @Pantelispanka, there is currently no way to disable auth. By default SCRAM is required to be enabled.
