### ISSUE TITLE
mongodb-agent binary for Power (ppc64le) arch

### ISSUE THREAD

**Issue by snehlatamohite** [mongodb/mongodb-kubernetes-operator#712]
Hello Team,

We were trying to build mongodb-kubernetes-operator locally on power platform.  

All operator images got built on Power. However x86 mongodb-agent binary is getting installed in mongodb-agent-dev:latest image.  Dockerfile - (https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/scripts/dev/templates/agent/Dockerfile.builder#L8)

In previous conversation over ticket https://github.com/mongodb/mongodb-kubernetes-operator/issues/226#issuecomment-720351457 
I have found link for mongodb-agent for Power https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-manager-10.19.0.6566-1.ppc64e1.ubuntu1604.deb

I tried to download it using wget https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-manager-10.19.0.6566-1.ppc64e1.ubuntu1604.deb  but its failing with **forbidden error.** 
```

Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.20.173
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.20.173|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-09-09 05:53:50 ERROR 403: Forbidden.
```

Can someone please guide me how to download and install mongodb-agent on Power Platform? Please comment/advice on how to resolve issue.

Thanks,
Snehlata Mohite.

**Comment by krishvoor** [comment]
@theburi we cannot seem to pull in the binary from this [location]( https://cloud.mongodb.com/download/agent/automation/mongodb-mms-automation-agent-manager-10.19.0.6566-1.ppc64e1.ubuntu1604.deb ) onto ppc64le

Do we have to import any public keys for the repo/deb-package to be accessible?
Can you kindly shed some light on this?

**Comment by snehlatamohite** [comment]
Able to download binary for power using dockerfile. Thanks.  

ADD https://mciuploads.s3.amazonaws.com/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod/mongodb-mms-automation-agent-11.0.5.6963-1.rhel7_ppc64le.tar.gz /data/mongodb-agent.tar.gz
Downloading [==================================================>]  15.39MB/15.39MB
 ---> 663fc95ed96a
