### ISSUE TITLE
Cannot scale down cluster to zero nodes

### ISSUE THREAD

**Issue by olfway** [mongodb/mongodb-kubernetes-operator#731]
**What did you do to encounter the bug?**
I tried to temporary scale down cluster with spec.members: 0

**What did you expect?**
Operator should terminate all mongodb pods

**What happened instead?**
Got an error in operator logs:
> ERROR    controllers/mongodb_status_options.go:84    error validating new Spec: number of arbiters specified (0) is greater or equal than the number of members in the replicaset (0). At least one member must not be an arbiter

**Operator Information**
 - mongodb-kubernetes-operator:0.7.0

**Comment by priyolahiri** [comment]
We currently don't allow scale down of MongoDB nodes to 0. We might consider allowing this in the future.

**Comment by nick4fake** [comment]
@priyolahiri any news on this?
