### ISSUE TITLE
Using mongo:4.2 fails creating replica set

### ISSUE THREAD

**Issue by TechnicalMercenary** [mongodb/mongodb-kubernetes-operator#737]
**What did you do to encounter the bug?**
For our mongo in dev regions we prefer not to lock mongo to a 0.0.x version.  Helps keep us up to date.

I tried  the following 

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo-deployment
spec:
  members: 3
  type: ReplicaSet
  version: "4.2"
```

**What did you expect?**
I had hoped that the mongo pods would be created running the latest version of mongo 4.2.x but I got an error instead.

Well,  the first pod was created successfully, but the replica set will not initialize.

It did try to use `Container image "docker.io/mongo:4.2" already present on machine` so that's good.

**What happened instead?**

I did get one running mongo pod but there's a failure.

```
2021-09-29T17:55:19.398Z	ERROR	controllers/mongodb_status_options.go:84	Error deploying MongoDB ReplicaSet: failed to ensure AutomationConfig: could not build automation config: can't build the automation config: can't compute semver version from previous FeatureCompatibilityVersion
github.com/mongodb/mongodb-kubernetes-operator/controllers.messageOption.ApplyOption
	/workspace/controllers/mongodb_status_options.go:84
github.com/mongodb/mongodb-kubernetes-operator/pkg/util/status.Update
	/workspace/pkg/util/status/status.go:25
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:187
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```
**Screenshots**

**Operator Information**
 - quay.io/mongodb/mongodb-kubernetes-operator:0.7.0
 - mongo:4.2

**Kubernetes Cluster Information**
 - EKS
 - 1.18
 - quay /. docker hub
 -

**Comment by priyolahiri** [comment]
We currently don't support running the latest version with a tag like 4.2. You need to enter a minor version. We will consider this use case in the future.
