### ISSUE TITLE
Provide metrics to monitoring the operator

### ISSUE THREAD

**Issue by Starefossen** [mongodb/mongodb-kubernetes-operator#748]
What kind of metrics is it possible to get out from the operator currently?
Would it be possible to instrument the operator (not the databases) with Prometheus metrics for better monitoring?

**Comment by Starefossen** [comment]
Any updates on this @priyolahiri? How can I follow the tickets in JIRA?

**Comment by priyolahiri** [comment]
We don't have a public roadmap for the Community Operator currently. You can track the major issues on Github Issues. We are starting to work on Prometheus Metrics this quarter and should have an update soon.

**Comment by laurivosandi** [comment]
Any updates on this?
