### ISSUE TITLE
resize data volume and update configuration

### ISSUE THREAD

**Issue by suppix** [mongodb/mongodb-kubernetes-operator#756]
Hello. Thanks for this k8s operator. 

Could you please let me know how I can resize volume for Mongodb: 
```
 message: 'Error deploying MongoDB ReplicaSet: error creating/updating StatefulSet:
    error creating/updating StatefulSet: StatefulSet.apps "mongodb" is invalid: spec:
    Forbidden: updates to statefulset spec for fields other than ''replicas'', ''template'',
    and ''updateStrategy'' are forbidden'
```

My config:
```
    volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 60G
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10G
```
I have changed storage 50G -> 60G 

And the same question about config:
I have added this config:
```
additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```
But operator, haven't updated Mongodb config file.

**Comment by bznein** [comment]
Hi @suppix,

I'm closing this issue as this is not a feature we support and the provided documentation should help you achieve what you are trying to do. Feel free to reopen the issue if that's not helping.

**Comment by nick4fake** [comment]
@bznein In the previous ticket you have suggested to open a feature request for this page:
https://www.mongodb.com/docs/kubernetes-operator/current/tutorial/resize-pv-storage/

To be automated. Shouldn't this ticket stay opened? This is a quite important task that is extremely tedious to do by hand

**Comment by nick4fake** [comment]
Btw, looking through instruction there is no "/var/lib/mongodb-mms-automation/mongodb-linux-*" folder inside mongodb pod
