### ISSUE TITLE
Configure the mongo image itself

### ISSUE THREAD

**Issue by lokm01** [mongodb/mongodb-kubernetes-operator#77]
Is there currently any way to specify which mongo image will be pulled? 

It would be great if we could specify images in ECR for example.

**Comment by chatton** [comment]
Hi @lokm01 

There isn't any way to configure this at the moment, this is something that we should be implementing pretty soon. I'm creating a ticket to track this internally.

**Comment by lexual** [comment]
Any progress on this since last update? :) 🤞

**Comment by TannerBragg** [comment]
@chatton This is important.  Please consider implementing soon.  :]
