### ISSUE TITLE
Possbile to configure electionTimeoutMillis in replicaset?

### ISSUE THREAD

**Issue by stanltam** [mongodb/mongodb-kubernetes-operator#771]
**What did you do to encounter the bug?**
Possible to configure electionTimeoutMillis in replica set CRD? Not able to find any documents mentioned that. 

**What did you expect?**
Possible to configure electionTimeoutMillis in replica set CRD? Not able to find any documents mentioned that. 

**What happened instead?**
Possible to configure electionTimeoutMillis in replica set CRD? Not able to find any documents mentioned that.

**Comment by bznein** [comment]
Hello @stanltam 

This is not possible at the moment but it would be a good feature to have. There is work being done at https://github.com/mongodb/mongodb-kubernetes-operator/pull/806 that will move toward being able to implement it. If you are interested in contributing feel free to comment and we can provide some guidance around it
