### ISSUE TITLE
Mongodb community operator Helm chart is Broken

### ISSUE THREAD

**Issue by fractal1977** [mongodb/mongodb-kubernetes-operator#776]
The Mongodb operator community Helm Chart is no more available on our catalog because the new community-operator chart is missing from the index (only enterprise is listed here)

**Comment by rodrigovalin** [comment]
Thanks for reporting,

As stated here https://github.com/mongodb/helm-charts/issues/70 the Chart was renamed to `mongodb-kubernetes-operator`; _that was a mistake on our part_.

The Chart will be renamed back to `community-operator` as you expect, in the next few days.

**Comment by rodrigovalin** [comment]
Hello @fractal1977

The Community Chart was renamed back to `community-operator`. Once again, thanks for reporting.
