### ISSUE TITLE
secrets that contains users' connection strings and credentials still not created.

### ISSUE THREAD

**Issue by daniel-tasnadi-epam** [mongodb/mongodb-kubernetes-operator#819]
**What did you do to encounter the bug?**
1. Start Ubuntu 20.04 LTS
2. Start minikube 
3. Follow the [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set)

**What did you expect?**
 The mentioned ` <metadata.name>-<auth-db>-<username>` secret should be created.
 
 **What happened instead?**
The secret not created at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/91332442/146228082-18ef23de-aeb2-4737-9c54-956154bbcc5f.png)

**Operator Information**
 - Operator Version: latest master
 - MongoDB Image used: 4.6.2
 
 **Kubernetes Cluster Information**
 - Version: 1.22.4
 
After cloning the latest master and reaching this part in the [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set). The mentioned ` <metadata.name>-<auth-db>-<username>` secret is not created at all.

I saw the previous [Issue](https://github.com/mongodb/mongodb-kubernetes-operator/issues/711), where it stated it fixed in that version. However, the issue is present/introduced since than in master.

**Comment by daniel-tasnadi-epam** [comment]
Hi @bznein, sure.
Please find the logs below:

`2021-12-15T15:01:48.037Z INFO controllers/replica_set_controller.go:132 Reconciling MongoDB {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.037Z DEBUG controllers/replica_set_controller.go:134 Validating MongoDB.Spec {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.037Z DEBUG controllers/replica_set_controller.go:143 Ensuring the service exists {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.042Z INFO controllers/replica_set_controller.go:390 The service already exists... moving forward: services "example-mongodb-svc" already exists {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.042Z INFO controllers/replica_set_controller.go:308 Creating/Updating AutomationConfig {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.054Z DEBUG scram/scram.go:165 Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2021-12-15T15:01:48.054Z DEBUG controllers/replica_set_controller.go:429 AutomationConfigMembersThisReconciliation {"mdb.AutomationConfigMembersThisReconciliation()": 3}
2021-12-15T15:01:48.054Z DEBUG controllers/replica_set_controller.go:331 Waiting for agents to reach version 3 {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.054Z INFO agent/agent_readiness.go:52 All 3 Agents have reached Goal state {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.054Z INFO controllers/replica_set_controller.go:288 Creating/Updating StatefulSet {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.059Z DEBUG controllers/replica_set_controller.go:298 Ensuring StatefulSet is ready, with type: RollingUpdate {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.059Z DEBUG controllers/replica_set_controller.go:202 Resetting StatefulSet UpdateStrategy to RollingUpdate {"ReplicaSet": "mongodb/example-mongodb"}
2021-12-15T15:01:48.063Z ERROR controllers/replica_set_controller.go:231 Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "example-mongodb" is invalid: [status.currentMongoDBArbiters: Required value, status.currentStatefulSetArbitersReplicas: Required value] {"ReplicaSet": "mongodb/example-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
/workspace/controllers/replica_set_controller.go:231
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227`

**Comment by bznein** [comment]
It looks like the reconciliation doesn't succeed.
The secret is created at the very last step of a successful reconciliation so it makes sense not seeing it.

Have you applied the most recent CRD? 

Can you do one of the following?

1. Paste the output of `kubectl get crd mongodbcommunity.mongodbcommunity.mongodb.com -o yaml`
2. Apply the updated CRD: `kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml` from the root of the repo

**Comment by daniel-tasnadi-epam** [comment]
@bznein yeah, sure.
Here is the output of the first command. Also, after the second command apply nothing changed.

`apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{"controller-gen.kubebuilder.io/version":"v0.4.1"},"creationTimestamp":null,"name":"mongodbcommunity.mongodbcommunity.mongodb.com"},"spec":{"group":"mongodbcommunity.mongodb.com","names":{"kind":"MongoDBCommunity","listKind":"MongoDBCommunityList","plural":"mongodbcommunity","shortNames":["mdbc"],"singular":"mongodbcommunity"},"scope":"Namespaced","versions":[{"additionalPrinterColumns":[{"description":"Current state of the MongoDB deployment","jsonPath":".status.phase","name":"Phase","type":"string"},{"description":"Version of MongoDB server","jsonPath":".status.version","name":"Version","type":"string"}],"name":"v1","schema":{"openAPIV3Schema":{"description":"MongoDBCommunity is the Schema for the mongodbs API","properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"description":"MongoDBCommunitySpec defines the desired state of MongoDB","properties":{"additionalMongodConfig":{"description":"AdditionalMongodConfig is additional configuration that can be passed to each data-bearing mongod at runtime. Uses the same structure as the mongod configuration file: https://docs.mongodb.com/manual/reference/configuration-options/","nullable":true,"type":"object","x-kubernetes-preserve-unknown-fields":true},"arbiters":{"description":"Arbiters is the number of arbiters to add to the Replica Set. It is not recommended to have more than one arbiter per Replica Set. More info: https://docs.mongodb.com/manual/tutorial/add-replica-set-arbiter/","type":"integer"},"automationConfig":{"description":"AutomationConfigOverride is merged on top of the operator created automation config. Processes are merged by name. Currently Only the process.disabled field is supported.","properties":{"processes":{"items":{"description":"OverrideProcess contains fields that we can override on the AutomationConfig processes.","properties":{"disabled":{"type":"boolean"},"name":{"type":"string"}},"required":["disabled","name"],"type":"object"},"type":"array"}},"required":["processes"],"type":"object"},"featureCompatibilityVersion":{"description":"FeatureCompatibilityVersion configures the feature compatibility version that will be set for the deployment","type":"string"},"members":{"description":"Members is the number of members in the replica set","type":"integer"},"replicaSetHorizons":{"description":"ReplicaSetHorizons Add this parameter and values if you need your database to be accessed outside of Kubernetes. This setting allows you to provide different DNS settings within the Kubernetes cluster and to the Kubernetes cluster. The Kubernetes Operator uses split horizon DNS for replica set members. This feature allows communication both within the Kubernetes cluster and from outside Kubernetes.","items":{"additionalProperties":{"type":"string"},"type":"object"},"type":"array"},"security":{"description":"Security configures security features, such as TLS, and authentication settings for a deployment","properties":{"authentication":{"properties":{"ignoreUnknownUsers":{"default":true,"nullable":true,"type":"boolean"},"modes":{"description":"Modes is an array specifying which authentication methods should be enabled.","items":{"enum":["SCRAM","SCRAM-SHA-256","SCRAM-SHA-1"],"type":"string"},"type":"array"}},"required":["modes"],"type":"object"},"roles":{"description":"User-specified custom MongoDB roles that should be configured in the deployment.","items":{"description":"CustomRole defines a custom MongoDB role.","properties":{"authenticationRestrictions":{"description":"The authentication restrictions the server enforces on the role.","items":{"description":"AuthenticationRestriction specifies a list of IP addresses and CIDR ranges users are allowed to connect to or from.","properties":{"clientSource":{"items":{"type":"string"},"type":"array"},"serverAddress":{"items":{"type":"string"},"type":"array"}},"required":["clientSource","serverAddress"],"type":"object"},"type":"array"},"db":{"description":"The database of the role.","type":"string"},"privileges":{"description":"The privileges to grant the role.","items":{"description":"Privilege defines the actions a role is allowed to perform on a given resource.","properties":{"actions":{"items":{"type":"string"},"type":"array"},"resource":{"description":"Resource specifies specifies the resources upon which a privilege permits actions. See https://docs.mongodb.com/manual/reference/resource-document for more.","properties":{"anyResource":{"type":"boolean"},"cluster":{"type":"boolean"},"collection":{"type":"string"},"db":{"type":"string"}},"type":"object"}},"required":["actions","resource"],"type":"object"},"type":"array"},"role":{"description":"The name of the role.","type":"string"},"roles":{"description":"An array of roles from which this role inherits privileges.","items":{"description":"Role is the database role this user should have","properties":{"db":{"description":"DB is the database the role can act on","type":"string"},"name":{"description":"Name is the name of the role","type":"string"}},"required":["db","name"],"type":"object"},"type":"array"}},"required":["db","privileges","role"],"type":"object"},"type":"array"},"tls":{"description":"TLS configuration for both client-server and server-server communication","properties":{"caCertificateSecretRef":{"description":"CaCertificateSecret is a reference to a Secret containing the certificate for the CA which signed the server certificates The certificate is expected to be available under the key \"ca.crt\"","properties":{"name":{"type":"string"}},"required":["name"],"type":"object"},"caConfigMapRef":{"description":"CaConfigMap is a reference to a ConfigMap containing the certificate for the CA which signed the server certificates The certificate is expected to be available under the key \"ca.crt\" This field is ignored when CaCertificateSecretRef is configured","properties":{"name":{"type":"string"}},"required":["name"],"type":"object"},"certificateKeySecretRef":{"description":"CertificateKeySecret is a reference to a Secret containing a private key and certificate to use for TLS. The key and cert are expected to be PEM encoded and available at \"tls.key\" and \"tls.crt\". This is the same format used for the standard \"kubernetes.io/tls\" Secret type, but no specific type is required. Alternatively, an entry tls.pem, containing the concatenation of cert and key, can be provided. If all of tls.pem, tls.crt and tls.key are present, the tls.pem one needs to be equal to the concatenation of tls.crt and tls.key","properties":{"name":{"type":"string"}},"required":["name"],"type":"object"},"enabled":{"type":"boolean"},"optional":{"description":"Optional configures if TLS should be required or optional for connections","type":"boolean"}},"required":["enabled"],"type":"object"}},"type":"object"},"statefulSet":{"description":"StatefulSetConfiguration holds the optional custom StatefulSet that should be merged into the operator created one.","properties":{"spec":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"required":["spec"],"type":"object"},"type":{"description":"Type defines which type of MongoDB deployment the resource should create","enum":["ReplicaSet"],"type":"string"},"users":{"description":"Users specifies the MongoDB users that should be configured in your deployment","items":{"properties":{"db":{"description":"DB is the database the user is stored in. Defaults to \"admin\"","type":"string"},"name":{"description":"Name is the username of the user","type":"string"},"passwordSecretRef":{"description":"PasswordSecretRef is a reference to the secret containing this user's password","properties":{"key":{"description":"Key is the key in the secret storing this password. Defaults to \"password\"","type":"string"},"name":{"description":"Name is the name of the secret storing this user's password","type":"string"}},"required":["name"],"type":"object"},"roles":{"description":"Roles is an array of roles assigned to this user","items":{"description":"Role is the database role this user should have","properties":{"db":{"description":"DB is the database the role can act on","type":"string"},"name":{"description":"Name is the name of the role","type":"string"}},"required":["db","name"],"type":"object"},"type":"array"},"scramCredentialsSecretName":{"description":"ScramCredentialsSecretName appended by string \"scram-credentials\" is the name of the secret object created by the mongoDB operator for storing SCRAM credentials These secrets names must be different for each user in a deployment.","pattern":"^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$","type":"string"}},"required":["name","passwordSecretRef","roles","scramCredentialsSecretName"],"type":"object"},"type":"array"},"version":{"description":"Version defines which version of MongoDB will be used","type":"string"}},"required":["security","type","users"],"type":"object"},"status":{"description":"MongoDBCommunityStatus defines the observed state of MongoDB","properties":{"currentMongoDBArbiters":{"type":"integer"},"currentMongoDBMembers":{"type":"integer"},"currentStatefulSetArbitersReplicas":{"type":"integer"},"currentStatefulSetReplicas":{"type":"integer"},"message":{"type":"string"},"mongoUri":{"type":"string"},"phase":{"type":"string"},"version":{"type":"string"}},"required":["currentMongoDBArbiters","currentMongoDBMembers","currentStatefulSetArbitersReplicas","currentStatefulSetReplicas","mongoUri","phase"],"type":"object"}},"type":"object"}},"served":true,"storage":true,"subresources":{"status":{}}}]},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2021-12-15T10:23:45Z"
  generation: 1
  name: mongodbcommunity.mongodbcommunity.mongodb.com
  resourceVersion: "1959"
  uid: f3d9889f-1f3a-4b2f-940f-978b3d4decc0
spec:
  conversion:
    strategy: None
  group: mongodbcommunity.mongodb.com
  names:
    kind: MongoDBCommunity
    listKind: MongoDBCommunityList
    plural: mongodbcommunity
    shortNames:
    - mdbc
    singular: mongodbcommunity
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the MongoDB deployment
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Version of MongoDB server
      jsonPath: .status.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: MongoDBCommunity is the Schema for the mongodbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MongoDBCommunitySpec defines the desired state of MongoDB
            properties:
              additionalMongodConfig:
                description: 'AdditionalMongodConfig is additional configuration that
                  can be passed to each data-bearing mongod at runtime. Uses the same
                  structure as the mongod configuration file: https://docs.mongodb.com/manual/reference/configuration-options/'
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              arbiters:
                description: 'Arbiters is the number of arbiters to add to the Replica
                  Set. It is not recommended to have more than one arbiter per Replica
                  Set. More info: https://docs.mongodb.com/manual/tutorial/add-replica-set-arbiter/'
                type: integer
              automationConfig:
                description: AutomationConfigOverride is merged on top of the operator
                  created automation config. Processes are merged by name. Currently
                  Only the process.disabled field is supported.
                properties:
                  processes:
                    items:
                      description: OverrideProcess contains fields that we can override
                        on the AutomationConfig processes.
                      properties:
                        disabled:
                          type: boolean
                        name:
                          type: string
                      required:
                      - disabled
                      - name
                      type: object
                    type: array
                required:
                - processes
                type: object
              featureCompatibilityVersion:
                description: FeatureCompatibilityVersion configures the feature compatibility
                  version that will be set for the deployment
                type: string
              members:
                description: Members is the number of members in the replica set
                type: integer
              replicaSetHorizons:
                description: ReplicaSetHorizons Add this parameter and values if you
                  need your database to be accessed outside of Kubernetes. This setting
                  allows you to provide different DNS settings within the Kubernetes
                  cluster and to the Kubernetes cluster. The Kubernetes Operator uses
                  split horizon DNS for replica set members. This feature allows communication
                  both within the Kubernetes cluster and from outside Kubernetes.
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
              security:
                description: Security configures security features, such as TLS, and
                  authentication settings for a deployment
                properties:
                  authentication:
                    properties:
                      ignoreUnknownUsers:
                        default: true
                        nullable: true
                        type: boolean
                      modes:
                        description: Modes is an array specifying which authentication
                          methods should be enabled.
                        items:
                          enum:
                          - SCRAM
                          - SCRAM-SHA-256
                          - SCRAM-SHA-1
                          type: string
                        type: array
                    required:
                    - modes
                    type: object
                  roles:
                    description: User-specified custom MongoDB roles that should be
                      configured in the deployment.
                    items:
                      description: CustomRole defines a custom MongoDB role.
                      properties:
                        authenticationRestrictions:
                          description: The authentication restrictions the server
                            enforces on the role.
                          items:
                            description: AuthenticationRestriction specifies a list
                              of IP addresses and CIDR ranges users are allowed to
                              connect to or from.
                            properties:
                              clientSource:
                                items:
                                  type: string
                                type: array
                              serverAddress:
                                items:
                                  type: string
                                type: array
                            required:
                            - clientSource
                            - serverAddress
                            type: object
                          type: array
                        db:
                          description: The database of the role.
                          type: string
                        privileges:
                          description: The privileges to grant the role.
                          items:
                            description: Privilege defines the actions a role is allowed
                              to perform on a given resource.
                            properties:
                              actions:
                                items:
                                  type: string
                                type: array
                              resource:
                                description: Resource specifies specifies the resources
                                  upon which a privilege permits actions. See https://docs.mongodb.com/manual/reference/resource-document
                                  for more.
                                properties:
                                  anyResource:
                                    type: boolean
                                  cluster:
                                    type: boolean
                                  collection:
                                    type: string
                                  db:
                                    type: string
                                type: object
                            required:
                            - actions
                            - resource
                            type: object
                          type: array
                        role:
                          description: The name of the role.
                          type: string
                        roles:
                          description: An array of roles from which this role inherits
                            privileges.
                          items:
                            description: Role is the database role this user should
                              have
                            properties:
                              db:
                                description: DB is the database the role can act on
                                type: string
                              name:
                                description: Name is the name of the role
                                type: string
                            required:
                            - db
                            - name
                            type: object
                          type: array
                      required:
                      - db
                      - privileges
                      - role
                      type: object
                    type: array
                  tls:
                    description: TLS configuration for both client-server and server-server
                      communication
                    properties:
                      caCertificateSecretRef:
                        description: CaCertificateSecret is a reference to a Secret
                          containing the certificate for the CA which signed the server
                          certificates The certificate is expected to be available
                          under the key "ca.crt"
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      caConfigMapRef:
                        description: CaConfigMap is a reference to a ConfigMap containing
                          the certificate for the CA which signed the server certificates
                          The certificate is expected to be available under the key
                          "ca.crt" This field is ignored when CaCertificateSecretRef
                          is configured
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      certificateKeySecretRef:
                        description: CertificateKeySecret is a reference to a Secret
                          containing a private key and certificate to use for TLS.
                          The key and cert are expected to be PEM encoded and available
                          at "tls.key" and "tls.crt". This is the same format used
                          for the standard "kubernetes.io/tls" Secret type, but no
                          specific type is required. Alternatively, an entry tls.pem,
                          containing the concatenation of cert and key, can be provided.
                          If all of tls.pem, tls.crt and tls.key are present, the
                          tls.pem one needs to be equal to the concatenation of tls.crt
                          and tls.key
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      enabled:
                        type: boolean
                      optional:
                        description: Optional configures if TLS should be required
                          or optional for connections
                        type: boolean
                    required:
                    - enabled
                    type: object
                type: object
              statefulSet:
                description: StatefulSetConfiguration holds the optional custom StatefulSet
                  that should be merged into the operator created one.
                properties:
                  spec:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - spec
                type: object
              type:
                description: Type defines which type of MongoDB deployment the resource
                  should create
                enum:
                - ReplicaSet
                type: string
              users:
                description: Users specifies the MongoDB users that should be configured
                  in your deployment
                items:
                  properties:
                    db:
                      description: DB is the database the user is stored in. Defaults
                        to "admin"
                      type: string
                    name:
                      description: Name is the username of the user
                      type: string
                    passwordSecretRef:
                      description: PasswordSecretRef is a reference to the secret
                        containing this user's password
                      properties:
                        key:
                          description: Key is the key in the secret storing this password.
                            Defaults to "password"
                          type: string
                        name:
                          description: Name is the name of the secret storing this
                            user's password
                          type: string
                      required:
                      - name
                      type: object
                    roles:
                      description: Roles is an array of roles assigned to this user
                      items:
                        description: Role is the database role this user should have
                        properties:
                          db:
                            description: DB is the database the role can act on
                            type: string
                          name:
                            description: Name is the name of the role
                            type: string
                        required:
                        - db
                        - name
                        type: object
                      type: array
                    scramCredentialsSecretName:
                      description: ScramCredentialsSecretName appended by string "scram-credentials"
                        is the name of the secret object created by the mongoDB operator
                        for storing SCRAM credentials These secrets names must be
                        different for each user in a deployment.
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                      type: string
                  required:
                  - name
                  - passwordSecretRef
                  - roles
                  - scramCredentialsSecretName
                  type: object
                type: array
              version:
                description: Version defines which version of MongoDB will be used
                type: string
            required:
            - security
            - type
            - users
            type: object
          status:
            description: MongoDBCommunityStatus defines the observed state of MongoDB
            properties:
              currentMongoDBArbiters:
                type: integer
              currentMongoDBMembers:
                type: integer
              currentStatefulSetArbitersReplicas:
                type: integer
              currentStatefulSetReplicas:
                type: integer
              message:
                type: string
              mongoUri:
                type: string
              phase:
                type: string
              version:
                type: string
            required:
            - currentMongoDBArbiters
            - currentMongoDBMembers
            - currentStatefulSetArbitersReplicas
            - currentStatefulSetReplicas
            - mongoUri
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: MongoDBCommunity
    listKind: MongoDBCommunityList
    plural: mongodbcommunity
    shortNames:
    - mdbc
    singular: mongodbcommunity
  conditions:
  - lastTransitionTime: "2021-12-15T10:23:45Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-12-15T10:23:45Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1`

**Comment by daniel-tasnadi-epam** [comment]
Based on some testing, it's working in version 0.7.2, but with latest master it isn't.

**Comment by tibulca** [comment]
Hi @daniel-tasnadi-epam 
It looks like one of the recent changes in the CRD caused the issue you found. 
This was breaking the reconciliation process and that's why the secret was not created either (since the creation of the secret is at the end of the reconciliation process).
I implemented the fix, so if you pull the latest master, you should be able to successfully install the operator and deploy a replica set.
Ciprian

**Comment by xadereq** [comment]
@tibulca so if I deployed already, what step should I take in order to fix this issue? Applying new CRD and then deleting `MongoDBCommunity` kind and creating new one or should applying new CRD be enough?

**Comment by tibulca** [comment]
@xadereq applying the new CRD should be enough (you can also restart the operator pod if you want the changes to be picked up faster)

**Comment by xadereq** [comment]
> @xadereq applying the new CRD should be enough (you can also restart the operator pod if you want the changes to be picked up faster)

thank you, worked flawlessly. Merry Christmas ;)

**Comment by daniel-tasnadi-epam** [comment]
Hi @tibulca ,

I can confirm now your fix working properly. Thank you for your help!
