### ISSUE TITLE
Limit memory usage for mongod

### ISSUE THREAD

**Issue by daniloasfigueiredo** [mongodb/mongodb-kubernetes-operator#830]
Hi, we using mongodb operator with 3 replicaset, each replica is hosted on a dedicaded node with 16GB of RAM, and we configure the pod limits do use max 14GB of RAM, but the mongod container recognizes the all provioned memory on the node, in this case 16GB of RAM.

Out problem is, every time the mongod container tries to use more than 12GB of ram, the pod is restarted by kubernetes, because the high memory usage.

Is any method to limit the memory usage for mongodb service (for example 12GB)? after some research we found the parameter below

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    **storage.wiredTiger.engineConfig.cacheSizeGB: 12**

**Comment by bznein** [comment]
> storage.wiredTiger.engineConfig.cacheSizeGB: 12

My understanding is that this should work.

If it doesn't, can you exec into one of the pods and show the content of /data/automation-mongod.conf?

Thanks

**Comment by priyolahiri** [comment]
Please re-open if this did not work for you.

**Comment by Jammy42** [comment]
See my answer in

https://github.com/mongodb/mongodb-kubernetes-operator/issues/936

**Comment by gmartynov** [comment]
faced this issue on a new cluster with Ubuntu 22.04 and cgroup v2 on a k8s hosts
on a previous cluster with Ubuntu 20.04 and cgroup v1 everything worked fine

is there a hope for solution ?
