### ISSUE TITLE
Support for Service Binding Operator

### ISSUE THREAD

**Issue by baijum** [mongodb/mongodb-kubernetes-operator#831]
[Service Binding Operator](https://github.com/redhat-developer/service-binding-operator) helps to connect applications with services on Kubernetes and OpenShift. Service Binding Operator implements [Service Binding Specification](https://github.com/servicebinding/spec). There are two ways to support Service Binding Operator.

1. Make the MongoDB Kubernetes resource compliant with [Provisioned Service](https://github.com/servicebinding/spec#provisioned-service) (a spec concept for backing service)
2. Use the [Secret Generation Extension](https://github.com/servicebinding/spec/blob/main/extensions/secret-generation.md) used by the Service Binding Operator.

The second option would be easy to implement.

**Comment by bznein** [comment]
Thanks @baijum for opening this issue.

This looks like an interesting feature; there's no immediate plan to implement it but I think it would be a good candidate for external contributors.

**Comment by slemeur** [comment]
Hi - we would really like to contribute that support to the MongoDB Kubernetes operator. @baijum has created the following PR for supporting the effort #847 .
Have you been able to give a look?
