### ISSUE TITLE
Can not change domain cluster name.

### ISSUE THREAD

**Issue by necipakca** [mongodb/mongodb-kubernetes-operator#832]
I have tried to change default "cluster.local" domain name to my cluster name.
I have define ENV like below I could not sure which is right so I have set both :)

       - name: CLUSTER_DNS_NAME
          value: my-k8s-cls
        - name: CLUSTER_NAME
          value: my-k8s-cls

But my connection string same like 

mongodb://my-dev-mongodb-0.my-dev-mongodb-svc.ygd-namespace-dev.svc.**cluster.local**:27017

I am now sure because of this or not I can not connect to mongo in pod with correct string like 
mongodb://my-dev-mongodb-0.my-dev-mongodb-svc.ygd-namespace-dev.svc.**my-k8s-cls**:27017

Its say connection refused. Is it check DNS name to validate ?

 - Operator Version : 0.7.2
 - MongoDB Image used : latest

 - Distribution : On-prem - vanilla
 - Version : 1.21.5
 - Image Registry location:  quay

**Comment by irajdeep** [comment]
Hi @necipakca the cluster domain can now be configured using environment variable in the operator pod. It can be found in the release notes: https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.7.1

**Comment by necipakca** [comment]
Adjusting CLUSTER_DOMAIN env on manager.yaml works. Thanks.
