### ISSUE TITLE
deploy/clusterwide/role_binding.yaml is not compatible with kustomize

### ISSUE THREAD

**Issue by haslersn** [mongodb/mongodb-kubernetes-operator#834]
https://github.com/mongodb/mongodb-kubernetes-operator/pull/672 added the subject namespace `<your-namespace>`. However, this broke compatibility of that file with kustomize. kustomize will insert the subject namespace, if it's `default` or empty, but not if it's `<your-namespace>`.

**Comment by bznein** [comment]
Hi @haslersn 

#672 was created to fix #663. Wouldn't this change bring back the same issue?

**Comment by haslersn** [comment]
Well, in cases where the line is needed, it needs to be changed anyway. If necessary, one can remove the comment.
