### ISSUE TITLE
Mongodb log file is not getting generated in kubernetes statefulset yaml 

### ISSUE THREAD

**Issue by Archanadorepalli** [mongodb/mongodb-kubernetes-operator#841]
**What did you do to encounter the bug?**
1. Go to 'we have added log file path in mongod.conf.orig file, but still its not generating log file'

**What did you expect?**
As we have mentioned log file path in mongod.conf.orig, is there any way to write config file from statefulset yaml to generate log in the mentioned log path

**What happened instead?**
Log file is not present. var/log/mongodb/ folder is empty.

**Operator Information**
 - 5.0 version community edision
 - MongoDB Image used is latest

**Kubernetes Cluster Information**
 - 1.20.5

**Comment by priyolahiri** [comment]
what is the location of the file mogod.conf.orig you are changing? is it on disk?

**Comment by priyolahiri** [comment]
the way to override the log location would be to change it in the deployment. if you look at the sample [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml), you should see an additionalMongodConfig section. If you put in systemLog.path: "/path_to_log_file_location", you should be able to override the log file location. for additional settings, you can refer to this [doc](https://docs.mongodb.com/manual/reference/configuration-options/).

**Comment by priyolahiri** [comment]
Feel free to re-open the issue if not resolved
