### ISSUE TITLE
service account missing when deploying database to different namespace than operator

### ISSUE THREAD

**Issue by kkendzia** [mongodb/mongodb-kubernetes-operator#850]
**What did you do to encounter the bug?**
1. Deploy operator to namespace: mongodb-operator with watchNamespace: "*"
2. Try to deploy example-mongodb to namespace: mongodb-test

**What did you expect?**
Deployment with 3 replicas.

**What happened instead?**
`pods "example-mongodb-0" is forbidden: error looking up service account mongodb-test/mongodb-database: serviceaccount "mongodb-database" not found`

**Operator Information**
 - Operator Version: 0.27.0
 - MongoDB Image used: default

**Kubernetes Cluster Information**
 - Distribution: Debian
 - Version: 11
 - Image Registry location (quay, or an internal registry)
 - Kubernetes Version 1.22.5

Is it intended, that if I deploy a database into a different namespace than the operator, I have to create a service account by my own? What is the reason for this? Is it planned to be changed?

**Comment by drsheff** [comment]
same problem

`serviceaccount "mongodb-database" not found`

**Comment by irajdeep** [comment]
Hi @kkendzia 

> Is it intended, that if I deploy a database into a different namespace than the operator, I have to create a service account by my own? What is the reason for this?

Indeed that's the intended behavior, in the current setup to have the database deployed in a different namespace other than the operator, one needs to create the service account in that particular namespace(provided here: https://github.com/mongodb/mongodb-kubernetes-operator/tree/master/config/rbac). We intentionally decided the operator not to give permission to create serviceaccounts automatically since a fair amount of our users considered it to be too much permission granted to the operator.

**Comment by irajdeep** [comment]
Feel free to re-open if creating the service-account in the namespace doesn't work out.

**Comment by Starefossen** [comment]
I don't understand why the database needs this serviceaccount? This seams counter intuitive and just overly complex imho...

**Comment by dcharbonnier** [comment]
@irajdeep why is this sa used ? the operator already have the authorizations on all the namespaces

**Comment by godwhoa** [comment]
@reselbob You'll need to create other resources as well for it to work. 

```
git clone https://github.com/mongodb/mongodb-kubernetes-operator
# If you explore that `rbac` folder it contains service account, role, role bindings in it.
kubectl apply -k mongodb-kubernetes-operator/config/rbac/  --namespace mynamespace
kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mynamespace
```

**Comment by tamer-hassan** [comment]
Documentation is now very detailed and covers all three different scopes (single namespace, multi-namespace, and cluster-wide), covering both the use of kubectl and helm
https://www.mongodb.com/docs/kubernetes-operator/master/tutorial/set-scope-k8s-operator/#ns-scope-different-ns

**Comment by reselbob** [comment]
Thanks! @tamer-hassan

**Comment by nick4fake** [comment]
This seems very counterintuitive and too verbose for multi-namespace management. Every single operator that I've used simply supports specifying namespaces, instead of provisioning additional resources to *each* namespace that we want to work with. It becomes tedious as soon as you have 10+ namespaces

**Comment by adamtwiss** [comment]
The operator seems really poorly designed to need to do this. These permissions seem to grant access to do things like Get secrets, when reading secrets would be far better done through create Pod definitions that pull these in through manifests put into the environment of the Pod. This is the way that most similar operators work.

**Comment by danbopes** [comment]
Just tried to get kickstarted, and ran into this too. Really poor design :(

**Comment by dijareoracle** [comment]
I see the commit that was used to fix this issue, but this still happens despite the service account being in the operators namespace

**Comment by whrami** [comment]
Deserves a fix. This is clearly not what your users want.
