### ISSUE TITLE
How to disable download gz for offline installation?

### ISSUE THREAD

**Issue by stanltam** [mongodb/mongodb-kubernetes-operator#853]
**What did you do to encounter the bug?**
1.Install the operator
2. Install the CRD replicasets

**What did you expect?**
Start up normally

**What happened instead?**
Saw the database container is not ready, from the log, it shows
{"logType":"automation-agent-verbose","contents":"[2022-01-16T13:22:36.994+0000] [.info] [src/util/download.go:DownloadUngzipUntarCustomClientWithHeaders:257] <db-zdsotc-dev-2> [13:22:36.994] Starting extraction of url=https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-rhel80-4.4.0.tgz to /var/lib/mongodb-mms-automation/mongodb-linux-x86_64-4.4.0-ent. This may be happening in parallel with download"}

Seems it is trying to download from internet, but the environment is isolated from the internet. 

**Screenshots**

**Operator Information**
 - Operator Version
 mongo-enterprise-operator:1.13.0
 - MongoDB Image used
enterprise-database:2.0.2

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by priyolahiri** [comment]
This is the repository for the community operator. Please go to support.mongodb.com to raise issues for the Enterprise Operator.
