### ISSUE TITLE
The pod is in the running state, but the cluster state is pending

### ISSUE THREAD

**Issue by jinchengsix** [mongodb/mongodb-kubernetes-operator#860]
**What did you do to encounter the bug?**
kubectl apply -f config/xxxx_cr.yaml 

**What did you expect?**
cluster state is running

**What happened instead?**
cluster state is pending

**Screenshots**
![image](https://user-images.githubusercontent.com/39333013/150099147-b03ae279-d9d1-4ac0-84e9-6ac8fc01fc3b.png)

**Operator Information**
 - Operator 0.7.0
 - MongoDB Image used 4.0.3

**Additional context**
kubectl describe statefulSet mongodb
![image](https://user-images.githubusercontent.com/39333013/150100973-9aa49110-282e-4be3-b430-05a83c658d0d.png)

kubectl describe pod mongodb-0
![image](https://user-images.githubusercontent.com/39333013/150101024-dc98f72f-e828-4fcb-828a-3e2980c0099d.png)

kubectl logs mongodb-0 -c mongod
![image](https://user-images.githubusercontent.com/39333013/150101151-907ef0da-bc84-490c-acc6-0c659d766cb1.png)

kubectl logs mongodb-0 -c mongodb-agent
![image](https://user-images.githubusercontent.com/39333013/150101405-bd826acb-1f61-4077-9593-7981f9b0c85c.png)

kubectl logs operator-pod
![image](https://user-images.githubusercontent.com/39333013/150101609-cd2af1b6-510d-4788-8100-c2c2b139598c.png)

I‘m stuck now , cannot do scale in or scale out or upgrade operations , please help , thanks a lot

**Comment by jinchengsix** [comment]
here is my cr file

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.0.3"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: shuaib
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    # the additional config passed to the mongod process can be specified
    # either in nested or dot notation
    storage:
      wiredTiger:
        engineConfig:
          journalCompressor: zlib
    net:
      bindIp: 0.0.0.0
      port: 27017
      maxIncomingConnections: 2048
    systemLog:
      destination: file
      path: /data/mongod.log
      logAppend: true
      logRotate: reopen
    operationProfiling:
      mode: "off"
      slowOpThresholdMs: 100
    replication:
      oplogSizeMB: 1024
      enableMajorityReadConcern: true
    setParameter:
      cursorTimeoutMillis: 600000
    processManagement:
      fork: true

  statefulSet:
    spec:
      # Name for the service object created by the operator
      serviceName: mongodb-svc
      selector: {}
      # Specifies a size for the data volume different from the default 10Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: csi-standard
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: csi-standard
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              image: dockerhub.qingcloud.com/mongodb_op/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.3
              imagePullSecrets:
                - name: qingcloud
              imagePullPolicy: IfNotPresent
            - name: mongodb-agent-readinessprobe
              image: dockerhub.qingcloud.com/mongodb_op/mongodb-kubernetes-readinessprobe:1.0.6
              imagePullSecrets:
                - name: qingcloud
              imagePullPolicy: IfNotPresent
          containers:
            - name: mongod
              image: dockerhub.qingcloud.com/mongodb_op/mongo:4.0.3
              imagePullSecrets:
                - name: qingcloud
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 1
                  memory: 500M
                requests:
                  cpu: 1
                  memory: 400M

            - name: mongodb-agent
              image: dockerhub.qingcloud.com/mongodb_op/mongodb-agent:11.0.5.6963-1
              imagePullSecrets:
                - name: qingcloud
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 1
                  memory: 500M
                requests:
                  cpu: 1
                  memory: 400M
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: shuaib

**Comment by jinchengsix** [comment]
sorry ， my mistake

**Comment by maximeancellin** [comment]
Hi @jinchengsix,

We have same issue on some namespace with MongoDB operator (and inside list of issues we have found some topics about same status of MongoDB agent).

Can you share what did you found to solve that ? 
What's your "mistake" ?

Thanks
