### ISSUE TITLE
mongodbcommunity.mongodbcommunity.mongodb.com status is not showing up in version 0.7.2

### ISSUE THREAD

**Issue by GayathriRameshK** [mongodb/mongodb-kubernetes-operator#861]
**What did you do to encounter the bug?**
I have installed mongoDB kubernetes operator version 0.7.2. while trying to check the status of mdbc using below command, the status is not showing up.
kubectl get mongodbcommunity.mongodbcommunity.mongodb.com

**What did you expect?**
The mdbc status should be showing as running or failed.

**What happened instead?**
No Status generated.
NAME                PHASE   VERSION
opupgrade-mongodb   

**Screenshots**

**Operator Information**
 - Operator Version - 0.7.2
 - MongoDB Image used - 5.0.5

If possible, please include:
 - `kubectl describe` output

```
Name:         opupgrade-mongodb
Namespace:    mdb-opupgrade
Labels:       argocd.argoproj.io/instance=
Annotations:  <none>
API Version:  mongodbcommunity.mongodb.com/v1
Kind:         MongoDBCommunity
Metadata:
  Creation Timestamp:  2022-01-18T13:11:19Z
  Generation:          3
  Managed Fields:
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
      f:spec:
        .:
        f:additionalMongodConfig:
          .:
          f:net.maxIncomingConnections:
          f:net.tls.mode:
          f:storage.directoryPerDB:
        f:members:
        f:replicaSetHorizons:
        f:security:
          .:
          f:authentication:
            .:
            f:ignoreUnknownUsers:
            f:modes:
          f:roles:
          f:tls:
            .:
            f:caConfigMapRef:
              .:
              f:name:
            f:certificateKeySecretRef:
              .:
              f:name:
            f:enabled:
        f:statefulSet:
          .:
          f:spec:
            .:
            f:template:
            f:volumeClaimTemplates:
        f:type:
        f:users:
        f:version:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2022-01-18T13:11:19Z
  Resource Version:  95451687
  Self Link:        
  UID:               
```

**Comment by rodrigovalin** [comment]
hi @GayathriRameshK,

When submitting a bug report, please add as much infomation as possible; that makes it easier for us to understand the problem and be able to help you!

If you look at the bug report, we also request:

- yaml definition of your `MongoDBCommuntity` resources (`kubectl get mdbc -o yaml`)
- logs of the Operator Pod (`kubectl logs <operator-pod>`)

**Comment by GayathriRameshK** [comment]
$kubectl get mdbc -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

$Kubectl logs <operator pod>
2022-01-24T11:13:57.410Z        INFO    controllers/replica_set_controller.go:132       Reconciling MongoDB     {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.410Z        DEBUG   controllers/replica_set_controller.go:134       Validating MongoDB.Spec {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.410Z        DEBUG   controllers/replica_set_controller.go:143       Ensuring the service exists     {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.422Z        INFO    controllers/replica_set_controller.go:390       The service already exists... moving forward: services "opupgrade-mongodb-svc" already exists       {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.422Z        INFO    controllers/mongodb_tls.go:40   Ensuring TLS is correctly configured    {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.422Z        INFO    controllers/mongodb_tls.go:94   Successfully validated TLS config       {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.422Z        INFO    controllers/replica_set_controller.go:277       TLS is enabled, creating/updating TLS secret    {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.427Z        ERROR   controllers/mongodb_users.go:26 user password secret "mdb-opupgrade/scrt-appuser" not found: %!s(<nil>)     {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.ensureUserResources
        /workspace/controllers/mongodb_users.go:26
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
        /workspace/controllers/replica_set_controller.go:177
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227
2022-01-24T11:13:57.428Z        DEBUG   controllers/replica_set_controller.go:348       Enabling TLS on an existing deployment, the StatefulSet must be updated first   {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.428Z        INFO    controllers/replica_set_controller.go:288       Creating/Updating StatefulSet   {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.441Z        DEBUG   controllers/replica_set_controller.go:298       Ensuring StatefulSet is ready, with type: RollingUpdate {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.441Z        INFO    controllers/replica_set_controller.go:308       Creating/Updating AutomationConfig      {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.462Z        DEBUG   scram/scram.go:165      Credentials have not changed, using credentials stored in: secret/mongodba-scram-credentials
2022-01-24T11:13:57.462Z        DEBUG   scram/scram.go:149      password secret was not found, reading from credentials from secret/mongoappuser-scram-credentials
2022-01-24T11:13:57.489Z        DEBUG   scram/scram.go:165      Credentials have not changed, using credentials stored in: secret/mongoexporter-scram-credentials
2022-01-24T11:13:57.508Z        DEBUG   scram/scram.go:165      Credentials have not changed, using credentials stored in: secret/mongobackup-scram-credentials
2022-01-24T11:13:57.509Z        DEBUG   controllers/replica_set_controller.go:429       AutomationConfigMembersThisReconciliation       {"mdb.AutomationConfigMembersThisReconciliation()": 3}
2022-01-24T11:13:57.509Z        DEBUG   controllers/replica_set_controller.go:331       Waiting for agents to reach version 4   {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.510Z        INFO    agent/agent_readiness.go:52     All 3 Agents have reached Goal state    {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.510Z        DEBUG   controllers/replica_set_controller.go:202       Resetting StatefulSet UpdateStrategy to RollingUpdate   {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
2022-01-24T11:13:57.524Z        ERROR   controllers/replica_set_controller.go:231       Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "opupgrade-mongodb" is invalid: [status.currentMongoDBArbiters: Required value, status.currentStatefulSetArbitersReplicas: Required value] {"ReplicaSet": "mdb-opupgrade/opupgrade-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
        /workspace/controllers/replica_set_controller.go:231
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227

**Comment by mircea-cosbuc** [comment]
Hi @GayathriRameshK, it seems like the `mongodbcommunity` resource you're trying to create might be invalid. Can you please share the manifest you're trying to apply to the cluster?

**Comment by GayathriRameshK** [comment]
Please find the manifest file below:

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: opupgrade
spec:
  members: 3
  type: ReplicaSet
  #arbiters: 1
  version: "5.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
      ignoreUnknownUsers: false
#custom role start
    roles:
      - role: role-restore
        db: admin
        privileges:
          - resource:
              anyResource: true
            actions:
              - anyAction
        roles: []
#custom role end

  users:
    - name: mongodba
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: scrt-dbauser
      roles:
        - name: root
          db: admin
        - name: role-restore
          db: admin
      scramCredentialsSecretName: mongodba-scram
  
  additionalMongodConfig:
    #storage.wiredTiger.engineConfig.journalCompressor: zlib
    net.tls.allowConnectionsWithoutCertificates: false

#use specific storage class, CPU & Memory - start
  # persistent: true
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: mongodb-sc 
            resources:
              requests:
                storage: 6Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: mongodb-sc 
              requests:
                storage: 6Gi

      template:
        spec:
          containers:
            - name: "mongodb-agent"
              readinessProbe:
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: 200m
                  memory: 200Mi
                limits:
                  cpu: 500m
                  memory: 500Mi
            - name: "mongod"
              resources:
                requests:
                  cpu: 500m
                  memory: 500Mi
                limits:
                  cpu: 1
                  memory: 1Gi
          
#use specific storage class, CPU & Memory - end

**Comment by GayathriRameshK** [comment]
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: opupgrade
spec:
  members: 3
  type: ReplicaSet
  #arbiters: 1
  version: "5.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
      ignoreUnknownUsers: false
#custom role start
    roles:
      - role: role-restore
        db: admin
        privileges:
          - resource:
              anyResource: true
            actions:
              - anyAction
        roles: []
#custom role end

  users:
    - name: mongodba
      db: admin
      passwordSecretRef: 
        name: my-dbauser
      roles:
        - name: root
          db: admin
        - name: role-restore
          db: admin
      scramCredentialsSecretName: mongodba-scram
  
  additionalMongodConfig:
    #storage.wiredTiger.engineConfig.journalCompressor: zlib
    net.tls.allowConnectionsWithoutCertificates: false

#use specific storage class, CPU & Memory - start
 
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: mongodba-sc
            resources:
              requests:
                storage: 6Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: mongodba-sc 
              requests:
                storage: 6Gi
 template:
        spec:
           containers:
            - name: "mongodb-agent"
              readinessProbe:
                timeoutSeconds: 5
              resources:
                requests:
                  cpu: 200m
                  memory: 200Mi
                limits:
                  cpu: 500m
                  memory: 500Mi
            - name: "mongod"
              resources:
                requests:
                  cpu: 500m
                  memory: 500Mi
                limits:
                  cpu: 1
                  memory: 1Gi
          
#use specific storage class, CPU & Memory - end

**Comment by GayathriRameshK** [comment]
Hi,

Now the Status and Version showing up.
$kubectl get mongodbcommunity.mongodbcommunity.mongodb.com 
NAME                  PHASE     VERSION
opupgrade-mongodb         Running   5.0.5

**Short name : mdbc is not showing up now** 
$kubectl get mdbc
No resources found in namespace.

Please find the below CRD that I am using
```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: mongodbcommunity.mongodbcommunity.mongodb.com
spec:
  group: mongodbcommunity.mongodb.com
  names:
    kind: MongoDBCommunity
    listKind: MongoDBCommunityList
    plural: mongodbcommunity
    shortNames:
    - mdbc
    singular: mongodbcommunity
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of the MongoDB deployment
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Version of MongoDB server
      jsonPath: .status.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: MongoDBCommunity is the Schema for the mongodbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MongoDBCommunitySpec defines the desired state of MongoDB
            properties:
              additionalMongodConfig:
                description: 'AdditionalMongodConfig is additional configuration that
                  can be passed to each data-bearing mongod at runtime. Uses the same
                  structure as the mongod configuration file: https://docs.mongodb.com/manual/reference/configuration-options/'
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              arbiters:
                description: Arbiters is the number of arbiters (each counted as a
                  member) in the replica set
                type: integer
              featureCompatibilityVersion:
                description: FeatureCompatibilityVersion configures the feature compatibility
                  version that will be set for the deployment
                type: string
              members:
                description: Members is the number of members in the replica set
                type: integer
              replicaSetHorizons:
                description: ReplicaSetHorizons Add this parameter and values if you
                  need your database to be accessed outside of Kubernetes. This setting
                  allows you to provide different DNS settings within the Kubernetes
                  cluster and to the Kubernetes cluster. The Kubernetes Operator uses
                  split horizon DNS for replica set members. This feature allows communication
                  both within the Kubernetes cluster and from outside Kubernetes.
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
              security:
                description: Security configures security features, such as TLS, and
                  authentication settings for a deployment
                properties:
                  authentication:
                    properties:
                      ignoreUnknownUsers:
                        default: true
                        nullable: true
                        type: boolean
                      modes:
                        description: Modes is an array specifying which authentication
                          methods should be enabled.
                        items:
                          enum:
                          - SCRAM
                          - SCRAM-SHA-256
                          - SCRAM-SHA-1
                          type: string
                        type: array
                    required:
                    - modes
                    type: object
                  roles:
                    description: User-specified custom MongoDB roles that should be
                      configured in the deployment.
                    items:
                      description: CustomRole defines a custom MongoDB role.
                      properties:
                        authenticationRestrictions:
                          description: The authentication restrictions the server
                            enforces on the role.
                          items:
                            description: AuthenticationRestriction specifies a list
                              of IP addresses and CIDR ranges users are allowed to
                              connect to or from.
                            properties:
                              clientSource:
                                items:
                                  type: string
                                type: array
                              serverAddress:
                                items:
                                  type: string
                                type: array
                            required:
                            - clientSource
                            - serverAddress
                            type: object
                          type: array
                        db:
                          description: The database of the role.
                          type: string
                        privileges:
                          description: The privileges to grant the role.
                          items:
                            description: Privilege defines the actions a role is allowed
                              to perform on a given resource.
                            properties:
                              actions:
                                items:
                                  type: string
                                type: array
                              resource:
                                description: Resource specifies specifies the resources
                                  upon which a privilege permits actions. See https://docs.mongodb.com/manual/reference/resource-document
                                  for more.
                                properties:
                                  anyResource:
                                    type: boolean
                                  cluster:
                                    type: boolean
                                  collection:
                                    type: string
                                  db:
                                    type: string
                                type: object
                            required:
                            - actions
                            - resource
                            type: object
                          type: array
                        role:
                          description: The name of the role.
                          type: string
                        roles:
                          description: An array of roles from which this role inherits
                            privileges.
                          items:
                            description: Role is the database role this user should
                              have
                            properties:
                              db:
                                description: DB is the database the role can act on
                                type: string
                              name:
                                description: Name is the name of the role
                                type: string
                            required:
                            - db
                            - name
                            type: object
                          type: array
                      required:
                      - db
                      - privileges
                      - role
                      type: object
                    type: array
                  tls:
                    description: TLS configuration for both client-server and server-server
                      communication
                    properties:
                      caCertificateSecretRef:
                        description: CaCertificateSecret is a reference to a Secret
                          containing the certificate for the CA which signed the server
                          certificates The certificate is expected to be available
                          under the key "ca.crt"
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      caConfigMapRef:
                        description: CaConfigMap is a reference to a ConfigMap containing
                          the certificate for the CA which signed the server certificates
                          The certificate is expected to be available under the key
                          "ca.crt" This field is ignored when CaCertificateSecretRef
                          is configured
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      certificateKeySecretRef:
                        description: CertificateKeySecret is a reference to a Secret
                          containing a private key and certificate to use for TLS.
                          The key and cert are expected to be PEM encoded and available
                          at "tls.key" and "tls.crt". This is the same format used
                          for the standard "kubernetes.io/tls" Secret type, but no
                          specific type is required. Alternatively, an entry tls.pem,
                          containing the concatenation of cert and key, can be provided.
                          If all of tls.pem, tls.crt and tls.key are present, the
                          tls.pem one needs to be equal to the concatenation of tls.crt
                          and tls.key
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      enabled:
                        type: boolean
                      optional:
                        description: Optional configures if TLS should be required
                          or optional for connections
                        type: boolean
                    required:
                    - enabled
                    type: object
                type: object
              statefulSet:
                description: StatefulSetConfiguration holds the optional custom StatefulSet
                  that should be merged into the operator created one.
                properties:
                  spec:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - spec
                type: object
              type:
                description: Type defines which type of MongoDB deployment the resource
                  should create
                enum:
                - ReplicaSet
                type: string
              users:
                description: Users specifies the MongoDB users that should be configured
                  in your deployment
                items:
                  properties:
                    db:
                      description: DB is the database the user is stored in. Defaults
                        to "admin"
                      type: string
                    name:
                      description: Name is the username of the user
                      type: string
                    passwordSecretRef:
                      description: PasswordSecretRef is a reference to the secret
                        containing this user's password
                      properties:
                        key:
                          description: Key is the key in the secret storing this password.
                            Defaults to "password"
                          type: string
                        name:
                          description: Name is the name of the secret storing this
                            user's password
                          type: string
                      required:
                      - name
                      type: object
                    roles:
                      description: Roles is an array of roles assigned to this user
                      items:
                        description: Role is the database role this user should have
                        properties:
                          db:
                            description: DB is the database the role can act on
                            type: string
                          name:
                            description: Name is the name of the role
                            type: string
                        required:
                        - db
                        - name
                        type: object
                      type: array
                    scramCredentialsSecretName:
                      description: ScramCredentialsSecretName appended by string "scram-credentials"
                        is the name of the secret object created by the mongoDB operator
                        for storing SCRAM credentials
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                      type: string
                  required:
                  - name
                  - passwordSecretRef
                  - roles
                  - scramCredentialsSecretName
                  type: object
                type: array
              version:
                description: Version defines which version of MongoDB will be used
                type: string
            required:
            - security
            - type
            - users
            type: object
          status:
            description: MongoDBCommunityStatus defines the observed state of MongoDB
            properties:
              currentMongoDBMembers:
                type: integer
              currentStatefulSetReplicas:
                type: integer
              message:
                type: string
              mongoUri:
                type: string
              phase:
                type: string
              version:
                type: string
            required:
            - currentMongoDBMembers
            - currentStatefulSetReplicas
            - mongoUri
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []```

**Comment by mircea-cosbuc** [comment]
Hi @GayathriRameshK , looking at the status, it seems like your cluster hasn't accepted the shortname yet for the resource. Can you provide the output to 
```
kubectl explain mdbc
```
to possibly identify any conflict?

**Comment by GayathriRameshK** [comment]
kubectl explain mdbc


KIND:     MongoDBCommunity
VERSION:  mongodb.com/v1

DESCRIPTION:
     <empty>

**Comment by mircea-cosbuc** [comment]
Thanks @GayathriRameshK, it looks like you're encountering a conflict with an older version of the CRD, the correct version should be `mongodbcommunity.mongodb.com/v1`:
```
kubectl explain mdbc
KIND:     MongoDBCommunity
VERSION:  mongodbcommunity.mongodb.com/v1
...
```
which explains why the short names are not registering.

Can you try the upgrade steps in https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#upgrade-the-operator and see if the issue persists?

**Comment by GayathriRameshK** [comment]
On upgrading the operator from 0.5.0 to 0.7.2, getting the below error in pulling busybox image.

There are no useful logs from operator and pod.  Mdbc shorthand is still an issue.


```
kubectl get mongodbcommunity.mongodbcommunity.mongodb.com
NAME                PHASE     VERSION
opupgrade-mongodb   Pending   
```

```


Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               37s                default-scheduler        Successfully assigned mdb-opupgrade/opupgrade-mongodb-0
  Normal   SuccessfulAttachVolume  36s                attachdetach-controller  AttachVolume.Attach succeeded for volume 
  Normal   SuccessfulAttachVolume  36s                attachdetach-controller  AttachVolume.Attach succeeded for volume 
  Normal   Pulled                  19s                kubelet                  Successfully pulled image "busybox:latest" in 637.95559ms
  Normal   Pulled                  18s                kubelet                  Successfully pulled image "busybox:latest" in 615.456255ms
  Normal   Created                 17s (x2 over 19s)  kubelet                  Created container change-data-dir-permissions
  Normal   Started                 17s (x2 over 19s)  kubelet                  Started container change-data-dir-permissions
  Warning  BackOff                 15s (x2 over 16s)  kubelet                  Back-off restarting failed container
  Normal   Pulling                 0s (x3 over 20s)   kubelet                  Pulling image "busybox:latest"
```

**Comment by GayathriRameshK** [comment]
On taking the logs from busybox, it seems there is some permission issue
```
chown: /data/index-23--7947836235866560666.wt: Operation not permitted
chown: /data/journal/WiredTigerPreplog.0000000001: Operation not permitted
chown: /data/journal/WiredTigerPreplog.0000000002: Operation not permitted
chown: /data/journal/WiredTigerLog.0000000003: Operation not permitted
chown: /data/journal: Operation not permitted
chown: /data/journal: Operation not permitted
chown: /data/storage.bson: Operation not permitted
chown: /data/index-26--7947836235866560666.wt: Operation not permitted
chown: /data/index-16--7947836235866560666.wt: Operation not permitted
chown: /data/collection-6--7947836235866560666.wt: Operation not permitted
chown: /data/automation-mongod.conf: Operation not permitted

```

security context used in manager.yaml
```

        securityContext:
          readOnlyRootFilesystem: true
          #runAsNonRoot: true
          runAsUser: 2000
```
