### ISSUE TITLE
MongoDB Community Kubernetes Operator can deploy replica set with arbiter?

### ISSUE THREAD

**Issue by stanltam** [mongodb/mongodb-kubernetes-operator#864]
**What did you do to encounter the bug?**
Currently, my k8s environment has some limitation and need to deploy a replica set with 2 data node and 1 arbiter. 
May I know if MongoDB Community Kubernetes Operator can deploy replica set with arbiter?

**Comment by irajdeep** [comment]
Hi @stanltam 

Yes, it is possible you can configure it under [spec.arbiters](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml#L57)

**Comment by irajdeep** [comment]
Feel free to re-open, if configuring the arbiters doesn't work.
