### ISSUE TITLE
Connection string in another namespace

### ISSUE THREAD

**Issue by yovanoc** [mongodb/mongodb-kubernetes-operator#881]
Hello, it's not a bug, but I want some advice. I own a k8s cluster with 2 namespaces: `dev` and `prod`. I want a database for each of this environment. If I put the operator in a namespace `mongodb` I can't access the secrets in my other namespace for the `connectionString.standardSrv` thing. But I can't put a MongoDBCommunity deployment in each namespace too because it creates a ClusterIP.

What's the best way to have a database for each environments, thanks

**Comment by chatton** [comment]
Hi @yovanoc 

What issues are you running into exactly with the services that are created by the operator?

The operator will always create connection string secrets in the namespace that the `MongoDBCommunity` resource is deployed to. 

Is your goal to access the secrets from a namespace that is not `dev` or `prod`?

**Comment by yovanoc** [comment]
No, this is the exact opposite. I want to access in the namespace `dev` and `prod` the secret `connectionString.standardSrv`. But the operator is in the `mongodb` namespace. I just want to know what's the best way to use the operator with a database for each environments in their own namespace

**Comment by chatton** [comment]
I see, in that case you should be either able to deploy a single operator in cluster wide mode in any namespace, or if you prefer deploy an operator per-namespace. So one in the `prod` namespace and one in the `dev` namespace. These will then only watch resources you create in the namespace of the operator itself.

**Comment by yovanoc** [comment]
I want to deploy a cluster wide operator, but when in other deployments in `dev` and `prod` I want to use `connectionString.standardSrv` its impossible because secrets are only on the `mongodb` namespace where I put the operator

**Comment by yovanoc** [comment]
Is this something not standard? I was thinking its a basic example, or I miss something?

**Comment by eugene-marchanka** [comment]
From [stackoverflow](https://stackoverflow.com/questions/46297949/sharing-secret-across-namespaces):

Secret API objects reside in a namespace. They can only be referenced by pods in that same namespace. Basically, you will have to create the secret for every namespace.

https://kubernetes.io/docs/concepts/configuration/secret/#details

**Comment by yovanoc** [comment]
> From [stackoverflow](https://stackoverflow.com/questions/46297949/sharing-secret-across-namespaces):
> 
> Secret API objects reside in a namespace. They can only be referenced by pods in that same namespace. Basically, you will have to create the secret for every namespace.
> 
> https://kubernetes.io/docs/concepts/configuration/secret/#details

I know that, but first its just a hack and then it doesn't work at all because the secrets needs resources in the other namespace too or the crds or I can't remember but it doesn't work. I am just asking what's the best way to tackle this. for now, I have hardcoded the connection string in my yml deployment files

**Comment by eugene-marchanka** [comment]
We are facing the same type of issue with our application and seems like there are only 2 options available:
1. Copy secrets from `mongodb` namespace to app namespace
2. As you mentioned - hardcode the connection string
I think this is a k8s underneath limitation to it and not sure if it has something to do with mongodb operator itself
🤷🏻‍♂️

**Comment by MGlants** [comment]
We could add annotation to created secrets for using it in reflector

**Comment by szechp** [comment]
i concur, a way to save secret across namespaces would be nice.

**Comment by siegenthalerroger** [comment]
@dan-mckean this isn't stale and should be re-opened.
