### ISSUE TITLE
Issues deploying on OpenShift

### ISSUE THREAD

**Issue by noelo** [mongodb/mongodb-kubernetes-operator#89]
Hi, 
I'm using the operator on OpenShift 4.3 and I'm seeing a readiness probe failure on, I think, the mongodb-agent pod.
I've followed the instructions in the readme to deploy. Due to the probe failure the pod isn't added to the created service.

Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0+b4261e0", GitCommit:"b4261e07ed", GitTreeState:"clean", BuildDate:"2019-07-06T03:16:01Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"b9b84e0", GitTreeState:"clean", BuildDate:"2020-04-26T20:16:35Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

$ cat tournamentdb.yml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: tournamentdb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"

$ oc get pods
NAME                                           READY   STATUS      RESTARTS   AGE
mongodb-kubernetes-operator-687d7bfcb8-c9z6l   1/1     Running     0          10m
tournamentdb-0                                 1/2     Running     0          4m36s

goroutine 1 [running]:
main.main()
      /Users/cianhatton/go/src/github.com/10gen/ops-manager-kubernetes/probe/readiness.go:239 +0x277
0s    Warning   Unhealthy   pod/tournamentdb-0   Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied

$ oc describe pod tournamentdb-0
Name:               tournamentdb-0
Namespace:          service-binding-demo
Priority:           0
PriorityClassName:  <none>
Node:               crc-dv9sm-master-0/192.168.126.11
Start Time:         Sun, 05 Jul 2020 13:23:59 +0100
Labels:             app=tournamentdb-svc
                    controller-revision-hash=tournamentdb-55cf6df467
                    statefulset.kubernetes.io/pod-name=tournamentdb-0
Annotations:        k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "openshift-sdn",
                          "interface": "eth0",
                          "ips": [
                              "10.128.0.183"
                          ],
                          "dns": {},
                          "default-route": [
                              "10.128.0.1"
                          ]
                      }]
                    openshift.io/scc: restricted
Status:             Running
IP:                 10.128.0.183
Controlled By:      StatefulSet/tournamentdb
Init Containers:
  mongod-prehook:
    Container ID:  cri-o://ccb200a7439fd36b7b34600f6a7e259721b102143cc24cba8125b24a954e2775
    Image:         quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.1
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook@sha256:4b7a96acb9e8a936412a87fbdcdb3ccac7b785069bd096c09f7d175648a27ca1
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      pre-stop-hook
      /hooks/pre-stop-hook
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 05 Jul 2020 13:24:04 +0100
      Finished:     Sun, 05 Jul 2020 13:24:04 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-jfgzx (ro)
Containers:
  mongodb-agent:
    Container ID:  cri-o://bf54b34dd87f4e67fa572c414e29f77b8af54fecca87251fb010354fe9e38522
    Image:         quay.io/mongodb/mongodb-agent:10.15.1.6468-1
    Image ID:      quay.io/mongodb/mongodb-agent@sha256:b24548bf5104acd7fed88791542d9c8eaf80ee47714f1cb248670c3735995928
    Port:          <none>
    Host Port:     <none>
    Command:
      agent/mongodb-agent
      -cluster=/var/lib/automation/config/automation-config
      -skipMongoStart
      -noDaemonize
      -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      -serveStatusPort=5000
    State:          Running
      Started:      Sun, 05 Jul 2020 13:24:07 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:      500m
      memory:   400M
    Readiness:  exec [/var/lib/mongodb-mms-automation/probes/readinessprobe] delay=5s timeout=1s period=10s #success=1 #failure=240
    Environment:
      AGENT_STATUS_FILEPATH:  /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
    Mounts:
      /data from data-volume (rw)
      /var/lib/automation/config from automation-config (ro)
      /var/log/mongodb-mms-automation/healthstatus from healthstatus (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-jfgzx (ro)
  mongod:
    Container ID:  cri-o://b94b3d41b5172bdabd02d3ad7a36332b92e05e03814334056030b8566315b553
    Image:         mongo:4.2.6
    Image ID:      docker.io/library/mongo@sha256:8c48baa1571469d7f5ae6d603b92b8027ada5eb39826c009cb33a13b46864908
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      while [ ! -f /data/automation-mongod.conf ]; do sleep 3 ; done ; sleep 2 ;
      # start mongod with this configuration
      mongod -f /data/automation-mongod.conf ;

      # start the pre-stop-hook to restart the Pod when needed
      # If the Pod does not require to be restarted, the pre-stop-hook will
      # exit(0) for Kubernetes to restart the container.
      /hooks/pre-stop-hook ;

    State:          Running
      Started:      Sun, 05 Jul 2020 13:24:07 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:     500m
      memory:  400M
    Environment:
      AGENT_STATUS_FILEPATH:   /healthstatus/agent-health-status.json
      PRE_STOP_HOOK_LOG_PATH:  /hooks/pre-stop-hook.log
    Mounts:
      /data from data-volume (rw)
      /healthstatus from healthstatus (rw)
      /hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-jfgzx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-tournamentdb-0
    ReadOnly:   false
  healthstatus:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  hooks:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  automation-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      tournamentdb-config
    Optional:  false
  mongodb-kubernetes-operator-token-jfgzx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-kubernetes-operator-token-jfgzx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From                         Message
  ----     ------     ----              ----                         -------
  Normal   Scheduled  58s               default-scheduler            Successfully assigned service-binding-demo/tournamentdb-0 to crc-dv9sm-master-0
  Normal   Pulling    56s               kubelet, crc-dv9sm-master-0  Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.1"
  Normal   Pulled     53s               kubelet, crc-dv9sm-master-0  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.1"
  Normal   Created    53s               kubelet, crc-dv9sm-master-0  Created container mongod-prehook
  Normal   Started    53s               kubelet, crc-dv9sm-master-0  Started container mongod-prehook
  Normal   Pulling    53s               kubelet, crc-dv9sm-master-0  Pulling image "quay.io/mongodb/mongodb-agent:10.15.1.6468-1"
  Normal   Pulled     50s               kubelet, crc-dv9sm-master-0  Successfully pulled image "quay.io/mongodb/mongodb-agent:10.15.1.6468-1"
  Normal   Created    50s               kubelet, crc-dv9sm-master-0  Created container mongodb-agent
  Normal   Started    50s               kubelet, crc-dv9sm-master-0  Started container mongodb-agent
  Normal   Pulled     50s               kubelet, crc-dv9sm-master-0  Container image "mongo:4.2.6" already present on machine
  Normal   Created    50s               kubelet, crc-dv9sm-master-0  Created container mongod
  Normal   Started    50s               kubelet, crc-dv9sm-master-0  Started container mongod
  Warning  Unhealthy  1s (x5 over 41s)  kubelet, crc-dv9sm-master-0  Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied

goroutine 1 [running]:
main.main()
  /Users/cianhatton/go/src/github.com/10gen/ops-manager-kubernetes/probe/readiness.go:239 +0x277

**Comment by antonlisovenko** [comment]
Hi @noelo 

thanks for your report

have you tried to configure the MongoDB using the instructions given in another issue? https://github.com/mongodb/mongodb-kubernetes-operator/issues/58#issuecomment-642528641

**Comment by noelo** [comment]
Yes I tried that as well but same result as far as I remember

**Comment by cacois** [comment]
This issue persists, and is present in Openshift 4.5 as well. The error indicates a permissions error inside the mongodb pod itself, so this is unrelated to any config vars set for the operator (i've tried that solution, it had no effect). 

Advice on a workaround would be appreciated, currently the operator is unusable in openshift.

**Comment by chatton** [comment]
Hi, as of the latest operator release, v0.1.1 it should now be possible to configure the CRD in such a way to run correctly in openshift, see the following [example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml)

The `MANAGED_SECURITY_CONTEXT` environment variable must be set to true in both the agent, and mongod container and also the **operator deployment** itself.

Let me know if this works as expected.

**Comment by dalareo** [comment]
This solved my issue with EKS.

I got: 

```Error: couldn't add user: not master :```

when trying to create users from shell inside init-container of my application.

**Comment by gopikrishnamanne** [comment]
> Hi, as of the latest operator release, v0.1.1 it should now be possible to configure the CRD in such a way to run correctly in openshift, see the following [example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml)
> 
> The `MANAGED_SECURITY_CONTEXT` environment variable must be set to true in both the agent, and mongod container and also the **operator deployment** itself.
> 
> Let me know if this works as expected.



> Hi, as of the latest operator release, v0.1.1 it should now be possible to configure the CRD in such a way to run correctly in openshift, see the following [example](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_openshift_cr.yaml)
> 
> The `MANAGED_SECURITY_CONTEXT` environment variable must be set to true in both the agent, and mongod container and also the **operator deployment** itself.
> 
> Let me know if this works as expected.

HI, could you please elaborate more on this. I applied the `MANAGED_SECURITY_CONTEXT` environment variable in the operator config and the pod is failing continuously.

**Comment by saksham1gupta** [comment]
Readiness probe failing for mongod-agent container
mongodb community status: PENDING
