### ISSUE TITLE
Mongo Opensource operator TLS Issues

### ISSUE THREAD

**Issue by rajivml** [mongodb/mongodb-kubernetes-operator#891]
HI, 

We are using mongo opensource operator to deploy Mongo enterprise because we don't want the complexity of ops manager and the same approach was suggested by mongo team.

**Kubernetes Operator Version:** mongodb-kubernetes-operator:0.7.0
**MongoDB Version:** mongodb-enterprise-appdb-database:4.4.4-ent

For creating certificate resources, we are using this template https://raw.githubusercontent.com/mongodb/helm-charts/735367f4db9933489ea36a53cc4e71797b7263b9/charts/community-operator/templates/mongodbcommunity_cr_with_tls.yaml

But since 0.7.0 operator doesn't have support for passing CA via **caCertificateSecretRef** , we are instead passing CA via configmap via this property **caConfigMapRef** as stated in this document https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/secure.md

Now we are facing 2 issues on our environments, 

* Since we were are using this template for creating certificate resources, In this template, duration was specified as one year for final certificate but duration was not specified for root CA and if duration is not specified for root certificate, it will by default expire in 3 months and if root CA is expired, no matter how much duration is specified on final certificate, it will not be valid  https://github.com/mongodb/helm-charts/blob/735367f4db9933489ea36a53cc4e71797b7263b9/charts/community-operator/templates/mongodbcommunity_cr_with_tls.yaml
* The second issue we are facing is, when the underlying cert is rotated, the pem files that these secrets are referring to are different as a result mongo isn't coming up because the pem files which the **mongodb-replica-set-config** is being referred are different from that of pem file which the **mongodb-replica-set-server-certificate-key** secret is referring to 

![image](https://user-images.githubusercontent.com/46923567/153745058-9c4010f4-01e3-4d9c-8d8b-781afbdd26cb.png)

and as a result mongoDB is going down with this kind of error where the pod itself isn't coming up if the pod is restarted because it's trying to access an file which no longer exist 

![image](https://user-images.githubusercontent.com/46923567/153746691-7a629a60-8328-465a-82c2-232fe9908948.png)

or the pod is up but u will see the cert expiry errors like this,  

![image](https://user-images.githubusercontent.com/46923567/153745667-8fd2e5e6-2edf-4fd0-9352-d0f110c1d23e.png)

Our expectation is operator handles the cert rotation seamlessly but that is not happening because of these 2 issues, few of our customers have ran into this recently, to mitigate the issue on their environment, we manually changed the paths in mongodb-replica-set-config to whatever mongodb-replica-set-server-certificate-key is referring to.

To replicate the issue, try reducing the cert duration to 1h and renewbefore to 5m and then try

**Comment by priyolahiri** [comment]
This is being looked into. We will update on this soon.

**Comment by rajivml** [comment]
@priyolahiri sure, #00887782

**Comment by priyolahiri** [comment]
closing the issue here. will be addressed in the support ticket.
