### ISSUE TITLE
OLM support and joinging operatorhub

### ISSUE THREAD

**Issue by m-yosefpor** [mongodb/mongodb-kubernetes-operator#913]
Currently only enterprise mongodb operator is available via OLM and in operatorhub. It would be great if we have mongodb community operator shipped via OLM and in operatorhub too.

**Comment by chris93111** [comment]
Hello any update ?

**Comment by Morriz** [comment]
hello?

**Comment by m-yosefpor** [comment]
still needed

**Comment by marandalucas** [comment]
Hi folks! Could you re-considered opening the feature request? We are excited about having the same implementation that in the enterprise version. :=)
