### ISSUE TITLE
Connecting to Headless Service from Docker Desktop (localhost)

### ISSUE THREAD

**Issue by napalm684** [mongodb/mongodb-kubernetes-operator#92]
Given this appears to be implemented using a headless service with no cluster IP and no kube-proxy support as a result, how does one using docker desktop on Windows connect via an IDE tool like Robo 3T etc? I have tried just about everything I can think of with no success. Any guidance would be much appreciated!

**Comment by ImadYamane** [comment]
I am facing the same issue, did you find a solution?

**Comment by napalm684** [comment]
Nope I gave up and used helm.
