### ISSUE TITLE
How do I fully uninstall this operator?

### ISSUE THREAD

**Issue by ghost** [mongodb/mongodb-kubernetes-operator#922]
Hi, I installed the operator with FluxCD to a custom namespace. I should have flux deleted first, but instead I deleted the namespace, then flux uninstalled. Now when I try to re-install, I get the error:

MongoDBCommunity/default/wfc-mongod namespace not specified, error: the server could not find the requested resource (patch mongodbcommunity.mongodbcommunity.mongodb.com wfc-mongod)

However the list is empty when I kubectl get mongodbcommunity -A. 

It looks like there is a dead dangling reference to my old wfc-mongod. How do I get rid of everything to start from scratch?

**Comment by alarmsdk** [comment]
Same question
