### ISSUE TITLE
arm64 platform，mongodb-agent  container failed to run。

### ISSUE THREAD

**Issue by 283713406** [mongodb/mongodb-kubernetes-operator#925]
**What did you do to encounter the bug?**

1. Install a 2 member replicaset using the operator's MongoDBCommunity CRD.
2. Wait for all pods to boot but the replicaset READY is 1/2，mongodb-agent  container failed to run 

**What did you expect?**
ReplicaSet to boot successfully and all container run successfully..

**What happened instead?**
I am running on the arm64 platform, and the mongodb agent container reports an error:  [.error] [src/main/cm.go:mainLoop:462] [05:59:22.908] Error loading desired cluster configs : [05:59:22.908] Error retrieving cluster config from '/var/lib/automation/config/cluster-config.json' : [05:59:22.908] Cluster config did not pass validation for pre-expansion semantics : MongoDB version 4.2.6 for process = example-mongodb-0 was not found in the list of available versions : [ 4.2.6 : &{linux   [] amd64 rhel   false},&{linux   [] amd64 ubuntu   false} ]

**Screenshots**
![image](https://user-images.githubusercontent.com/19170385/158749867-80872981-0dde-4a2a-96f6-dd59eb3b4541.png)
![image](https://user-images.githubusercontent.com/19170385/158749938-6c1d03d8-2252-4d21-b2ff-09eacce54fac.png)

**Operator Information**
- Operator Version: 0.7.2
- MongoDB Image used:
   - mongod: docker.io/mongo: 4.2.6
   - mongodb-agent: quay.io/mongodb/mongodb-agent: 11.12.0.7388-1

**Kubernetes Cluster Information**
 - Distribution
 - Version  v1.19.1
 - Image Registry location (quay, or an internal registry)：docker.io and quay.io

If possible, please include:
 - `kubectl describe pod example-mongodb-0   -n mongo-test` output
![image](https://user-images.githubusercontent.com/19170385/158750389-a567b0fe-81bd-4a09-8a0a-8070e1ac8c30.png)

**Comment by mohsinonxrm** [comment]
Is there any update on this?

**Comment by dan-mckean** [comment]
Hi, apologies for the lack of response on this. 

ARM64 is not currently supported. We do plan to do it sometime next year, but the exact timing is currently undecided.

**Comment by mohsinonxrm** [comment]
@dan-mckean, thanks for getting back. Could you please just confirm my findings above? and if that is indeed causing the issue, could you perhaps please share or point me to the documentation of building the agent binaries? (not the agent image, i've already built the image).

I understand the binaries are downloaded from:
https://mciuploads.s3.amazonaws.com/mms-automation/mongodb-mms-build-agent/builds/automation-agent/hosted/mongodb-mms-automation-agent-[version].amzn2_aarch64.tar.gz

But would need to know how can I build the above myself and use that in the docker builder file.

Thanks again for getting back.

**Comment by mohsinonxrm** [comment]
@283713406 , here you go:
https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1304623123
