### ISSUE TITLE
Where is the "Free Commercial use" License ??

### ISSUE THREAD

**Issue by jinchengsix** [mongodb/mongodb-kubernetes-operator#938]
**What did you do to encounter the bug?**
Sorry this is not bug , I just don't know where to ask .. 
**What did you expect?**

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by jinchengsix** [comment]
【The MongoDB Agent binary in the agent/ directory may be used under the "Free for Commercial Use - Oct 2020" license found in agent/LICENSE.】
I can't find the directory 【agent/LICENSE】 ，can anyone show me where the "Free for Commercial Use - Oct 2020" license is , thanks a lot

**Comment by mircea-cosbuc** [comment]
Hi @jinchengsix , I think you're looking for [this file](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/scripts/dev/templates/agent/LICENSE). Thanks for pointing out the missing link to the file.
