### ISSUE TITLE
Got "getaddrinfo ENOTFOUND mongodb replica set." error message.

### ISSUE THREAD

**Issue by mike0355** [mongodb/mongodb-kubernetes-operator#946]
Hi , I'm a new on use Mongodb. When I deploy the mongodb operator on K8s from this github community，and I want to use local mongodb compass to connect this mongodb server . 
When I try to connect the mongodb server I got  "getaddrinfo ENOTFOUND mongodb replica set." error massage.
![image](https://user-images.githubusercontent.com/51089749/163519685-990f507f-f784-4035-a89c-d6ec1488d986.png)

When I finished to deploy mongodb, I use port-forward command to port-forward this service ，and see this message on my browser.
![image](https://user-images.githubusercontent.com/51089749/163519791-8e6b3378-2ed8-4195-a906-a598fe26dfdb.png)
![image](https://user-images.githubusercontent.com/51089749/163519798-79cb9ed3-abeb-4480-913d-5fa8af5d8613.png)
And here is my service...
![image](https://user-images.githubusercontent.com/51089749/163520354-7af23628-a0f5-4bb5-b930-9b5f01f1f73d.png)

And here is my secret info.
![image](https://user-images.githubusercontent.com/51089749/163519953-119cb332-c72d-4c7e-a0d2-a47c2083a003.png)

I follow this github to install and deploy mongodb, so  I think my setting is correct. But I don't know why I  get this problem.

**Comment by priyolahiri** [comment]
Please take a look at the external connectivity docs [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/external_access.md).

**Comment by sudobhat** [comment]
Try selecting the Direct connection in the General tab - and turn off TLS if you have not configured it in TLS/SSL tab

**Comment by BryanDollery** [comment]
I have the same problem when using port-forward.

![image](https://user-images.githubusercontent.com/3526157/166449772-bf1d66d2-c0b2-4695-a8f8-545c736c1bf6.png)

I have read the document referenced y priyolahiri, but it isn't related to this problem at all. 

Does anyone have any clue as to how this is meant to work? I migrated to the community operator from the bitnami helm chart, but this approach works fine with that helm chart and doesn't seem to work at all with this operator mediated deployment.

**Comment by AniketKariya** [comment]
facing the same issue, any updates?

**Comment by mike0355** [comment]
Hi , when I face this problem, I select the "Direct connect" this option  and I solved this problem.
![image](https://user-images.githubusercontent.com/51089749/175231120-202192e4-0f8a-4bab-9ad9-16c85475b140.png)

**Comment by mike0355** [comment]
And one thing need to notice , only primary MongoDB pod  can provide read data and write data function. Secondary MongoDB pods only  save the data.

**Comment by mike0355** [comment]
> I have the same problem when using port-forward.
> 
> ![image](https://user-images.githubusercontent.com/3526157/166449772-bf1d66d2-c0b2-4695-a8f8-545c736c1bf6.png)
> 
> I have read the document referenced y priyolahiri, but it isn't related to this problem at all.
> 
> Does anyone have any clue as to how this is meant to work? I migrated to the community operator from the bitnami helm chart, but this approach works fine with that helm chart and doesn't seem to work at all with this operator mediated deployment.

Is your port-forward  port is 8000:27017? that means container environment port forward to the local side's 8000 port. So you need to select the 8000 port  and select the "Direct connect".

**Comment by AniketKariya** [comment]
however, the solution creates another issue, as stating from https://www.mongodb.com/docs/compass/current/connect/general-connection/

> onnection and connect to a secondary member of a replica set, your write operations fail because it is not the primary member.

this solution, as temporary to test whether the connection succeeds is fine, but I am not sure if this would connect from backend (for instance node) as there'd be no option to connect directly, or even if there is, it would connect to secondary node and would deny any write operations. please look into this.

**Comment by mike0355** [comment]
One method can observed which one pod is primary member. It is enter to the mongodb pods container environment to check .
Use kubectl exec -it ... command.
 Also you use VIM editor to change the number of member.  If only one MongoDB pod deploy on K8s environment，and that MongoDB pod must be primary. And after you can edit again , change the number of member to another number, when you port-forward again I think you can connect to the primary pod by default.

**Comment by leo81122** [comment]
> Try selecting the Direct connection in the General tab - and turn off TLS if you have not configured it in TLS/SSL tab

You save my day(night)!

**Comment by bnhNhan** [comment]
- url: mongodb://hieunhan:********@127.0.0.1:27018:27018/?tls=false
- changer mongo with ip 127.0.0.1

**Comment by cateyelow** [comment]
the issue is cause because of /etc/hosts in your client which running MongoDB Compass.
you have to sync /etc/hosts to find your replicaset.
maybe if you use kubernetes, maybe you have to use NAT or port-forwarding 

[Example]
suggest you set /etc/hosts like that
```
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

192.168.0.X mongo0.replset.member
192.168.0.X mongo1.replset.member
192.168.0.X mongo2.replset.member
```

then you have to sync the /etc/hosts with public ip in external if you want to activate replica

```
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

121.X.X.X mongo0.replset.member
121.X.X.X mongo1.replset.member
121.X.X.X mongo2.replset.member
```

then try connect in external env

`mongodb://id:password@[your_host]:27017,[your_host]27018,[your_host]:27019/?authMechanism=SCRAM-SHA-1&replicaSet=rs0&readPreference=secondaryPreferred`
