### ISSUE TITLE
Readiness probe failing continuously with operator 0.7.3

### ISSUE THREAD

**Issue by ID2343242** [mongodb/mongodb-kubernetes-operator#949]
**What did you do to encounter the bug?**

1. Create Namespace
kubectl apply -f mongodb/namespace.yml

2. Create Operator
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml --namespace mongodb

3. Create RBAC
kubectl apply -k config/rbac/ --namespace mongodb

4. Create Operator Deployment
kubectl create -f config/manager/manager.yaml --namespace mongodb

5. Install Mongodb
kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mongodb

**What did you expect?**
A MongoDB running as a Replica Set working inside my Kubernetes cluster

**What happened instead?**

Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  4m32s (x60 over 13m)  kubelet  (combined from similar events): Readiness probe failed: 2022-04-18 16:48:52.346515 +0000 UTC m=+0.032297674 write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied

**Operator Information**
 - 0.7.3
 - 5.0.5

**Kubernetes Cluster Information**
 - microk8s
 - 1.23
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output

kubectl describe pods -n mongodb example-mongodb-0

Name:         example-mongodb-0
Namespace:    mongodb
Priority:     0
Node:         sys0001/192.168.5.84
Start Time:   Mon, 18 Apr 2022 17:38:42 +0100
Labels:       app=example-mongodb-svc
              controller-revision-hash=example-mongodb-d96648d47
              statefulset.kubernetes.io/pod-name=example-mongodb-0
Annotations:  agent.mongodb.com/version: -1
              cni.projectcalico.org/podIP: 10.1.144.29/32
              cni.projectcalico.org/podIPs: 10.1.144.29/32
Status:       Running
IP:           10.1.144.29
IPs:
  IP:           10.1.144.29
Controlled By:  StatefulSet/example-mongodb
Init Containers:
  mongod-posthook:
    Container ID:  containerd://461d9c7e4d3310a55b1e5bbdda2e80314cb3daab9d033ed3f7ddfba98d04b033
    Image:         quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook@sha256:64b27b76e89279664c227c9f6a31fd7c243a40d90b06b79e840d5488b81fd806
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      version-upgrade-hook
      /hooks/version-upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 18 Apr 2022 17:38:43 +0100
      Finished:     Mon, 18 Apr 2022 17:38:43 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ls87v (ro)
  mongodb-agent-readinessprobe:
    Container ID:  containerd://18ce22f456493453dac55aa2de99ed358f4857749a2dece2d55f8692e92a884f
    Image:         quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8
    Image ID:      quay.io/mongodb/mongodb-kubernetes-readinessprobe@sha256:fccc2a2e9da0072d24fcabb896d5536e4c292cc5ead4788b7cfcaf751bb3328e
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /probes/readinessprobe
      /opt/scripts/readinessprobe
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 18 Apr 2022 17:38:44 +0100
      Finished:     Mon, 18 Apr 2022 17:38:44 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/scripts from agent-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ls87v (ro)
Containers:
  mongod:
    Container ID:  containerd://2a00f2cb6c4658bb4731a8c89eb1f82e6549fdac10e43fa33a80fd9b066f87e9
    Image:         docker.io/mongo:5.0.6
    Image ID:      docker.io/library/mongo@sha256:fed6248ae0bb0d54c0448eb786c87120737eedc522172ee1536ad47789782348
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      
      #run post-start hook to handle version changes
      /hooks/version-upgrade
      
      # wait for config and keyfile to be created by the agent
       while ! [ -f /data/automation-mongod.conf -a -f /var/lib/mongodb-mms-automation/authentication/keyfile ]; do sleep 3 ; done ; sleep 2 ;
      
      # with mongod configured to append logs, we need to provide them to stdout as
      # mongod does not write to stdout and a log file
      tail -F /var/log/mongodb-mms-automation/mongodb.log > /dev/stdout &
      
      # start mongod with this configuration
      exec mongod -f /data/automation-mongod.conf;
      
      
    State:          Running
      Started:      Mon, 18 Apr 2022 17:38:45 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:     500m
      memory:  400M
    Environment:
      AGENT_STATUS_FILEPATH:  /healthstatus/agent-health-status.json
    Mounts:
      /data from data-volume (rw)
      /healthstatus from healthstatus (rw)
      /hooks from hooks (rw)
      /var/lib/mongodb-mms-automation/authentication from example-mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ls87v (ro)
  mongodb-agent:
    Container ID:  containerd://14195dfc33c4b15f4f8de21888d4030a63899de73ea393f375a736d85f0d6f70
    Image:         quay.io/mongodb/mongodb-agent:11.12.0.7388-1
    Image ID:      quay.io/mongodb/mongodb-agent@sha256:c0db8287814c8af6339bab3f0690858bcb2301b3c5877a3aa9553917071e9ca7
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      current_uid=$(id -u)
      AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"
      declare -r current_uid
      if ! grep -q "${current_uid}" /etc/passwd ; then
      sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
      echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
      export NSS_WRAPPER_PASSWD=/tmp/passwd
      export LD_PRELOAD=libnss_wrapper.so
      export NSS_WRAPPER_GROUP=/etc/group
      fi
      agent/mongodb-agent -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -cluster=/var/lib/automation/config/cluster-config.json -skipMongoStart -noDaemonize -useLocalMongoDbTools
    State:          Running
      Started:      Mon, 18 Apr 2022 17:38:45 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:      500m
      memory:   400M
    Readiness:  exec [/opt/scripts/readinessprobe] delay=5s timeout=1s period=10s #success=1 #failure=40
    Environment:
      AGENT_STATUS_FILEPATH:  /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      AUTOMATION_CONFIG_MAP:  example-mongodb-config
      HEADLESS_AGENT:         true
      POD_NAMESPACE:          mongodb (v1:metadata.namespace)
    Mounts:
      /data from data-volume (rw)
      /opt/scripts from agent-scripts (rw)
      /var/lib/automation/config from automation-config (ro)
      /var/lib/mongodb-mms-automation/authentication from example-mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/log/mongodb-mms-automation/healthstatus from healthstatus (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ls87v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  logs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  logs-volume-example-mongodb-0
    ReadOnly:   false
  data-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-example-mongodb-0
    ReadOnly:   false
  agent-scripts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  automation-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  example-mongodb-config
    Optional:    false
  example-mongodb-keyfile:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  healthstatus:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hooks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-ls87v:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  4m32s (x60 over 13m)  kubelet  (combined from similar events): Readiness probe failed: 2022-04-18 16:48:52.346515 +0000 UTC m=+0.032297674 write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied

 - yaml definitions for your objects
I have just used the standard install ones

 - log files for the operator and database pods

**Comment by peterjanes** [comment]
`/var/lib/automation` is a `volumeMount` from the `{dbname}-config` secret created by the operator, and that secret only contains a `cluster-config.json`entry. Can't see any way to create an `acVersion/version` path as that's an invalid field name.

**Comment by jicki** [comment]
> The readiness in 0.7.3 is also failing when you try to build it from the tag. It looks like it's now trying to read for a file `/var/lib/automation/config/acVersion/version` https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/pkg/readiness/headless/headless.go#L26 which is never created hence the readiness is always failing.
> 
> @bznein Do you have an idea how, and where does that file should be created? Thanks

I also encountered this problem, how can I solve it

**Comment by Brice187** [comment]
same problem
```
Readiness probe failed: panic: open /var/lib/automation/config/acVersion/version: no such file or directory goroutine 1 [running]: main.main() /build/main.go:225 +0x14b
```

**Comment by irajdeep** [comment]
Hi @[ID2343242](https://github.com/ID2343242)

We weren't able to reproduce the readiness.log permission denied problem based on the steps you've mentioned. The MongoDB cluster was able to reach `Running` state.

As a next step to help us troubleshoot -- could you run `kubectl edit <pod_name>` for the Mongodb pod and share the `securityContext` specified in the pod

**Comment by itaytalmi** [comment]
A workaround is available here https://github.com/mongodb/mongodb-kubernetes-operator/issues/989#issuecomment-1151020336

**Comment by irajdeep** [comment]
I am going to close this issue for now. Feel free to re-open if the issue still persists.
