### ISSUE TITLE
add a podDisruptionBudget

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#954]
The operator should (possibly optional) also set up a podDisruptionBudget for the mongoDB cluster so it doesn't break on rolling updates of the kubernetes nodes.
For example, our Cluster got 250GB of data, with that it takes 5-10 minutes for the pod to be up on the new node again. The nodes spawn faster than the pods get up, causing a downtime of the database without a pdb.

**Comment by bramk** [comment]
I also ran into an issue where 2 out of 3 pods in the statefulset where rescheduled. Can we reopen this and get it on the list? :)

**Comment by SCLogo** [comment]
for spot instances this is deal breaker. we need to add pdb manually.

**Comment by fireba11** [comment]
Yes .. you usually find out it's missing when your cluster just went down :-P
