### ISSUE TITLE
Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory

### ISSUE THREAD

**Issue by pantxisto** [mongodb/mongodb-kubernetes-operator#959]
**What did you do to encounter the bug?**
1. Create statefulset with 2 replicas.
2. Set pvc for automatic provisioning
3. Output of k describe:
```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  9m13s (x3096 over 8h)  kubelet  Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory

goroutine 1 [running]:
main.main()
           /build/main.go:218 +0x15a
  Warning  Unhealthy  4m16s (x403 over 19h)  kubelet  Readiness probe failed: command "/opt/scripts/readinessprobe" timed out
```

**What did you expect?**
/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json should exist and this error should not.

**What happened instead?**
/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json file doesn't exist and the error is thrown.

**Operator Information**
 - 0.7.3
 - 4.2.6

**Kubernetes Cluster Information**
 - Distribution: kubeadmin cluster
 - Version: v1.23.5
 - Image Registry location: quay

**Additional context**
I found that mongod and mongodb-agent containers share same volume called healthstatus. If I go to the mount path of mongod container I find agent-health-status.json file, but if I go to mount path of mongodb-agent container it is empty. It has no sense. Also, this only happen after some running time of the pod, initially the file is on both containers.

**Comment by mircea-cosbuc** [comment]
Hi @pantxisto,
Thank you for your report. A 2 member replica set should reconcile successfully, can you please share the `MongoDBCommunity` resource `yaml` to help us debug further?
The error message you're seeing could be improved, it would be better to have this logged gracefully, but it is expected during the start-up of your replica set.

**Comment by jicki** [comment]
me too

**Comment by mircea-cosbuc** [comment]
@pantxisto @jicki A couple of fixes which might address the issue have been merged and should be available with the next release. If you could provide the `MongoDBCommunity` resource to help me replicate further, please feel free to re-open.

**Comment by Trackhe** [comment]
I get the Same error with. the mongodb-community-manager 0.7.4 installed over helm and the mongodb version 5 and 4.4..15

**Comment by vnugent** [comment]
Same error.  I followed the example to install the operator and replicaset in the same namespace using kubectl.

Replicaset yaml (my mongo version = 5)
- https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml

**Comment by bokukpark** [comment]
@nileshm2501 Try mongodb 4.4.17

**Comment by nileshm2501** [comment]
> @nileshm2501 Try mongodb 4.4.17

Tried with both 4.0 and 5.0  version getting the same error

**Comment by moatorres** [comment]
Same error here.

**Comment by jurgen-weber-deltatre** [comment]
not sure why this is closed, I have the same problem. How did people resolve it?

**Comment by arf1372** [comment]
The fix just works for `mongodb==4.2.6`. When I change the image version to anything else (even `4.2`!) it will fail again.
For the exact version mentioned, it works; for everything else, it simply does not.

### Information
* Kubernetes distribution: microk8s (`MicroK8s v1.26.3 revision 4959`)
* Cluster version:
      Client Version: v1.26.3
      Kustomize Version: v4.5.7
      Server Version: v1.26.3
* Operator chart used: `community-operator-0.7.9`

P.S.
The patch which you can use to test against:
Mongo version: `4.2` instead of `4.2.6` (you can change the version to `4.4` and test again):
```diff
diff --git a/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml b/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
index 37b2881..2a0cc14 100644
--- a/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
+++ b/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
@@ -6,7 +6,7 @@ metadata:
 spec:
   members: 3
   type: ReplicaSet
-  version: "4.2.6"
+  version: "4.2"
   security:
     authentication:
       modes: ["SCRAM"]
```
(for `4.4` just edit the line says: `version: .... ` below `type: ReplicaSet`)

**Comment by arf1372** [comment]
Hi all
To @mircea-cosbuc @bokukpark 

The fix just works for `mongodb==4.2.6`. When I change the image version to anything else (even `4.2`!) it will fail again.
For the exact version mentioned, it works; for everything else, it simply does not.

### Information
* Kubernetes distribution: microk8s (`MicroK8s v1.26.3 revision 4959`)
* Cluster version:
      Client Version: v1.26.3
      Kustomize Version: v4.5.7
      Server Version: v1.26.3
* Operator chart used: `community-operator-0.7.9`

The patch which you can use to test against:
Mongo version: `4.2` instead of `4.2.6` (you can change the version to `4.4` and test again):
```diff
diff --git a/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml b/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
index 37b2881..2a0cc14 100644
--- a/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
+++ b/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
@@ -6,7 +6,7 @@ metadata:
 spec:
   members: 3
   type: ReplicaSet
-  version: "4.2.6"
+  version: "4.2"
   security:
     authentication:
       modes: ["SCRAM"]
```
(for `4.4` just edit the line says: `version: .... ` below `type: ReplicaSet`)

**Comment by paniKatarinka** [comment]
Hi all,
did anybody also have this issue and fix it differently? I would like to go within 6.0.5...downgrade to 4.2.6 is no way for me...
@arf1372 did you test it with 6.0.5?

**Comment by balait4** [comment]
Any progress on this issue? I'm also facing the same issue with `4.2` image.

**Comment by CameronHudson8** [comment]
Thankfully, after jumping my broken MongoDBCommunity version `4.4.22` to `5.0.18`, and waiting through some rough restarts of each pod that took several minutes and caused downtime, my pods stabilized and my data is still accessible. I was really worried because only one container in the first pod had been able to start after upgrading from `4.2.6` to `4.4.22`. So I essentially jumped over version `4.4.22`, which I don't think is supported. I was on community operator version `0.8.0` throughout.

**Comment by shiveshabhishek** [comment]
Hi, with mongo version 6.0.3, we are still getting the same error

```
│   Warning  Unhealthy               46m   kubelet                  Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or  │
│ directory                                                                                                                                                                                     │
```

**Comment by quazard** [comment]
Was having exactly this problem with MongoDB Agent where it was stuck showing the error described on this thread title, regardless of the MongoDB version (4, 5, 6 and even 7) and having everything on same namespace. In my case deployment was happening on a K3s cluster over a Proxmox VE VM with kvm64 processors. After changing the kind of processor on the VM (to host), deployment worked just fine.

Honestly not sure if it is a hardware thing which makes the Operator/Agent to not get readynessProbe to work as expected, given that logs have no further details, but adding this comment in case it helps anyone with a similar problem.

MongoDB Community Operator 0.8.2
MongoDB version 6.0.10
k3s cluster v1.27.5+k3s1 / proxmox ve 7.4-3

**Comment by ololoepepe** [comment]
I have faced this issue, too.

Some context: I have my own small cluster spanning 1 VPS instance (master) and 2 PCs (workers) owned by me, grographically distributed. One worker has Intel i3-3220, the other has Pentium G4560.

The bug (is it really a bug?) happens on G4560 but not on i3-3220. That is interesting, as the latter is way more old. So it's probably something related to CPUs, maybe instruction set, idk as I'm not that good with hardware.

Short answer: change the CPU (PC, VPS, etc.). More modern CPU does not guarantee you won't fact this bug, though.

**Comment by CarlosFdez77** [comment]
Same problem for me when I enable TLS security. Without it there is no problem.

`apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: cluster-mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  users:
    - name: admin-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: admin
      scramCredentialsSecretName: my-scram
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongo-tls-secret
      caConfigMapRef:
        name: mongo-tls-ca-configmap
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1"
                  memory: 22250M
                requests:
                  cpu: "0.2"
                  memory: 500M
#            - name: mongodb-agent
#              resources:
#                limits:
#                  cpu: "1"
#                  memory: 2250M
#                requests:
#                  cpu: "0.2"
#                  memory: 200M
          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: oci-bv
                resources:
                  requests:
                    storage: 10G
#            - metadata:
#                name: logs-volume
#              spec:
#                accessModes: [ "ReadWriteOnce" ]
#                storageClassName: oci-bv
#                resources:
#                  requests:
#                    storage: 2G`

Any solution?

**Comment by itsMarydan** [comment]
I have the same problem wonder if this is resolved  deploying in an eks cluster using this spec from the provided samples https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_tls_cr.yaml

**Comment by solaris24251** [comment]
I have faced this issue, too.
My context is K3s on a virtual machine in Proxmox, where the CPU is without AVX instruction.
But on another virtual machine where CPU supports AVX I don't have a problem.

**Comment by senyahnoj** [comment]
We've encountered this as well. Here's a couple of links to other people who have experienced problems with the MongoDB 5.0+ container with AVX CPU instructions

https://github.com/wekan/wekan/issues/4321
https://github.com/Graylog2/graylog-docker/issues/241
https://stackoverflow.com/questions/76126384/mongodb-5-0-requires-a-cpu-with-avx-support-container-failed-to-start

**Comment by dhalfageme** [comment]
In my case, I suspect I get this error because I have this setting:

```
spec:
  additionalMongodConfig:
    net:
      tls:
        allowConnectionsWithoutCertificates: true
```

to simpify connections from other replicas.

But, depending on the version of mongo, this setting is called `tls`or `ssl`

Adding `ssl`for an older version , it started to work

```
spec:
  additionalMongodConfig:
    net:
      tls:
        allowConnectionsWithoutCertificates: true
      ssl:
        allowConnectionsWithoutCertificates: true
```

**Comment by arunkush5** [comment]
I’ve encountered this issue as well. In my case, the k8s(EKS) cluster is running on AWS Cloud, and the pod was scheduled on an ARM-based node. The MongoDB pod was using an image that isn't compatible with ARM architecture, which caused the pod to continuously restart.
